### ISSUE TITLE
Resurrect SIG meeting

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1011]
From the [public meeting notes](https://docs.google.com/document/d/1tGKuCsSnyT2McDncVJrMgg74_z8V06riWZa0Sr79I_4/edit#heading=h.fssat5bvwd5m), it looks like the last time a SIG meeting was done was in Nov 2021. If I understand correctly, the SIG meetings were discontinued due to lack of participation.

I would like to propose to resurrect the meetings and see if there is enough interest now for having these meetings. 

If you are interested in having this, and would like to join, please reply to this issue. If we get enough interest, the maintainers of this repo can figure out the logistics - decide time, frequency, zoom accounts from OTel TC etc. (I can help with any tasks as needed.)

**Comment by cijothomas** [comment]
@open-telemetry/rust-approvers @open-telemetry/rust-maintainers - Please share your thoughts. Thank you.

**Comment by lzchen** [comment]
I would be interested!

**Comment by jtescher** [comment]
Works for me if there is interest

**Comment by lalitb** [comment]
I would be interested!

**Comment by TommyCpp** [comment]
Yep I am interested

**Comment by cijothomas** [comment]
@hdost Could you do a doodle poll for the same? I think its best to seed it with some times preferred by the maintainer/approver, and then others can add their vote..

**Comment by hdost** [comment]
> @hdost Could you do a doodle poll for the same? I think its best to seed it with some times preferred by the maintainer/approver, and then others can add their vote..

I thought of doing a doodle but originally wanted it to more general than that though I suppose we could do a doodle for the first next sig and talk about when would be good general times to have it.

**Comment by TommyCpp** [comment]
We can also rotate between different time if participants are in  mutliple time zones

**Comment by lzchen** [comment]
@hdost 
Is there a link to the doodle?

**Comment by hdost** [comment]
Doodle Link: https://doodle.com/meeting/participate/id/av8ZgB0d
Please fill out by 14 April 2023.

**Comment by hdost** [comment]
So it looks like the only time for people whom have filled it out have set tomorrow as the time. I'm gonna propose we go for that.
April 7th 2023 
16:00 – 16:30 UTC
Meeting Room: https://zoom.us/j/97571287540?pwd=Yi9NcHFia0pwM3lrU1hqRkpvalFsUT09

Add topics: https://docs.google.com/document/d/1tGKuCsSnyT2McDncVJrMgg74_z8V06riWZa0Sr79I_4/edit

As mentioned I think it's most important to get something on the calendar and then see again about future meetings. It's always possible to adapt.

**Comment by TommyCpp** [comment]
Works for me! Thanks for organizating it

**Comment by cijothomas** [comment]
will join this one ! thanks

**Comment by hdost** [comment]
The calendar has been update to reflect the new meeting time, I think @TommyCpp ? If so, thank you 👍🏼 .

I've updated the meeting link in to Google Doc.
With that I'm going to close this.

Hope to see you all there.

**Comment by TommyCpp** [comment]
Ah it's not me 😄 I think the credit goes to @cijothomas maybe?

**Comment by cijothomas** [comment]
Not me!
