### ISSUE TITLE
How to fix breaking changes (with_trace_config, install_batch)

### ISSUE THREAD

**Issue by bangbaew** [open-telemetry/opentelemetry-rust#1012]
![image](https://user-images.githubusercontent.com/29559559/228757250-7dffd01b-42bb-4cdc-97ee-b38c4dcdaab4.png)
![image](https://user-images.githubusercontent.com/29559559/228757163-9221243a-df88-4c83-8ce5-d3294ecf4141.png)

I've just updated the crates and my current code is not working anymore, how can I fix it?
Configuring the service name is all I want.

**Comment by djc** [comment]
It looks like you might have two differrent versions of crates in your dependency graph?

**Comment by cijothomas** [comment]
Closing as this seems fixed with using latest versions.
