### ISSUE TITLE
Propagators API

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-rust#1013]
According to the [spec](https://sourcegraph.com/github.com/open-telemetry/opentelemetry-specification/-/blob/specification/context/api-propagators.md
)  the propagators https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/propagation/composite.rs should be in the API instead of the SDK 

Context Conversation: https://cloud-native.slack.com/archives/C03GDP0H023/p1679426866872239

**Comment by wperron** [comment]
As far as I understand it the current structure does respect the spec; the `TextMapPropagator` is defined in the API, and specific implementations are found in the SDK. Digging around, seems like this conversation already occurred in #266. @jtescher might know more.

**Comment by hdost** [comment]
If that were the case then these should also be in the SDK. 
[Java](https://github.com/open-telemetry/opentelemetry-java/blob/f4d464a1c03b75b58ef4ce58e88c69f0fe89c9dd/api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java)
[C#](https://github.com/open-telemetry/opentelemetry-dotnet/blob/807f703e1b4d9874a92bd86d9f2d4ebe5b5d52e4/src/OpenTelemetry.Api/Context/Propagation/TraceContextPropagator.cs)

As well the specific propagators such as Jaeger and B3(a.k.a Zipkin) should be in different extension crates and the W3C ones can (probably should by included in the API). 
https://sourcegraph.com/github.com/open-telemetry/opentelemetry-specification/-/blob/specification/context/api-propagators.md#propagators-distribution
Though

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#propagators-distribution From this spec, the W3C propagators may be distributed as part of API packages.

**Comment by TommyCpp** [comment]
Distribution of propagators in other language:

| Propagator | Language | Location
| --- | ---- | ----
| baggage propagator | [Go](https://github.com/open-telemetry/opentelemetry-go/blob/85e4c467da71aa1ce1423c7bbb7a99f1810f9e43/propagation/baggage.go) | API / propagation
| baggage propagator | [Java](https://github.com/open-telemetry/opentelemetry-java/blob/aca4157d8f2cc39f5b120975c5e352e82284b2e5/api/all/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java) | API / baggage
| baggage propagator | [.NET](https://github.com/open-telemetry/opentelemetry-dotnet/blob/807f703e1b4d9874a92bd86d9f2d4ebe5b5d52e4/src/OpenTelemetry.Api/Context/Propagation/BaggagePropagator.cs) | API / propagation
| trace context propagator | [Go](https://github.com/open-telemetry/opentelemetry-go/blob/85e4c467da71aa1ce1423c7bbb7a99f1810f9e43/propagation/trace_context.go) | API / propagation
| trace context propagator | [Java](https://github.com/open-telemetry/opentelemetry-java/blob/f4d464a1c03b75b58ef4ce58e88c69f0fe89c9dd/api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java) | API / propagation
| trace context propagator | [.NET](https://github.com/open-telemetry/opentelemetry-dotnet/blob/807f703e1b4d9874a92bd86d9f2d4ebe5b5d52e4/src/OpenTelemetry.Api/Context/Propagation/TraceContextPropagator.cs) | API / propagation
| composite propagator | [Go](https://github.com/open-telemetry/opentelemetry-go/blob/85e4c467da71aa1ce1423c7bbb7a99f1810f9e43/propagation/propagation.go#L113) | API / propagation
| composite propagator | [Java](https://github.com/open-telemetry/opentelemetry-java/blob/aca4157d8f2cc39f5b120975c5e352e82284b2e5/context/src/main/java/io/opentelemetry/context/propagation/TextMapPropagator.java#L53) | API / propagation
| composite propagator | [.NET](https://github.com/open-telemetry/opentelemetry-dotnet/blob/807f703e1b4d9874a92bd86d9f2d4ebe5b5d52e4/src/OpenTelemetry.Api/Context/Propagation/CompositeTextMapPropagator.cs) | API / propagation
