### ISSUE TITLE
Contrib repo

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1014]
Currently all the components - OTel spec components (API/SDK/Exporter), instrumentations, vendor specific components are all in the same repo (*this repo*). Given the general recommendation from OpenTelemetry is to host vendor specific components in a separate "-contrib" repo, could we consider spinning up a new contrib repo, and start moving the vendor specific components there?

Most other OTel languages has started with single repo (just like OTel-Rust), and then eventually spun off a contrib repo, and moved components there. There is some logistics involved in that, but given it is something that'll be needed eventually, it'd probably be a good idea to start now when there are only few components that require "lift & shift".

(My colleagues are planning to contribute few components, mostly Exporters to OS native tracing mechanisms like Windows ETW Exporter, [Linux user_events](https://docs.kernel.org/trace/user_events.html) exporter etc. It'd be nice if we can make it to the contrib repo, but we are okay to host it here as well if there are no concerns.)

Note: I can help as needed with some logistics. (Have gone through this exercise in OTel .NET, OTel .NET Contrib spin off)

**Comment by hdost** [comment]
This is a duplicate issue https://github.com/open-telemetry/opentelemetry-rust/issues/841
