### ISSUE TITLE
`MeterProvider::meter` should not use `&'static str`

### ISSUE THREAD

**Issue by tqwewe** [open-telemetry/opentelemetry-rust#1015]
It seems like the `MeterProvider::meter` method takes `&'static str`'s for name (as well as version and schema_url).
<https://docs.rs/opentelemetry/latest/opentelemetry/metrics/trait.MeterProvider.html>

In my case, the string I want to use is not `'static`, and this means I cannot use it to create meters.

I see that the instrument builder methods take `impl Into<String>` for the names. Maybe the meter functions could take the same, or `Cow<'static, str>` directly (since it seems like thats whats stored in the [`InstrumentationLibrary`](https://docs.rs/opentelemetry/latest/opentelemetry/struct.InstrumentationLibrary.html#structfield.name))

**Comment by djc** [comment]
`Cow<'static, str>` probably makes sense, would you be able to send a PR?
