### ISSUE TITLE
Implement Console metrics exporter

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-rust#1024]
Similar to [trace](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/export/trace/stdout.rs)

**Comment by lzchen** [comment]
@TommyCpp 

If this is a valid issue, could I be assigned?

**Comment by jtescher** [comment]
I have an implementation, should have a PR shortly
