### ISSUE TITLE
Improved HTTP exporter error handling

### ISSUE THREAD

**Issue by jaymell** [open-telemetry/opentelemetry-rust#1026]
Hi -- I'm wondering if it's possible to surface additional HTTP failures in the OTLP HTTP exporter. I've found that it doesn't report errors based on status code at all, which makes troubleshooting difficult. 

If there's a connection-level issue, there's at least some error handling that will surface associated errors via a console message, but no such luck if, for example, I'm posting to a non-existent endpoint and getting 404s as a consequence.

**Comment by lalitb** [comment]
Not sure if this was on purpose, but the status code error seems to be silently dropped [here](https://github.com/open-telemetry/opentelemetry-rust/blob/ee3efe060581b2c1329e3022a967a4c9117a4ef8/opentelemetry-otlp/src/span.rs#L495). I can take care of this for metrics OTLP HTTP exporter #1020. The change should be trivial for traces too, can pick this after #1020 if it is not already fixed.

**Comment by djc** [comment]
@jaymell sounds like a good idea, please submit a PR!

**Comment by jaymell** [comment]
Actually the link @lalitb shared shows this has already been fixed (in https://github.com/open-telemetry/opentelemetry-rust/pull/945, to be exact). I'm not able to upgrade yet due to some other conflicting dependencies, but this is definitely working in the latest version. Thanks for the attention folks!
