### ISSUE TITLE
SDK/Export concepts leaked into API.

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1042]
https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/common.rs#L426
https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/logs/mod.rs#L27
The above are part of Public API of the OpenTelemetry-API create. Its about "Export" which is an SDK only concept. 
Wondering if this is intentional or accidental? If it is not intentional, we should move them into SDK befoe 1.0 stable.

(There are few other similar issues, will open separate issues to track them)

**Comment by cijothomas** [comment]
See additional comment to be fixed while resolving this issue:https://github.com/open-telemetry/opentelemetry-rust/pull/1750#discussion_r1598799927

**Comment by cijothomas** [comment]
@lalitb Can you address for logs while fixing https://github.com/open-telemetry/opentelemetry-rust/issues/2175 ? error handler is the reason for this issue, so would be good to close them together.

**Comment by lalitb** [comment]
> @lalitb Can you address for logs while fixing https://github.com/open-telemetry/opentelemetry-rust/issues/2175 ? error handler is the reason for this issue, so would be good to close them together.

Yes.
