### ISSUE TITLE
`HistogramAggregator` is using `fetch_set_min` to set the `max`

### ISSUE THREAD

**Issue by nick-mobilecoin** [open-telemetry/opentelemetry-rust#1046]
Looking at https://github.com/open-telemetry/opentelemetry-rust/blob/5842ae2117b8c0b3a805ec1587a64f5cf62f0147/opentelemetry-sdk/src/metrics/aggregators/histogram.rs#L184
It appears that the `max` is being set to the minimum of the values
```rust
                        inner
                            .state
                            .max
                            .fetch_set_min(desc.number_kind(), &other.state.max.load());
```
Is this correct? I would think one would want `fetch_set_max`, but I only skimmed over the code so could be missing the intended functionality.

Looking at the `update()` method the `max` is being set with `fetch_set_max()`, https://github.com/open-telemetry/opentelemetry-rust/blob/5842ae2117b8c0b3a805ec1587a64f5cf62f0147/opentelemetry-sdk/src/metrics/aggregators/histogram.rs#L134
```rust
            inner.state.min.fetch_set_min(kind, number);
            inner.state.max.fetch_set_max(kind, number);
            inner.state.bucket_counts[bucket_id] += 1.0;
```

**Comment by jtescher** [comment]
Resolved in thew new impl in #1156
