### ISSUE TITLE
Separate `Carrier` into `Injector` and `Extractor`

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#105]
See https://github.com/open-telemetry/opentelemetry-specification/pull/578 for spec changes

**Comment by TommyCpp** [comment]
I think we can use something like
```rust
pub trait Carrier{}

impl<T> Carrier for T where T: Injector + Extractor{}
```
which basically make `Carrier` into a marker trait and implement it for every struct that implements `Injector` and `Extractor`

**Comment by jtescher** [comment]
@TommyCpp do you have cases in mind that would prefer to operate on `Carrier`? It seems likely that they exist, but most of the obvious use cases are either client or server libraries that would probably only impl `Injector` or `Extractor`.

**Comment by TommyCpp** [comment]
> @TommyCpp do you have cases in mind that would prefer to operate on `Carrier`? 
 
Hmmm actually not. I guess it make sense to replace `Carrier` with `Injector` and `Extractor`. I'd like to work on this if that's OK
