### ISSUE TITLE
Implement configurable number of cpus for stress testing

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-rust#1055]
for a follow up PR - make the count configurable instead of defaulting to num_cpus. We can use it to measure how good we scale by trying different thread count from 1, 2, ...till num_cpus.

_Originally posted by @cijothomas in https://github.com/open-telemetry/opentelemetry-rust/pull/1045#discussion_r1181795387_

**Comment by cijothomas** [comment]
@ThomsonTan Do you want to help fix this, since you are already in the stress testing area!
