### ISSUE TITLE
Concurrent access Testing

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-rust#1059]
Brought up when discussing https://github.com/open-telemetry/opentelemetry-specification/pull/3475/files

There are a number of requirements like:

> All methods of `MeterProvider` are safe to be called concurrently.

which we should validate.

**Comment by emschwartz** [comment]
Note this issue: https://github.com/open-telemetry/opentelemetry-rust/issues/1070

**Comment by jtescher** [comment]
Resolved in new release #1156
