### ISSUE TITLE
Improve batch span processor

### ISSUE THREAD

**Issue by xlc** [open-telemetry/opentelemetry-rust#1063]
We were getting >2k of `cannot send span to the batch span processor because the channel is full` error in less than a second which could be due to a spike of requests, which isn't that many (not enough to be considered as DoS).

It will be great if we can improve span processor to have better handling this kind of situation. e.g. enter spike handling mode and start aggressively dropping spans to avoid saturate the channel.

Or just expose a callback and I just do this as part of the application logic. Right now the `install_batch` method for datadog doesn't allow any configuration. While it is possible to kind of replicate the logic in application code, it is just a lot of duplicated code that could be avoided if we improve the interface a bit more.

We are using datadog if that makes any difference.

**Comment by Robo210** [comment]
The [`OTEL_BSP_MAX_QUEUE_SIZE`](https://github.com/open-telemetry/opentelemetry-rust/blob/e9adef6873b2cc44e3882eaefe097e8eb7de860c/opentelemetry-sdk/src/trace/span_processor.rs#L59) environment variable might be able to help in the short term, to let you increase the channel size without code changes.

**Comment by cijothomas** [comment]
BatchProcessor has few knobs that can be used to adjust, hopefully they are good enough. 
I will be closing the issue as there is no specific improvement we can track here. Happy to re-open, if there is anything in particular that can be improved for BatchProcessor. (A lot of work is going on in that area right now, so we can address anything additional there.)

https://github.com/open-telemetry/opentelemetry-rust/issues/2066
