### ISSUE TITLE
Use of the `futures` crate as a library dependency

### ISSUE THREAD

**Issue by jplatte** [open-telemetry/opentelemetry-rust#1064]
Hi, I noticed that a bunch of the opentelemetry crates use the `futures` crate as a (non-dev) dependency. I think they should depend on the required `futures-foo` crates instead:

- So only the parts that are actually needed are pulled in
- To improve build pipelining (even if the final app uses all of `futures-*`, more fine-grained dependency specifications allow more crates to be compiled in parallel)

Would a PR to implement this be welcome?

**Comment by jplatte** [comment]
Oh, I just saw that you require a CLA to be signed. I've asked my employer's legal team whether that's acceptable..

**Comment by djc** [comment]
@jplatte any progress with the legal stuff?

@nouzu your comment is unnecessarily negative and not at all constructive. Feel free to make a concrete proposal to replace one of these dependencies you feel are superfluous with something better.

**Comment by jplatte** [comment]
Nope, I've bumped the internal request 🥲

**Comment by nouzu** [comment]
@djc that comment is negative because I feel negative about this project (it's bloated). I don't care enough to contribute, but just enough to post feedback. Feel free to ignore me if you don't care as well.

**Comment by TommyCpp** [comment]
> Nope, I've bumped the internal request 🥲

If it's OK with everyone I can take a stab on this issue over the weekend and we can fix it before the new release

**Comment by jplatte** [comment]
Sorry, were you waiting for a reply from me? I'm definitely fine with somebody else doing the work 😄

**Comment by jplatte** [comment]
By the way, since there is no PR yet I had to go to a [random different PR](https://github.com/open-telemetry/opentelemetry-rust/pull/1035) to start the CCLA signup process, hope this doesn't cause any trouble x)
