### ISSUE TITLE
Concurrency bug in `opentelemetry_sdk` for metrics  0.19.0

### ISSUE THREAD

**Issue by emschwartz** [open-telemetry/opentelemetry-rust#1070]
Hi all, I came across a concurrency bug in how metrics are tracked in 0.19.0.

The problem is that the logic for checking whether a metric with a given set of labels already exists is not atomic. If multiple threads try to start a count for the same label set at the same time, the value may be under-counted. In practice, this probably isn't a huge issue, but I ran into it in testing because the tests are all run around the same time.

You can find the diff for the working vs broken code here: https://github.com/open-telemetry/opentelemetry-rust/compare/main...emschwartz:opentelemetry-rust:fix-concurrency-bug

And you can find a small repro here: https://github.com/emschwartz/otel-concurrency-bug-repro

Note that this bug does not seem to be present in the code on the main branch because it uses the `entry` API on the hashmap. https://github.com/open-telemetry/opentelemetry-rust/blob/e9adef6873b2cc44e3882eaefe097e8eb7de860c/opentelemetry-sdk/src/metrics/internal/sum.rs#L26-L34

That said, I'm not sure what your policy is on patching previous versions.

**Comment by cijothomas** [comment]
As discussed in SIG meeting:
1. We will do hotfix to prior release.
2. Because updaing to newer (when released) is a breaking change, and the main is not yet ready for a release now.

**Comment by emschwartz** [comment]
Just bumping this. Let me know if there's any way I can be helpful

**Comment by garypen** [comment]
We upgraded [our application](https://github.com/apollographql/router) to use otel 0.19.0 and we are having metrics problems (missing metrics in particular). This could be the cause so we are interested in the availability of this hotfix. We'd certainly be happy to test a candidate fix if that's helpful.

**Comment by jtescher** [comment]
Thew new metrics impl in #1156 should resolve this issue.
