### ISSUE TITLE
Ensure that OTLP/JSON exporter uses correct capitalization of field names

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-rust#1079]
We have recently found that the OTLP spec was confusingly written and it was not clear what capitalization to use for trace id, span id fields.

The spec was clarified in this PR: https://github.com/open-telemetry/opentelemetry-proto/pull/468/files (it was considered a bug in the spec and we were allowed to fix it).

**All fields (including traceId and spanId fields) in OTLP/JSON must use camelCase names in exporters.**

I have not verified how the OTLP/JSON exporter behaves in this repository. If the exporter is not already using camelCase name please fix it, if it already is compliant with the spec please close this issue.

Note that Otel Collector currently accepts both camelCase and snake_case field names and will continue to do so for a while to give time for existing users to transition all existing non-compliant data sources to new versions that are OTLP spec-compliant.

**Comment by TommyCpp** [comment]
We haven't supported OTLP/JSON exporter so I think it's not an issue for us. Thanks for the heads up!
