### ISSUE TITLE
Add log-appender for tracing crate

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1080]
Similar to the log-appender for log create, done in this PR (https://github.com/open-telemetry/opentelemetry-rust/pull/1071), this issue is opened to track adding log appender for the tracing crate. 

This issue also summarizes the discussions from the #1071 below:

1. The log-appender for tracing will be initially hosted in this repo.
2. If the maintainers of tracing-opentelemetry agrees, it'll be moved there. It already has tracing subscriber converting tracing into OpenTelemetry Spans/SpanEvents, so it logically makes sense to add the equivalent for Logs as well.
3. If tracing-opentelemetry repo do not agree to host it there, then this will be moved to opentelemetry owned contrib repo (once such a repo is created).
4. 1 is chosen initially because the OpenTelemetry Rust API/SDK that supports logging is not yet released, so hosting here is easy to build the initial version, and unblocks/makes-easy the overall work to support loggin in OTel Rust.

**Comment by jtescher** [comment]
Completed in #1071
