### ISSUE TITLE
Release a new version of opentelemetry-otlp for tonic 0.9

### ISSUE THREAD

**Issue by fbernier** [open-telemetry/opentelemetry-rust#1087]
Hi,

I have some project which I cannot upgrade to tonic 0.9, released two months ago now, because I'm using [with_metadata](https://docs.rs/opentelemetry-otlp/latest/opentelemetry_otlp/struct.TonicExporterBuilder.html#method.with_metadata) which results in an incompatibility (a `MetadataMap` from tonic-0.9.2 and opentelemetry-otlp 0.12 expects tonic-0.9.3)

The upgrade to tonic 0.9 in opentelemetry-otlp was merged in a while ago but all that's missing is a release. Is this planned anytime soon?

Thanks!

<img width="909" alt="image" src="https://github.com/open-telemetry/opentelemetry-rust/assets/147585/b14fb15a-22b9-4aa4-a3f7-89dbb867d771">

**Comment by TommyCpp** [comment]
Will continue the release discussion in #1100 feel free to follow up there
