### ISSUE TITLE
Tracer::Clone is at least 30% of the cost of Tracer::start, because of InstrumentationLibrary

### ISSUE THREAD

**Issue by shaun-cox** [open-telemetry/opentelemetry-rust#1092]
Here's a flame graph of starting portion of a span from the sdk's `trace` benchmark.
![image](https://github.com/open-telemetry/opentelemetry-rust/assets/30703437/559f42c8-247f-4f71-a24e-0c3791d90c89)

Cloning a [`Tracer`](https://github.com/open-telemetry/opentelemetry-rust/blob/b25394552f3bc2267b236397d2fa08b203d3c1b9/opentelemetry-sdk/src/trace/tracer.rs#L29) needs to be cheap, because we do it when creating new spans.

```rust
/// `Tracer` implementation to create and manage spans
#[derive(Clone)]
pub struct Tracer {
    instrumentation_lib: InstrumentationLibrary,
    provider: Weak<TracerProviderInner>,
}
```

But, [`InstrumentationLibrary`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-api/src/common.rs#L441) contains 3 `Cow<'static, str>` instances and a `Vec<KeyValue>` for a total of 120 bytes per instance.  All of that needs to get copied when Cloning one.

I think we need to focus on the design of the `InstrumentationLibrary` type, as it's in the api. To me, it feels like it is (or should be) immutable and needs to be cheaply cloneable, so my first thought was it should resemble something like an `Arc` wrapping an inner struct of 3 `static string slices and the optional vector of attributes.

I'm willing to contribute at PR to change this but want to coordinate and get consensus before choosing an implementation path that might ultimately get rejected after putting in a bunch of work.

My first question is about the seeming preference for `Cow<'static, str>` rather than, say `Arc<str>` for representing things like library name, version, and schema url, knowing that they are all fundamentally immutable.  IOW, I'm confused for what scenario would ever want to mutate these, and hence need the "copy on write" functionality?

**Comment by lalitb** [comment]
> I'm willing to contribute at PR to change this but want to coordinate and get consensus before choosing an implementation path that might ultimately get rejected after putting in a bunch of work.

I would vote for this, I did notice this while reviewing logging SDK (https://github.com/open-telemetry/opentelemetry-rust/pull/788#discussion_r1177128162), and find it unnecessary to clone InstrumentationLibrary and Resource for each log getting exported. Though final say would be for approvers/maintainers :)

**Comment by cijothomas** [comment]
I think similar optimization can be done for Resource too?

**Comment by shaun-cox** [comment]
> I think similar optimization can be done for Resource too?

For sure. I'm working on a change to make `schema_url` a `Option<Arc<str>>` rather than `Option<Cow<'static, str>>`, but honestly i wonder if it could not just be a literal (`'static str`)

**Comment by TommyCpp** [comment]
> but honestly i wonder if it could not just be a literal ('static str)

It used to be a literal but we received feedback that some use case populate the value during runtime. (See https://github.com/open-telemetry/opentelemetry-rust/issues/666)
