### ISSUE TITLE
Update OTLP to 0.20.0

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-rust#1097]
OTLP 0.20.0 was released: https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.20.0

It is also the release candidate for upcoming 1.0.0.

Please update the OTLP exporter to use OTLP 0.20.0.

**Comment by tigrannajaryan** [comment]
@open-telemetry/rust-maintainers have you had a chance to look at this?

**Comment by tigrannajaryan** [comment]
The TC has discussed OTLP 1.0.0 release today and decided that we have enough feedback to go ahead with the release.

If you believe we should delay the release please speak up here: https://github.com/open-telemetry/opentelemetry-proto/issues/456

If I don't hear any objections I am going to hit the release button tomorrow.

**Comment by TommyCpp** [comment]
> @open-telemetry/rust-maintainers have you had a chance to look at this?

Hi sorry for the late response. I took a look at it and didn't see any major blockers/issues. Also since we are still pre 1.0 in worst case we can still add breaking changes.
