### ISSUE TITLE
Remove Dynatrace Exporter

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1099]
https://github.com/open-telemetry/opentelemetry-rust/pull/1094#discussion_r1222297839

I believe this is not required at all to export to Dynatrace. If this is required, there should be an owner.

**Comment by cijothomas** [comment]
https://crates.io/crates/opentelemetry-dynatrace shows just 226 downloads.

**Comment by mviitane** [comment]
In Dynatrace, we’re about to deprecate this exporter in favor of the OTLP exporter. We planned to mark this exporter deprecated still in this month and remove the exporter 6 months later. This will be aligned with other language exporters as well. So, please don’t remove this exporter just yet.

**Comment by dyladan** [comment]
> I believe this is not required at all to export to Dynatrace. If this is required, there should be an owner.

It is not required. We actually encourage/prefer users to use OTLP rather than exporting to the metrics API.

> In Dynatrace, we’re about to deprecate this exporter in favor of the OTLP exporter.

We actually don't maintain this exporter. This statement is generally true of the exporters we do maintain though. Assuming there is a working rust protobuf/http exporter I would recommend you deprecate this in favor of that.

**Comment by hdost** [comment]
So perhaps we can:
1. mark the crate as deprecated. 
2. Do some release soonish?
3. Remove for next version of OTel

**Comment by cijothomas** [comment]
Is it okay for us to remove the exporter from this repo now?

**Comment by arminru** [comment]
@cijothomas Yes, I think with the deprecation notice that was added a few months ago it should be sufficiently clear.

Will only the code and package be removed while the subfolder and README stays there, or will it all vanish?

Maybe you could recite the deprecation notice in the release notes for the release where the exporter will be removed:

> **Warning**
> This exporter is deprecated.
> Dynatrace supports ingesting Traces and Metrics natively via OTLP, and therefore these should be sent directly to Dynatrace via **OTLP protobuf over HTTP** using the built-in [`opentelemetry-otlp`] exporter instead.
> See the [Dynatrace documentation for Rust] and the [Dynatrace documentation for ingesting metrics via OTLP] for details.
[Dynatrace documentation for ingesting metrics via OTLP]: https://www.dynatrace.com/support/help/shortlink/send-metrics-via-otlp-exporter

**Comment by cijothomas** [comment]
> Will only the code and package be removed while the subfolder and README stays there, or will it all vanish?

I am okay with keeping the subfolder and readme (that says deprecated) for sometime.

**Comment by hdost** [comment]
We never pushed anything to the crate about the deprecation https://crates.io/crates/opentelemetry-dynatrace

**Comment by cijothomas** [comment]
> We never pushed anything to the crate about the deprecation https://crates.io/crates/opentelemetry-dynatrace

who can help with that part?

**Comment by hdost** [comment]
@open-telemetry/rust-maintainers can you release dynatrace crate so that there's a deprecation notice and then we can remove it.

**Comment by cijothomas** [comment]
Closed with https://github.com/open-telemetry/opentelemetry-rust/pull/1321
