### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1100]
There were no releases done since the [Metrics SDK was rewritten](https://github.com/open-telemetry/opentelemetry-rust/pull/1000) with new specs, and also since the logging bridge was added.
Opening an issue to request a new release to be done. 

The logging bridge is not quite ready for production use, but that should be okay for release as logs are [opt-in only](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-api/src/lib.rs#L74-L76).
Releasing will make it easy to build the tracing-apppender in the tracing-opentelemetry repo, instead of temporarily doing in this [repo](https://github.com/open-telemetry/opentelemetry-rust/pull/1085).

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/issues/1087 Related issue.

**Comment by hdost** [comment]
Saw this just this afternoon, but I wrote something in our notes this morning 😅 about this exact thing. Possibly we could establish a cadence at some point. We can talk at the next sig I guess?

**Comment by chesedo** [comment]
What's the usual release schedule / timeline?

I would like to try out the new `logs` feature on otlp, But maybe I can tell cargo to pull from git `main` if I can only figure out how to align the versions with tracing :sweat_smile:

**Comment by purkhusid** [comment]
Any chance that a new release could be cut soon? Could really use this fix https://github.com/open-telemetry/opentelemetry-rust/pull/1016 since it's making updates hard.

**Comment by TommyCpp** [comment]
I think currently there are some performance improvement efforts that involve major changes in public APIs. Maybe we should wait until they land before cutting a release?

**Comment by djc** [comment]
> > I think currently there are some performance improvement efforts that involve major changes in public APIs. Maybe we should wait until they land before cutting a release?
> 
> Which PRs?

I think the main one is #1089.

**Comment by Sushisource** [comment]
Any update here? Not being able to upgrade tonic because of this is a bit rough. It'd be really lovely to have a release out to fix that.

**Comment by djc** [comment]
See #1156.

**Comment by HectorMRC** [comment]
Having problems with tonic and `with_metadata` as well. Any ETA for a v0.20.0 release?

**Comment by djc** [comment]
There's no point in asking again and again. You can keep track of #1156 and just wait.

**Comment by jtescher** [comment]
#1156 has been released.
