### ISSUE TITLE
Otel user_events logs exporter

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-rust#1103]
[user_events](https://docs.kernel.org/trace/user_events.html) is Linux solution for user process tracing, similar to [ETW](https://learn.microsoft.com/en-us/windows/win32/etw/about-event-tracing) (Event Tracing for Windows) on Windows. It builds on top of the Linux Tracepoints, and so allows user processes to create events and trace data that can be viewed via existing tools like ftrace and perf.

This kernel feature is supported starting Linux kernel 5.18 onwards, and it enables
 - A faster path for tracing from user mode application by utilizing kernel mode memory address space. 
 - User processes can now export telemetry events only when it is useful i.e, when the registered set of tracepoint events are enabled in kernel.

 The user_events exporter will enable applications to use OpenTelemetry API to capture the telemetry events, and write to user_events subsystem. From user_events, the events can be
  - Captured by the agents running locally, and listening for specific events within user_events subsystem.
  - Or monitored in real-time using local Linux tool like [perf](https://perf.wiki.kernel.org/index.php/Main_Page) or ftrace.

The exporter could be useful for 
 - system applications
 - applications with strict performance requirements.

These type of applications are typically written in C/C++ and Rust.

OpenTelemetry C++ already provides user_events exporter in the contrib repo - https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/exporters/user_events. For Rust, this can be initially added to main repo, and later moved once contrib repo is available.

Reference:
[user_events](https://docs.kernel.org/trace/user_events.html) - User-based Event Tracing
[Example](https://github.com/torvalds/linux/tree/master/samples/user_events) - Basic example from Linux kernel repo
[eventheader_dynamic](https://crates.io/crates/eventheader_dynamic) - Rust crate to write to user_events:

``
eventheader_dynamic provides a mid-level API for generating runtime-specified events using the EventHeader convention. The events are written using the user_events system. This is intended for use as an implementation layer for a higher-level API like OpenTelemetry.
``

**Comment by jtescher** [comment]
Released in #1156
