### ISSUE TITLE
Update semantic conventions to 1.22

### ISSUE THREAD

**Issue by mladedav** [open-telemetry/opentelemetry-rust#1108]
This project's semantic conventions crate [defines](https://docs.rs/opentelemetry-semantic-conventions/latest/src/opentelemetry_semantic_conventions/trace.rs.html#650) `http.status_code` while [semantic conventions](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/#common-attributes) seem to define `http.response.status_code`.

The crate currently uses [semantic conventions 1.20](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.20.0/specification/trace/semantic_conventions/http.md) or older. List of changes between 1.20 and later is in [this issue](https://github.com/open-telemetry/semantic-conventions/issues/43#issuecomment-1558948215).

**Comment by michaeljohnalbers** [comment]
I took a look at this and found a few things

1. The semantic conventions used to generate the constants have been moved into their own [repo](https://github.com/open-telemetry/semantic-conventions). This happened as part of the [1.21 release](https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.21.0) of the specification repo.
1. The new semantic conventions repo does not have any tags/releases/etc. (as of this writing) to which the [generation script](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-semantic-conventions/scripts/generate-consts-from-spec.sh#L8) can refer. And currently, according to the README, it only matches the 1.21 spec. 
1. There is a new version of the Docker `otel/semconvgen` Docker image the script uses. That should be updated as well.
