### ISSUE TITLE
Performance: send resource data to span processors once, not for every span when it ends

### ISSUE THREAD

**Issue by shaun-cox** [open-telemetry/opentelemetry-rust#1124]
[`sdk::trace::Span::ensure_ended_and_exported`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/trace/span.rs#LL192C20-L192C56) clones the provider's config resource for every span processor and every span before sending it to the span processor.

But since the resource is unique to the provider which owns all the span processors, this data could be sent ahead of time, just once, to each span processor.

Not only would this reduce CPU consumption by not cloning, but it will also reduce the size of each message sent through a span processor channel by about 64 bytes (estimated) which will save CPU all by itself.

(I can work on a PR for this but wanted to hear of any objections here before starting that work.)

**Comment by cijothomas** [comment]
+1
The same idea could be used in other signals as well (logs, metrics).

**Comment by lalitb** [comment]
I may be missing something basic here, but can't we have [build_export_data](https://github.com/open-telemetry/opentelemetry-rust/blob/320957751e688ca8a27f60a0c51f46f1c3fb08b8/opentelemetry-sdk/src/trace/span.rs#L218) take reference to the Resource object, just like it does for Tracer  ? Probably I am thinking C++ way, and rust lifetime scoping makes it difficult to pass reference here :)

**Comment by djc** [comment]
By "sent", do you mean it would just be passed at initialization? Or do we need some other (more clever) path to pass it?

Anyway, this sounds like it could make a lot of sense.

**Comment by shaun-cox** [comment]
> By "sent", do you mean it would just be passed at initialization?

At provider initialization, yes, but not technically at span processor initialization, as that happens while [`sdk::trace::provider::Builder`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/trace/provider.rs#L156-L218) is accumulating span processors.  Once `build` is invoked to create the `TraceProvider`, we'd have to invoke a new method on `SpanProcessor` to pass the configuration's `Resource`. The `SpanProcessor` implementations will then "send" it to their exporter counter-part on the receive end of the channel separating processor from exporter.

(Hope that makes more sense. In hindsight, the title of this issue should have said "send resource data to exporter once", or "send resource data through span processor to exporter".)

**Comment by shaun-cox** [comment]
First, I'm going to use the following to disambiguate *exported* `SpanData` from *core* `SpanData`:
- [`ExportedSpanData`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/export/trace.rs#L67-L94)
- [`SpanData`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/trace/span.rs#L28-L47)

Today we have this [trait](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/trace/span_processor.rs#L79-L93):
```rust
pub trait SpanProcessor {
    ...
    fn on_end(&self, span: ExportedSpanData);
    ...
```
There are two issues with this interface:
1. it requires the full exported span data be built in the first place, when it's the processor's job to decide if it should be exported at all.
2. even if the processor decides it should be exported, the means to do so more efficiently are removed.

I suspect a better interface might be something like:
```rust
pub trait SpanProcessor {
    ...
    fn on_end(&self, ctx: &SpanContext, data: &SpanData, lib_id: LibId);

    fn set_resource(&self, resource: Resource);
    fn set_libraray(&self, id: LibId, library: InstrumentationLibrary);
    ...
```
Now `on_end` takes borrowed references to immutable data (or scalar primitives), not large, owned data, and the processor can send much smaller messages to the exporter for each span it decides to export.  It's now pushed down to the exporter to marry up the context and core span data with the fixed resource (and InstrumentationLibrary) attributes in the export thread.

> I guess I don't really understand why we separate the processor and the exporter anyway.

It's to be able to do batch processing (in the exporter) and provide the instrumented code a bit of insulation from however the sdk is configured (or not) to "deal with" (i.e. process and export) spans.  The processor(s) are, if configured, dynamically dispatched to *on the thread of whatever is being instrumented*.  Their job is chiefly to make an export decision and ideally not have the instrumented code feel the cost of exporting directly... this practically means they are going to send their decision over a channel to the exporter to deal with the heavy lifting on its own thread.

**Comment by djc** [comment]
> It's to be able to do batch processing (in the exporter) and provide the instrumented code a bit of insulation from however the sdk is configured (or not) to "deal with" (i.e. process and export) spans. The processor(s) are, if configured, dynamically dispatched to _on the thread of whatever is being instrumented_. Their job is chiefly to make an export decision and ideally not have the instrumented code feel the cost of exporting directly... this practically means they are going to send their decision over a channel to the exporter to deal with the heavy lifting on its own thread.

Ah, right, so the processor is sort of "synchronous" with respect to user code, while the exporter is "asynchronous". So when using tracing-opentelemetry, is there still a processor being invoked like this by the tracing code code?

**Comment by shaun-cox** [comment]
> Ah, right, so the processor is sort of "synchronous" with respect to user code, while the exporter is "asynchronous".

Exactly.

> So when using tracing-opentelemetry, is there still a processor being invoked like this by the tracing code code?

Yes. Depending how you've configured your otel pipeline, you likely have at least one processor active (Simple or Batched). `tracing-opentelemetry` basically installs another `tracing` `Layer` and accumulates into an otel `SpanBuilder` while their span is active.  [When their (i.e. `tracing` crate) span is closed, our builder is used to start and export our span](https://github.com/tokio-rs/tracing-opentelemetry/blob/v0.1.x/src/layer.rs#L926-L928).  (So, unfortunately, it's their cost plus our cost, I've learned. So any optimizations we make here, will improve the use cases of `tracing-opentelemetry` too.)

**Comment by cijothomas** [comment]
> Ah, right, so the processor is sort of "synchronous" with respect to user code, while the exporter is "asynchronous".
> 
> Exactly.

Just to add that the above is true majority of the time. (when using any of the exporters from OTel spec like OTLP, Zipkin etc.). There are exporters to OS_native tracing systems, like https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-user-events-logs/src/logs/reentrant_logprocessor.rs, where exporter and processors are synchronous with respect to user code!

**Comment by TommyCpp** [comment]
Yeah, I agree we shouldn't transfer `Resource` as owned value in SpanProcessor. 

But I don't think `SpanProcessor` needs `set_resource` function. Since the `Resource` is used to identify the entity that emits the telemetry. It should only store in `TracerProvider`. Thus, we can just have a reference from `SpanData` to `TracerProvider` and `Tracer` that allow the exporter downstream to access `Resource` and `InstrumentationLibrary` information
