### ISSUE TITLE
Request for 0.19.1 -- wasm32/js_sys patch

### ISSUE THREAD

**Issue by computermouth** [open-telemetry/opentelemetry-rust#1131]
I encountered the bug fixed with this patch. I'm getting `opentelemetry_api` pulled in via `tracing-opentelemetry`. Currently trying to see if I can `patch` a dependency of a dependency, figured I might as well ask if I could get a bugfix release :pray: 

https://github.com/open-telemetry/opentelemetry-rust/issues/1005

**Comment by jtescher** [comment]
Released in #1156
