### ISSUE TITLE
Add api::context::propagation::Carrier implementation for http::header::HeaderMap

### ISSUE THREAD

**Issue by swilcox3** [open-telemetry/opentelemetry-rust#114]
Hey, I'm loving the direction this is going, I think it's really going to help me with my microservices backend written in [tonic](https://docs.rs/tonic/0.2.1/tonic/).  I've already got my individual services reporting to Jaeger, now I'm trying to get context propagation working.  `tonic` exposes a `trace_fn` that gives you a `http::header::HeaderMap`.  I'm trying to use a `B3Propagator` to extract the context from the `HeaderMap`, but `Carrier` is only implemented for `HashMap` with `&'static str` as the key.  
Could you make an implementation of `Carrier` for `http::header::HeaderMap` please?  Because of Rust's rules around implementations, I can't make an implementation of a foreign trait on a foreign type.  
Also in general, it seems like `Carrier` shouldn't be using `&'static str`, but should instead just be using `&str`.  I can take a stab at a pull request if you like.

**Comment by jtescher** [comment]
Hey @swilcox3, moving to `&str` sounds like a good improvement. A PR there would be appreciated! Also you can see https://github.com/open-telemetry/opentelemetry-rust/tree/master/examples/grpc for a working example of the (currently sub-optimal) tonic usage.

I think adding an impl for `http::header::HeaderMap` would be good as well, maybe behind a `http` feature flag?

**Comment by swilcox3** [comment]
Oh I didn't see that example.  You're right, it does the job, but there's
definitely some boilerplate.  I'll take a look at putting a PR together, it
shouldn't be too complicated.

**Comment by jtescher** [comment]
Resolved in #115
