### ISSUE TITLE
feature to disable span logs on jaeger exporter

### ISSUE THREAD

**Issue by FarhadF** [open-telemetry/opentelemetry-rust#1160]
Currently jaeger exporter always sends all event fields to jaeger as span log events.

Example:
```
info!(foo = 1, "in handler")
```
and in jaeger:
![image](https://github.com/open-telemetry/opentelemetry-rust/assets/17374492/cc11a280-4576-4ff5-bab8-d22b8160020a)

Depending on the scenario user might need to disable sending logs alongside spans to jaeger:

-  Costs
- Performance
- Having already robust logging infrastructure in place
- ...

It would be nice to have the feature to disable sending event fields as span logs to jaeger.

**Comment by jtescher** [comment]
Best to move this issue to https://github.com/tokio-rs/tracing-opentelemetry/ as the configuration option would be on the subscriber provided there currently.

**Comment by FarhadF** [comment]
thanks for quick response, afaik the issue is in this function in this repo:

```
/// Convert spans to jaeger thrift span for exporting.
fn convert_otel_span_into_jaeger_span(
    span: trace::SpanData,
    export_instrument_lib: bool,
) -> jaeger::Span {
    let trace_id_bytes = span.span_context.trace_id().to_bytes();
    let (high, low) = trace_id_bytes.split_at(8);
    let trace_id_high = i64::from_be_bytes(high.try_into().unwrap());
    let trace_id_low = i64::from_be_bytes(low.try_into().unwrap());
    jaeger::Span {
        trace_id_low,
        trace_id_high,
        span_id: i64::from_be_bytes(span.span_context.span_id().to_bytes()),
        parent_span_id: i64::from_be_bytes(span.parent_span_id.to_bytes()),
        operation_name: span.name.into_owned(),
        references: links_to_references(span.links),
        flags: span.span_context.trace_flags().to_u8() as i32,
        start_time: span
            .start_time
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap_or_else(|_| Duration::from_secs(0))
            .as_micros() as i64,
        duration: span
            .end_time
            .duration_since(span.start_time)
            .unwrap_or_else(|_| Duration::from_secs(0))
            .as_micros() as i64,
        tags: Some(build_span_tags(
            span.attributes,
            if export_instrument_lib {
                Some(span.instrumentation_lib)
            } else {
                None
            },
            span.status,
            span.span_kind,
        )),
        logs: events_to_logs(span.events),
    }
}```

on the last line you see all the events are being converted to logs as a part of span with no configuration options.

**Comment by jtescher** [comment]
That part is required by this section of the spec https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#events. But what you are generating with the tracing `info` macro happens upstream of that in https://github.com/tokio-rs/tracing-opentelemetry/blob/v0.1.x/src/layer.rs#L811.

In `tracing`, the event can produce either span events or logs, or potentially both. In otel the behavior is more strictly defined as logs and traces are separate signals. As such the configuration of where to send would either be in the tracing-opentelemetry repo or in the unreleased work in https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-appender-tracing in the future.

**Comment by FarhadF** [comment]
makes sense, thank you.
