### ISSUE TITLE
Any schedule for when stackdriver will get a release issued on crates.io?

### ISSUE THREAD

**Issue by msdrigg** [open-telemetry/opentelemetry-rust#1166]
Background: I got here because I keep seeing traces with this weird behavior (missing root span) appear in my google cloud tracing when I first started using `opentelemetry-stackdriver` crate to export traces to google cloud. 

<img width="320" alt="Screenshot 2023-07-25 at 5 26 45 PM" src="https://github.com/open-telemetry/opentelemetry-rust/assets/45189381/5ef16975-d8a9-417e-88fd-074c8ff3358a">

After researching this issue, I am seeing that this appears to be fixed by #1127 a few weeks ago https://github.com/open-telemetry/opentelemetry-rust/blob/ccb510fbd6fdef9694e3b751fd01dbe33c7345c0/opentelemetry-stackdriver/src/lib.rs#L329-L334

Any word on when we will get a `opentelemetry-stackdriver` release

**Comment by djc** [comment]
See #1156.
