### ISSUE TITLE
Trace id not exported correctly on links when using jaeger

### ISSUE THREAD

**Issue by bodymindarts** [open-telemetry/opentelemetry-rust#118]
Jaeger exporter serialises the trace id in 2 64bit chunks. Unfortunately when exporting links the high and low chunks are in reverse order so downstream systems receiving the events cannot construct correct links to the correlated traces.

https://github.com/open-telemetry/opentelemetry-rust/pull/117 fixes this.

**Comment by jtescher** [comment]
Resolved in #117
