### ISSUE TITLE
Can Stdout exporter write timestamp in human readable format?

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1191]
Given stdout exporters are meant for human consumption (learning purposes, not production use), I think the timestamps should be written in human readable format as opposed to ticks_since_epoch (eg: https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-stdout/src/metrics/transform.rs#L274).

I can send a short PR to make this happen for one signal, and if no objections, apply to all signals.

**Comment by jtescher** [comment]
Resolved in #1192
