### ISSUE TITLE
Sending a gauge via otlp to datadog

### ISSUE THREAD

**Issue by alexheretic** [open-telemetry/opentelemetry-rust#1200]
I'm currently reviewing sending gauge metrics to datadog via otlp. 

I have some issues using the metrics API:
* My code already publishes reports (of gauges) every interval. The otlp pipeline handles its own publishing though which seems to mean another up to 20s latency penalty (or duplicate publishes if I lower the period). Is there a way to trigger publishing without delay (or blocking)?
* The `register_callback` API seems unergonomic. I have to construct `rate_gauge` each time I call `register_callback` to move it into the callback fn. Is that how it is meant to work?
* When does `register_callback` return an error?
* How do I see if publishes are working? Connection or any other errors etc.
* This makes me wonder if there is a lower level API I can use to send a grpc message for each of my report intervals?

I'd appreciate any pointers!

My initial code looks something like the following:
```rust
let otlp = opentelemetry_otlp::new_pipeline()
    .metrics(opentelemetry_sdk::runtime::Tokio)
    .with_exporter(
        opentelemetry_otlp::new_exporter()
            .tonic()
            .with_endpoint("http://0.0.0.0:4317")
    )
    .with_resource(opentelemetry_sdk::Resource::new([
        opentelemetry_api::KeyValue::new(
            "host",
            opentelemetry_api::Value::String(aws_instance_id.to_string().into()),
        ),
    ]))
    .with_period(Duration::from_secs(20))
    .build()
    .unwrap();

let meter = otlp.meter("alex");

loop {
    tokio::select! {
        // ...
        _ = report_interval.tick() => {
            for (name, count) in &counts {
                let rate = // ...
                let attrs = //...
                let rate_gauge = meter
                    .f64_observable_gauge("foo.rate")
                    .with_unit(opentelemetry_api::metrics::Unit::new("msgs/s"))
                    .init();

                if let Err(err) = meter.register_callback(&[rate_gauge.as_any()], move |ob| {
                    ob.observe_f64(&rate_gauge, rate, &attrs);
                }) {
                    error!("{err}");
                }
            }
```

**Comment by cijothomas** [comment]
> I've found I can use `MetricsServiceClient` from _opentelemetry-proto_ instead to report gauges more directly.

That does not seem like the right usage.

**Comment by alexheretic** [comment]
> That does not seem like the right usage.

Can you elaborate why? The lower level direct method solves my issues and it's still a stable grpc api.

**Comment by cijothomas** [comment]
the proto files defines the wire format for transporting metrics from app to collector/any other otlp endpoints. They are not meant for direct usage as Metric APIs.

The correct usage of ObservableGauge is shown here : https://github.com/open-telemetry/opentelemetry-rust/blob/main/examples/metrics-basic/src/main.rs#L109-L129

The callbacks are automatically invoked every export cycle.

**Comment by alexheretic** [comment]
The otel collector provides a stable grpc API, but it isn't meant to be used? To me it seems pretty reasonable to use it as long as I'm willing to use it correctly. The protos are documented so this doesn't seem too bad.

Are you suggesting the grpc API is unstable and so shouldn't be used except by official wrapper clients? I don't see how that can be the case since the otel collector breaking the grpc API would break any existing running otlp publishers. 

Your linked usage looks the same as my initial code, so I think have the same issues I listed.

I think my use case is just not catered to by the main higher level lib. That's ok! I created this issue to see if I was missing something.

**Comment by cijothomas** [comment]
> The otel collector provides a stable grpc API, but it isn't meant to be used? To me it seems pretty reasonable to use it as long as I'm willing to use it correctly. The protos are documented so this doesn't seem too bad.

Like I said, the otlp is designed for transporting metrics/logs/traces from app to collector, not meant/designed as an end-user callable API. If you understand that and okay with that, I don't think there is anything preventing you from using that.

> Are you suggesting the grpc API is unstable

Not at all! Just that its not meant to be the end-user facing Metric API!

> I think my use case is just not catered to by the main higher level lib. That's ok!

I did not quite understand the use case. Perhaps you could rephrase the issue, and I can try to help.
https://github.com/open-telemetry/opentelemetry-rust/issues/1181 - maybe this is the issue?
