### ISSUE TITLE
opentelemetry_api should not depend on futures_channel

### ISSUE THREAD

**Issue by shaun-cox** [open-telemetry/opentelemetry-rust#1201]
`opentelemetry_api` [depends on](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-rust+futures_channel+path%3A%2F%5Eopentelemetry-api%5C%2Fsrc%5C%2F%2F&type=code) `futures_channel` simply to convert some of its error types into `TraceError` or `LogError`.

I think this was done because `opentelemetry_sdk` [happens to use this channel type](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-rust+futures_channel+path%3A%2F%5Eopentelemetry-sdk%5C%2Fsrc%5C%2F%2F&type=code) in its implementation.

I don't think the API crate should depend on `futures_channel` just for this, and instead would like to move the conversions into the SDK crate instead.

**Comment by djc** [comment]
Makes sense to me.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/issues/1042 similar.
