### ISSUE TITLE
No way to construct LogData

### ISSUE THREAD

**Issue by FSMaxB** [open-telemetry/opentelemetry-rust#1217]
There is currently no way to construct [`LogData`](https://docs.rs/opentelemetry/0.20.0/opentelemetry/sdk/export/logs/struct.LogData.html) directly, but I need it to feed a [`LogExporter`](https://docs.rs/opentelemetry/0.20.0/opentelemetry/sdk/export/logs/trait.LogExporter.html) with.

The issue is that there is no constructor and constructing it directly is prevented by the `#[non_exhaustive]` attribute.

There's a workaround, but it's absolutely less than pretty (the workaround is to create a fake `LogProcessor` and abuse a `LoggerProvider` to construct the `LogData` for us):

```rust
fn log_data(log_record: LogRecord) -> LogData {
    let (log_processor, log_data_receiver) = FakeLogProcesor::new();
    let provider = LoggerProvider::builder()
        .with_config(opentelemetry::sdk::logs::Config { resource: Cow::Owned(resource()) })
        .with_log_processor(log_processor)
        .build();

    let logger = provider.logger("logger name");

    logger.emit(log_record);

    log_data_receiver.recv().unwrap()
}

fn resource() -> Resource {
    Resource::new([KeyValue::new("service.name", "service-name")])
}

#[derive(Debug)]
struct FakeLogProcesor(std::sync::mpsc::Sender<LogData>);

impl FakeLogProcesor {
    pub fn new() -> (Self, std::sync::mpsc::Receiver<LogData>) {
        let (sender, receiver) = std::sync::mpsc::channel();
        (Self(sender), receiver)
    }
}

impl LogProcessor for FakeLogProcesor {
    fn emit(&self, data: LogData) {
        let _ = self.0.send(data);
    }

    fn force_flush(&self) -> LogResult<()> {
        Ok(())
    }

    fn shutdown(&mut self) -> LogResult<()> {
        Ok(())
    }
}
```

**Comment by lalitb** [comment]
Can you elaborate on your use case? The `LogData` is supposed to be constructed only within the SDK, and not part of the user-facing API/SDK.

**Comment by FSMaxB** [comment]
My use case is manually sending out logs and traces and handle errors individually.

I'm building a service that sends logs and traces to our customers, each of which can configure their own endpoints (only OTLP for now). What this means is that I'm multiplexing between customer endpoints and need to explicitly handle errors when sending the data to a customer.

Basically my service exposes a REST API, that is called with a piece of telemetry data and the configuration of the customer endpoint and I need to respond with a success or error HTTP response depending on whether the telemetry data was successfully delivered to that customer.

I can't rely on the regular `Logger` trait for that, because it is a) not asynchronous and b) doesn't provide any error reporting, that's why I'm using the `LogExporter` trait instead, which requires `LogData`.

**Comment by FSMaxB** [comment]
Note that `SpanData`, which I'm also using together with the `SpanExporter` trait, doesn't have the issue because it doesn't have the `#[non_exhaustive]` attribute.

**Comment by lalitb** [comment]
Ok thanks for the details. Feel free to raise a PR to remove the `#[non_exhaustive]` attributes from LogData. Also, need to be aware that the internal structure/implementation can change as Log signal is still not stable.

**Comment by FSMaxB** [comment]
> Ok thanks for the details. Feel free to raise a PR to remove the #[non_exhaustive] attributes from LogData.

Done.

> Also, need to be aware that the internal structure/implementation can change as Log signal is still not stable.

Yeah, that is fine, I can adapt when changes happen.
