### ISSUE TITLE
Why are attributes of type &[KeyValue] for metrics api

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-rust#1228]
The current metrics api takes in `&[KeyValue]` for [attributes](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-api/src/metrics/instruments/counter.rs#L35) on all recording operations. I was curious as to why the api takes in this type instead of some sort of dictionary like what [Python](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-api/src/opentelemetry/util/types.py#L28) is doing. This would probably save on performance implications in terms of duplicate keys and converting for KeyValue to HashKeyValue right?

I also ran cargo flamegraph and noticed that From<&[KeyValue]> takes up a decent amount of time in a regular metrics pipeline for counter.add().

![image](https://github.com/open-telemetry/opentelemetry-rust/assets/11580155/bd19e61f-a1d5-45cb-b2a5-35297392bcff)

**Comment by TommyCpp** [comment]
> What does From do ?

I think it's the [From](https://github.com/open-telemetry/opentelemetry-rust/blob/1688ec682458d04bf6deb445bf61d5052db28c88/opentelemetry-sdk/src/attributes/set.rs#L110) we are looking at. It creates a sorted set

**Comment by cijothomas** [comment]
> > What does From do ?
> 
> I think it's the [From](https://github.com/open-telemetry/opentelemetry-rust/blob/1688ec682458d04bf6deb445bf61d5052db28c88/opentelemetry-sdk/src/attributes/set.rs#L110) we are looking at. It creates a sorted set

Okay that is in the SDK. I was confused as the issue was talking about API :)
That seems to be *the* biggest bottleneck, as it does sorting and hashing. It may not be possible to avoid both, but need to explore more.
(OTel C++ and .NET has found ways to avoid sorting as sorting the attributes was the biggest cost in metrics hot path)

**Comment by lzchen** [comment]
@cijothomas 

> If the API accepts a dictionary, then user is forced to create the dictionary and pass it on, so the perf wont improve.

Not sure what you mean here. The `From` is a large bottle neck to convert from list of KeyValue to a BTreeSet of HashKeyValue. If we pass on the guarantee of no duplicate elements and ordering to the users, we would not have to sort and hash the key values right?

**Comment by cijothomas** [comment]
> no duplicate elements and ordering to the users, we would not have to sort and hash the key values

That is correct. But its just shifting perf intensive job from SDK to user code. The overall result is still the same.
