### ISSUE TITLE
Implement instrument advisory (hint) for Metric API

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1241]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-advisory-parameters New spec. The advisory needs to be exposed on Metric API, and then the SDK must leverage them for aggregation.

**Comment by alfiejfs** [comment]
Hi, is this still planned for the beta release on August 2nd? I see it mentioned in #1719 but I don't see it in the milestone. And is this just a temporary API patch whilst views are removed, or is it intended to stay? Cheers :)

**Comment by cijothomas** [comment]
> Hi, is this still planned for the beta release on August 2nd? I see it mentioned in #1719 but I don't see it in the milestone. And is this just a temporary API patch whilst views are removed, or is it intended to stay? Cheers :)

Yes. (Note we got delay by few weeks).
Will fix milestone, thanks for catching it. It'll be a permanent feature, as it is part of OTel's Stable specification.

**Comment by cijothomas** [comment]
This didn't land for the current release, will be covered in the next release, ~3 weeks from now. @utpilla is working on this.

**Comment by cijothomas** [comment]
Closing as this is covered by 0.26 release for histogram hints.
