### ISSUE TITLE
using package name with underscore intentional?

### ISSUE THREAD

**Issue by LearnShareAlways** [open-telemetry/opentelemetry-rust#1243]
There is news  of malware attack with the help of  package naming with underscore "_"  . I see some opentelemetry packages use underscore like  "opentelemetry_sdk" (see https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/Cargo.toml and  https://crates.io/crates/opentelemetry_sdk). Is this intentional?

**Comment by djc** [comment]
Please provide a reference for the malware attack. Crates with underscores in their names are pretty common and shouldn't normally cause issues as far as I'm aware.

**Comment by LearnShareAlways** [comment]
See https://blog.phylum.io/rust-malware-staged-on-crates-io/

I see  many packages use hyphen and  some use underscore. It is hard to tell what cargo pulls. Since there is no easy way, I am avoiding package name with underscore. Hard to guess by just looking into cargo.toml and not easy to go and check each package in git repo.. Be safe than sorry. I would suggest to stick with one convention and I see hyphen is pretty much standard.

**Comment by LearnShareAlways** [comment]
Like opentelemtry-http, opentelemtry-otlp and many more use hyphen

**Comment by TommyCpp** [comment]
We didn't release sdk and api separately. By the time we split them up we found someone already taken the name `opentelemetry_api` and `opentelemetry_sdk` so there is no way for us to align the connector to hyphen

**Comment by TommyCpp** [comment]
Seems to be duplicate with #1263
