### ISSUE TITLE
OpenTelemetry docs should talk only about instrumenting, and not about sdk or exporters.

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1256]
[OpenTelemetry](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/Cargo.toml#L35-L37) crate has dev-dependencies on the SDK/stdout crates as they are demonstrated in the [docs](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/lib.rs#L25).

Proposing to remove that dependency, and modify the doc to only show the API usage, without showing anything related to SDK/Exporters. We should say something like "For the telemetry to be exported, need to install additional crates and point to them", so users are aware that OpenTelemetry crate alone is just the facade which does nothing in the absence of further setup.

This approach is used in https://docs.rs/tracing/latest/tracing/ docs already - it just talks about the tracing facade there, and [lists the tracing-subscriber/other](https://docs.rs/tracing/latest/tracing/#related-crates) crates that are required for the traces to land somewhere.

Similar change is done in https://github.com/open-telemetry/opentelemetry-rust/pull/1249. There could be more places, but want to get general feedback on this proposal before further cleanups.

**Comment by shaun-cox** [comment]
Yep, I'm favor of this approach too.
