### ISSUE TITLE
resource attributes not present

### ISSUE THREAD

**Issue by casualjim** [open-telemetry/opentelemetry-rust#1261]
I have 2 identical configurations, 1 in golang and 1 in rust.

In golang when I specify attributes in resource I see them appear in zipkin but for the rust version those attributes are missing. From just looking at the code that should not be the case.

Rust config: 

* https://gist.github.com/casualjim/92bfb4943a5d05ef1e9147be05e3570b?ts=4#file-server-rs-L15-L25
* https://gist.github.com/casualjim/92bfb4943a5d05ef1e9147be05e3570b?ts=4#file-server-rs-L46

Golang:

* https://gist.github.com/casualjim/92bfb4943a5d05ef1e9147be05e3570b?ts=4#file-server-go-L134-L143
* https://gist.github.com/casualjim/92bfb4943a5d05ef1e9147be05e3570b?ts=4#file-server-go-L147

**Comment by casualjim** [comment]
It appears that the resource is never added to the attributes in the exporter. Adding

```rust
.chain(
    span_data
        .resource
        .as_ref()
        .iter()
        .map(|(k, v)| KeyValue::new(k.clone(), v.clone())),
)
```

[here](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-zipkin/src/exporter/model/mod.rs#L60) fixes the issue.

I took a look at the codebase and this seems to be a consistent omission, is there a reason for that?

**Comment by cijothomas** [comment]
The spec does not cover what to do with Resource for Zipkin.
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/zipkin.md

In general, Resource should not be automatically added as Span Attributes - some exporters may chose to do that, depending on their backends.

Were you expecting that all Resource attributes are added as Span attributes? If yes, Zipkin exporter could add a feature to do that if use opts-in to such a feature.
(I dont think the Collector's Zipkin Exporter is doing this either..https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/zipkinexporter/factory.go)

**Comment by casualjim** [comment]
They do add them everywhere: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/zipkin/zipkinv2/from_translator.go#L60-L61

**Comment by cijothomas** [comment]
> They do add them everywhere: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/zipkin/zipkinv2/from_translator.go#L60-L61

Got it. (Note that it is not a stable component, and that is not the spec). 

What I said is still true - Resource should not automatically be added as Span attributes by default.

**Comment by hdost** [comment]
It appears a similar conversation is happening in the spec https://github.com/open-telemetry/opentelemetry-specification/issues/1196

**Comment by cijothomas** [comment]
Closing as no changes planned unless the spec changes.
