### ISSUE TITLE
`new_view` should escape name before it is converted to a regex.

### ISSUE THREAD

**Issue by BrynCooke** [open-telemetry/opentelemetry-rust#1262]
When using `new_view` it does a bunch of pre-processing on the name to turn it into a regex.
This includes:
* stripping `^` and `$`
* Replacing `?` with `.`
* Replacing `*` with `.*`

As metrics are likely namespaced with a `.` this means that if you want to create a view that matches a particular prefix you have to game the api by inserting `\\.` in your pattern (we have a_b_* metrics that we want to exclude and `a.b.*` metrics that we want to include due to legacy constraints).

Maybe a dedicated glob library should be used or just stick with regex without the partial globbing support?

**Comment by jtescher** [comment]
I think glob matching could make sense as the spec doesn't call for more than wildcards, do you have time to submit a PR?

**Comment by lalitb** [comment]
@BrynCooke do you plan to work on it, or else I can pick it as it will help us unblock CI - https://github.com/open-telemetry/opentelemetry-rust/pull/1294#issuecomment-1761734757

**Comment by lalitb** [comment]
#1301 fixes it.
