### ISSUE TITLE
Move Metric API validations to SDK.

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1264]
In the current implementation, Metrics API (i.e part of OpenTelemetry crate) is [enforcing ](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/metrics/instruments/mod.rs#L103-L115) the various instrument name limitations. 

Proposing to move them to the SDK instead. Spec also [recommends that the validations be done in the API implementations, i.e SDKs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#synchronous-instrument-api).

**Comment by cijothomas** [comment]
> May I try to work on this issue ?

Sure! Depending on your experience, https://github.com/open-telemetry/opentelemetry-rust/issues/1265 could be tackled first (as it is straightforward), and then move to this issue or you can do this one directly.

**Comment by TommyCpp** [comment]
Close with #1269
