### ISSUE TITLE
Allow use of "/" in Metrics Instrument Names, and with a 255 char limit

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-rust#1265]
As per the recent specs change : 
 - Increase max instrument name length from 63 to 255: https://github.com/open-telemetry/opentelemetry-specification/pull/3648
 - Instrument names can have "/" character : https://github.com/open-telemetry/opentelemetry-specification/pull/3684

**Comment by cijothomas** [comment]
Club it here https://github.com/open-telemetry/opentelemetry-rust/issues/1264 or do separate to quickly get this out?

**Comment by lalitb** [comment]
Either is fine, as long as we can track these two specs changes :)

**Comment by cijothomas** [comment]
Straightforward, so tagging with "good first issue", to see if anyone wants to try.
