### ISSUE TITLE
End to end example of trace propagation

### ISSUE THREAD

**Issue by danielgerlag** [open-telemetry/opentelemetry-rust#1276]
Is there any end to end example of taking an upstream trace, adding to it and then calling a downstream service with a new traceparent?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/tree/main/examples/tracing-http-propagator Could you see if this is what you are looking for? We can enhance it to cover gaps, if any.

**Comment by cijothomas** [comment]
Closing old issues without activity. Feel free to reopen if there are further questions, and we can help.
