### ISSUE TITLE
Jaeger collector default endpoint looks incorrect

### ISSUE THREAD

**Issue by BrynCooke** [open-telemetry/opentelemetry-rust#1280]
According to the Jaeger docs port 14250 is for use with the proto format sent from jaeger agent:

14268 | HTTP | collector | accept jaeger.thrift directly from clients
14250 | HTTP | collector | accept model.proto

However the collector code uses thrift to export. https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-jaeger/src/exporter/collector.rs#L63

It feels like the [default endpoint](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-jaeger/src/exporter/config/collector/mod.rs#L35) should be using port 14268

**Comment by cijothomas** [comment]
Considering we are going to remove jaeger exporter https://github.com/open-telemetry/opentelemetry-rust/issues/995, closing the issue. Please use OTLP Exporter as Jaeger natively support this.
