### ISSUE TITLE
Publish a new release of opentelemetry-datadog

### ISSUE THREAD

**Issue by mightyguava** [open-telemetry/opentelemetry-rust#1291]
Could you publish a new release of the datadog crate? I'd really like to be able to get this fix I made 2 months ago https://github.com/open-telemetry/opentelemetry-rust/pull/1185. Thanks!

**Comment by mightyguava** [comment]
cc: @jtescher

**Comment by hdost** [comment]
Release is coming https://github.com/open-telemetry/opentelemetry-rust/pull/1343
