### ISSUE TITLE
Should opentelemetry-stdout conform to a strict serialization format?

### ISSUE THREAD

**Issue by erichulburd** [open-telemetry/opentelemetry-rust#1296]
Currently, `opentelemetry-stdout` writes data in a Rust SDK-specific format: https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-stdout/src/trace/transform.rs#L57 . Note, these structs do not implement `Deserialize`. This makes it hard to do anything with the data.

I'm currently using opentelemetry-stdout for making assertions on trace data exported from Rust. I propose `opentelemetry-stdout` write data in OTLP messages in JSON. This makes the data written to stdout machine readable - even across languages (which is especially relevant to work enabling tracing across Python-Rust FFI: https://github.com/rigetti/pyo3-opentelemetry/pull/3).

The snag I hit is that the trace and span ids written to stdout (or file) are not properly encoded to the OTel + Proto spec. Specifically, according to the Proto language specification, `bytes` fields within JSON should be encoded as:

>  a string using standard base64 encoding with paddings. Either standard or URL-safe base64 encoding with/without paddings are accepted.

See https://protobuf.dev/programming-guides/proto3/#json

_My reading of with / without paddings are the trailing "="._

Trace id and span id are encoded as hex in this library: https://github.com/open-telemetry/opentelemetry-rust/blob/6713143b59659dc509b7815404ebb57ad41cfe3a/opentelemetry-stdout/src/trace/transform.rs#L96

This isn't an issue for _every value_ , but there are some pathological examples where this produces invalid base64:

* trace id: 15769111199087022768103192234192075546
* encoded as: "bdd05355c559cbb7c36ee676b58fb1a"
* this should be "0bdd05355c559cbb7c36ee676b58fb1a"

**Comment by cijothomas** [comment]
stdout exporter is not meant for machine readable. [Its just for humans to read, and learn how things would work.](https://github.com/open-telemetry/opentelemetry-rust/pull/1192#issuecomment-1669994637). I was planning to add some warnings about this on the doc, but just haven't got to it yet.

I would not recommend betting on stdout format for any automation testing. Instead, rely on InMemoryExporter for ensuring the apps are correctly instrumented with Otel. 
If you want to validate by using external process, then it may be better off setting up a OTLPEndpoint and validate the data comes in the expected format. OTLP output will be guaranteed to be stable.

**Comment by jtescher** [comment]
Agree with @cijothomas that the in-memory version is likely easier to work with for your case. But the output should also be consistent with the spec so I've opened a PR to address any inconsistencies that the codebase has internally as well.

**Comment by erichulburd** [comment]
I was not aware of the `InMemoryExporter` (I wish I had before I implemented an in memory gRPC service for a bunch of my Rust tests!).

This comment suggests https://github.com/open-telemetry/opentelemetry-rust/pull/1192#issuecomment-1669994637:

> Make a OTLP Exporter (new one, or enhance existing ones), which can send data to file or stdout, following the linked specs. This may be used in Production and the output shape follows the spec and is predictable.

That is _exactly_ what I am looking for. Is it implemented (I [assume not](https://github.com/open-telemetry/opentelemetry-rust/tree/5eaaf530538f7de18dbdcfac3d81f6a4df7f952d/opentelemetry-otlp/src/exporter) and if not, is there an open issue for it?

**Comment by cijothomas** [comment]
No, there is no OTLP file exporter implemented.
Have you tried using in-memory exporter for your tests?

**Comment by cijothomas** [comment]
Closing old issues. Feel free to reopen or open a new one if there are clarifications required.
As of today, there are no plans to make opentelemetry-stdout stick with any predictable format.

**Comment by erichulburd** [comment]
@cijothomas (and any future passersby) I've ended up just manually implementing an `OtelOtlpFile as SpanExporter`: https://github.com/rigetti/pyo3-opentelemetry/blob/e84b8b3dca464169e04db2e26221ceb94e98f9f4/crates/tracing-subscriber/src/layers/otel_otlp_file.rs#L71

**Comment by cijothomas** [comment]
If you have the bandwidth, you may contribute it to the repo. Now there is an official spec for it as well: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/file-exporter.md
