### ISSUE TITLE
error trying to connect: invalid URL, scheme is not http

### ISSUE THREAD

**Issue by williamlsh** [open-telemetry/opentelemetry-rust#1302]
As described in this discussion: https://github.com/open-telemetry/opentelemetry-rust/discussions/1198

**Comment by chinmoyrp** [comment]
If you are using reqwest-client to connect to a https url, then add reqwest-rustls feature to opentelemetry-oltp. That fixed it for me.

**Comment by williamlsh** [comment]
> If you are using reqwest-client to connect to a https url, then add reqwest-rustls feature to opentelemetry-oltp. That fixed it for me.

Indeed, that solves the problem.
