### ISSUE TITLE
What's the purpose of ManualReader? Are there examples of it being used in a synchronous context?

### ISSUE THREAD

**Issue by 3tilley** [open-telemetry/opentelemetry-rust#1329]
I've looked through the documentation and can't see where someone would use `ManualReader` - all the examples use `PeriodicReader`. My assumption is that it exists to allow someone to write their own `MeterProvider`, but is there any way of using it with `MeterProvider::builder` to collect metrics on demand? The only place I can see it used is inside the prometheus exporter.

I was hoping to use it to create a simple example showing how to collect metrics in a synchronous manner, by running some instrumented functions, and then printing out the collected metrics at the end.

I'm happy to contribute that example and update the docs!

**Comment by cijothomas** [comment]
> I was hoping to use it to create a simple example showing how to collect metrics in a synchronous manner, by running some instrumented functions, and then printing out the collected metrics at the end.

You dont need manualreader for that. PeriodicReader would just work fine - just need to do ForceFlush() if you want to see without waiting for the timeinterval

**Comment by 3tilley** [comment]
Thanks! Is there a way to have it run without Tokio? I'm aware that most of the time people will be operating in async contexts, but I'd be interested to see a demo without. I tried `TokioCurrentThread` but that still needs a Tokio runtime.

**Comment by cijothomas** [comment]
You need a runtime surely today  - Tokio,TokioCurrentThread, async-std are supported : https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/runtime.rs

Let us know if this helps. If you have the bandwidth, we could use some doc updates to make these requirements more clear.

**Comment by 3tilley** [comment]
Thanks, I'm happy to help out with that! Specifically, is there any practical reason for me to use single thread tokio if I'm using out of the box meters (that presumably are configured to run well in asynchronously). If you're in a low-resource / embedded environment, will Tokio multi-threaded cause issue? I'm guessing you just tune your `tokio::main` to suit, and the periodic exporter grabs that?

**Comment by cijothomas** [comment]
I have very limited knowledge about async runtimes, so can't really offer any insights/help with that ! Hopefully there are others who can help with this part.

**Comment by ymgyt** [comment]
ManualReader is used in [the test on metrics](https://github.com/tokio-rs/tracing-opentelemetry/blob/70f3ed6f73a342d4119681794b28037b1fdfdf98/tests/metrics_publishing.rs#L397) in [tracing-opentelemetry](https://github.com/tokio-rs/tracing-opentelemetry)

**Comment by cijothomas** [comment]
> ManualReader is used in [the test on metrics](https://github.com/tokio-rs/tracing-opentelemetry/blob/70f3ed6f73a342d4119681794b28037b1fdfdf98/tests/metrics_publishing.rs#L397) in [tracing-opentelemetry](https://github.com/tokio-rs/tracing-opentelemetry)

It can leverage InMemoryExporter as well.

**Comment by jtescher** [comment]
Closing this as the answer has been provided.
