### ISSUE TITLE
`with_channel` for custom transports

### ISSUE THREAD

**Issue by kjvalencik** [open-telemetry/opentelemetry-rust#1333]
[This PR](https://github.com/open-telemetry/opentelemetry-rust/pull/1187) removed support for [`with_channel`](https://docs.rs/opentelemetry-otlp/0.13.0/opentelemetry_otlp/struct.TonicExporterBuilder.html#method.with_channel) which is useful for custom transports (e.g., unix domain sockets). (Original issue: https://github.com/open-telemetry/opentelemetry-rust/pull/515)

The setter and field still exist, but they are unused. Was this removal intentional or a small oversight in the refactoring?

Ideally, `with_channel` would also work for metrics--this was never implemented. Would you be open to a PR adding this feature back?

Thanks!

**Comment by rbtcollins** [comment]
Can we get a backport of this to 0.14 of opentelemetry-otlp ?  I'm happy to supply one, but its not clear what the protocol is for that, as there is no branch for 0.14...
