### ISSUE TITLE
OTLP gRPC exporter doesn't support `OTEL_EXPORTER_OTLP_HEADERS` but OTLP/HTTP supports it.

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-rust#1336]
The kv pairs from the env `OTEL_EXPORTER_OTLP_HEADERS` should be set as metadata for grpc exporter.

**Comment by TommyCpp** [comment]
Thanks for the report I will take a look. Should be an easy fix

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/pull/1290 The PR description explains why supporting this for gRPC is non-trivial, hence not done (yet).

**Comment by cijothomas** [comment]
@TommyCpp given Env vars are optional from spec, I think this can be treated as an enhancement, not a bug.
