### ISSUE TITLE
How to include trace_id in response header when using opentelemetry-otlp?

### ISSUE THREAD

**Issue by npuichigo** [open-telemetry/opentelemetry-rust#1338]
Great to switch to use `opentelemetry-otlp` from `opentelemetry-jaeger`, but some middleware like `axum-tracing-opentelemetry` failed to include trace id in response header for user to debug.

Any advice or practice on how to do that? Or how can we correspond the tracing result in for example Jaeger to user's specfic request?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/tree/main/examples/traceresponse Could you check if this is what you are looking for?

**Comment by npuichigo** [comment]
I use axum and it there any example of middleware to handle this? By the way, what about logging in opentelemetry-otlp? Will that useful to trace user log?

**Comment by cijothomas** [comment]
Unfortunately, my expertise in this space is very limited to offer more help.
The examples uses hyper, but the concept should be re-usable in any framework.

**Comment by npuichigo** [comment]
> Just to clearify are you saying you have trace id in response header when using `axum-tracing-opentelemetry` with `opentelemetry-jaeger` exporter but not when using the middleware with `opentelemetry-otlp` exporter?

Yes. I saw deprecated info in `opentelemetry-jaeger` and recommend to use `opentelemetry-otlp` instead. But I lose the feature after switching.

**Comment by TommyCpp** [comment]
Got it. On top of my mind I don't have a good idea how as exporter should be transparent to middleware. Maybe it has something to do with the propagator side. We will have to look into this a little deeper

**Comment by npuichigo** [comment]
I'm sorry I missed to pass a proper propagator as used with `opentelemetry-jaeger`. I misunderstood that `opentelemetry-otlp` would have it's own propagator but found none.

Since I use `Jaeger`, I still set global propagator as `opentelemetry::global::set_text_map_propagator(opentelemetry_jaeger::Propagator::new());` and it works for `opentelemetry-otlp` exporter.

**Comment by cijothomas** [comment]
I think the confusion here is `opentelemetry-jaeger` crate has both propagator *and* exporter. The exporter part will be removed but the propagator will not be. It has to be renamed to clearly indicate that the crate is for jaeger propagator.

Deprecation timeline for this repo is still being finalized - its already removed from spec and other languages. So expect it to occur anytime, so I'd suggest to switch to OTLPExporter right away (so we'll also know if something is missing with OTLP Exporter to meet the needs)

**Comment by npuichigo** [comment]
thanks for your reply
