### ISSUE TITLE
Not possible to instantiate metrics via api::Meter

### ISSUE THREAD

**Issue by iffyio** [open-telemetry/opentelemetry-rust#135]
Hi!

I started looking at this crate to provide an abstraction over metrics backends in a program. The idea is that a piece of code would e.g increment a counter via an interface rather than, say, a Prometheus counter directly.

It doesn't seem it will be possible to accomplish this with this crate's metrics interface.

My assumption is that this is one of the goals of this crate - this might be a wrong assumption, in which case these issues might not be valid to begin with.

The first issue seems to be the `Meter` trait's use of self-referencing associated types which rust (as of v1.43.0) doesn't handle very well.

As an example, I might want code that talks via the `Meter` interface to the sdk implementation

```rust
    let meter = opentelemetry::sdk::Meter::new("meter1");

    let _: Box<dyn opentelemetry::api::Meter<
        LabelSet=_,
        I64Counter=_,
        F64Counter=_,
        I64Gauge=_,
        F64Gauge=_,
        I64Measure=_,
        F64Measure=_
    >> = Box::new(meter); // Does not compile.
```

This fails with:
```
 type I64Counter: Counter<i64, Self::LabelSet>;
    |                        ---------------------------- the trait cannot be made into an object because it uses `Self` as a type parameter in this
```
The second, related issue is that I won't be able to say, write a function, which at runtime, chooses and returns (say based on config) an implementation of the `Meter` trait since rust doesn't support abstracting over trait implementations that have different associated types.

For example:
```rust
  // No such values would be suitable for `???` since they differ for Meter implementations
  fn get_arbitrary_meter() -> impl Meter<???> {
    if true {
      opentelemetry::sdk::Meter::new("meter1")
    } else {
      someOtherMeterImpl{}
    }
  }
```

**Comment by jtescher** [comment]
The metrics API is still a work in progress, see https://github.com/open-telemetry/opentelemetry-specification/pull/347 and other open PRs for examples of things that will change, as such you may want to wait before you try to use it in this state.
