### ISSUE TITLE
[Bug]: could not find `runtime` in `opentelemetry`

### ISSUE THREAD

**Issue by ibigbug** [open-telemetry/opentelemetry-rust#1357]
### What happened?

I see there's a change relates to #1186  in v0.21.0

and docs also updated to use the new namespace `.install_batch(opentelemetry_sdk::runtime::Tokio)?;`

questions is do we now need to explictly add opentelemetry_sdk as a dependency?

i can't seem to import it from any of these

```
[dependencies]
opentelemetry = { version = "*", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "*", features = ["rt-tokio"] }
```

linked here https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-jaeger#performance

### API Version

v0.21.0

### SDK Version

v0.21.0

**Comment by jtescher** [comment]
`runtime` has been moved to the SDK https://docs.rs/opentelemetry_sdk/latest/opentelemetry_sdk/runtime/index.html

**Comment by ibigbug** [comment]
I guess doc needs an update too then
