### ISSUE TITLE
sdk::Meter crashes the program if not configured properly

### ISSUE THREAD

**Issue by iffyio** [open-telemetry/opentelemetry-rust#136]
Hi!

Here are two cases where the sdk panics

1. using duplicate keys when creating an instrument e.g 
```rust
    let meter = sdk::Meter::new("meter1");
    let foo_key = api::Key::new("fookey");
    let bar_key = api::Key::new("fookey");
    let counter = meter.new_f64_counter("c",
      api::MetricOptions::default().with_keys(vec![foo_key.clone(), bar_key.clone()])); // panics

```

2. providing labels to `acquire_handle` that don't match those passed to the instrument e.g
```rust
    let meter = sdk::Meter::new("meter1");
    let foo_key = api::Key::new("fookey");
    let bar_key = api::Key::new("barkey");
    let counter = meter.new_f64_counter("c",
      api::MetricOptions::default().with_keys(vec![foo_key.clone(), bar_key.clone()]));

    let labels = meter.labels(vec![foo_key.string("foovalue")]);
    let _ = counter.acquire_handle(&labels); // panics

    // thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InconsistentCardinality(2, 1)'
```

In both cases, it would be friendlier with an api that makes it explicit that these operations can fail and leave the error handling up to the caller - For example `1` could return a `Result` instead while `2` an `Option` since its analogous to fetching something (a handle) that may or maynot exist.
The current behavior makes an implicit decision hidden from the user and the error message from `2` about `InconsistentCardinality` makes the problem cryptic to the user on failure.

**Comment by jtescher** [comment]
These come from the current implementation being basically a proxy for the `prometheus` crate in https://github.com/tikv/rust-prometheus/blob/8c8e65f1fbe6470573950fd787ebdd4ed5d9f345/src/errors.rs#L13. This should be fixed in a future release as the spec now allows for result responses.
