### ISSUE TITLE
opentelemetry-jaeger: Do no add `span.kind` tag if it has been set as an attribute

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#137]
Currently if the `span.kind` attribute is set, opentelemetry-jaeger will add a second one when it submits the jaeger data.

**Comment by siyopao** [comment]
Is it okay if I give this one a shot? If so, just one question to clarify, does this mean checking whether the `attribute` map in `SpanData` already contains `span.kind`, and if it does, then do not add `SpanData`s `span_kind` to the tag?

Thank you!

**Comment by jtescher** [comment]
@siyopao great! yeah basically https://github.com/open-telemetry/opentelemetry-rust/blob/master/opentelemetry-jaeger/src/lib.rs#L382-L415 should only add the attributes it does if they are not already set.

**Comment by jtescher** [comment]
Also could update https://github.com/open-telemetry/opentelemetry-rust/blob/master/opentelemetry-zipkin/src/lib.rs#L239-L250 if you are interested as it also has the incorrect behavior

**Comment by siyopao** [comment]
Hi @jtescher. Sure, no problem. Just one further clarification: if `span.kind` is found in `span_data.attributes` then `span_data.span_kind` should _not_ be added to the tags, or should `span_data.span_kind` always be added and any currently existing `span.kind` in the attributes be ejected? I get the feeling it is the former. Thank you.

**Comment by jtescher** [comment]
@siyopao Your feeling is correct, it should not be added if the user has specified it in the attributes 👍
