### ISSUE TITLE
Some links to "OpenTelemetry project standard event names and keys" are broken

### ISSUE THREAD

**Issue by siyopao** [open-telemetry/opentelemetry-rust#138]
For example, https://github.com/open-telemetry/opentelemetry-rust/blob/6f14587ff08a7dac53e73e7ef8c8d2cd11194ae8/src/api/trace/span.rs#L47.

I would happily create a PR to fix these but I am not quite sure to what they should be linking to. Possibly https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions?

**Comment by jtescher** [comment]
@siyopao thanks for finding these! yeah that's probably where it should point now. Probably also worth putting the spec release version in the URL (currently v0.5.0) to avoid future issues like this.
