### ISSUE TITLE
Consider `temp-env`  for environment testing

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-rust#1383]
> I moved common code for http and tonic exporters in `exporter/mod.rs` (function to parse header from string and test helper to run tests with isolated env variables)
I wanted to minimize the changes but maybe it should be a good idea to use a crate like https://crates.io/crates/temp-env for environment related testing

_Originally posted by @harscoet in https://github.com/open-telemetry/opentelemetry-rust/pull/1377_

**Comment by jtescher** [comment]
Yeah those tests are flakey currently. Good to get a fix 👍
