### ISSUE TITLE
End time should be configurable

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-rust#14]
Per the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/e6cd52d034c981ca4fcf896ccd7464e783589c0f/specification/api-tracing.md#end).

**Comment by iredelmeier** [comment]
This might be easier if spans as they exist now were instead builders, and only _become_ spans on `end`? #13 touches on this a bit.

**Comment by TommyCpp** [comment]
It feels like just need to add a `end_with_timestamp` function in `Span`. Not sure if I missed something. But I'd like to give it a try if that's OK

**Comment by jtescher** [comment]
@TommyCpp  Yeah there were originally questions around what options would be required but it seems like the answer now is just end time so a method should be sufficient 👍
