### ISSUE TITLE
[Feature]: SimpleSpanProcessor to be consistent with SimpleLogRecordProcessor

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1409]
### Describe the solution you'd like:

https://github.com/open-telemetry/opentelemetry-rust/pull/1308 modified SimpleLogRecordProcessor to simply take a Mutex protected call to Exporter. 
Proposing to make the similar change to SimpleSpanProcessor, effectively reversing https://github.com/open-telemetry/opentelemetry-rust/pull/502.

We'll get to eliminate the crossbeam-channel by doing this, and also ensures there is more consistency between signals.

**Comment by jtescher** [comment]
This may simplify things, but we should check the overall throughput to make sure it's still acceptable given our performance focus (e.g. if an exporter has an average latency of ~1 second)

**Comment by cijothomas** [comment]
I don't think the perf would be good here (and will directly be affected by how slow the exporter is!). For performance scenarios - there is BatchProcessors to the rescue, so my main point was - we should not worry about perf for SimpleProcessor, which should only be used for testing/learning purposes!

**Comment by cijothomas** [comment]
Any further comments/objections to do this?

**Comment by lalitb** [comment]
One of the concerns I believe was users needing performance in hot-path without depending on the external runtime. This should be resolved with #1506.
