### ISSUE TITLE
Should this repo maintain examples showing tracing-opentelemetry?

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1413]
https://github.com/open-telemetry/opentelemetry-rust/tree/main/examples/tracing-http-propagator shows using Tracing API from this Repo to demonstrate how to do tracing + propagation.

https://github.com/open-telemetry/opentelemetry-rust/tree/main/examples/tracing-grpc This is using `tracing-opentelemetry` crate, achieving similar end-results. Should we remove those examples from this repo, and instead ask them to be maintained in https://github.com/tokio-rs/tracing-opentelemetry/tree/v0.1.x/examples? Since the split to contrib repo, https://github.com/open-telemetry/opentelemetry-rust/tree/main/examples/tracing-grpc is the only place where tracing-opentelemetry is used. We do link to the crate in many docs, and that is necessary, but maintaining examples using tracing-opentelemetry may not be desirable.

Related : [Discussion about OTel Tracing API vs Tokio Tracing ](https://github.com/open-telemetry/opentelemetry-rust/discussions/1032).

**Comment by lalitb** [comment]
I feel it is good to have both `tracing-http` and `tracing-grpc` examples, as the latter also shows how to use the propagator with tonic metadata. How about removing `tracing-opentelemetry` dependency from this `tracing-grpc` example?

**Comment by cijothomas** [comment]
Yes, it makes sense to maintain tracing-grpc. I was thinking of removing the tracing-opentelemetry part only and instead follow the tracing-http style of showing OTel Tracing API. If a user ends up with tracing-opentelemetry separately, it'll likely result in duplicate?, so a warning can be mentioned here and in tracing-opentelemetry about that.

**Comment by TommyCpp** [comment]
Agree we should move those examples to `tracing-opentelemetry`. Different from most of example which uses the master branch. Examples using `tracing-opentelemtry` uses last released version. So probably better to move it to `tracing-opentelemetry` repo
