### ISSUE TITLE
Allow array values for attributes

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#142]
Add array variant to `Value` enum, see [the spec change](https://github.com/open-telemetry/opentelemetry-specification/pull/368) for details.

**Comment by siyopao** [comment]
I don't mind working on this if that is okay? But I am not sure how to enforce the requirement "The array MUST be homogeneous, i.e. it MUST NOT contain values of different types." unless we add a kind for every possible primitive value in the `Value` enum, e.g. `Array(Vec<Value::Bool>)`. Is there a better way?

**Comment by jtescher** [comment]
Hm yeah. Maybe check when constructing instances of `Value::Array`? I'd also be open to adding them without the check first and dealing with the validation in a later PR.
