### ISSUE TITLE
Add tests for appender-log crate

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1420]
appender for log crate has no tests today. Could borrow the approach from https://github.com/open-telemetry/opentelemetry-rust/pull/1415 and some coverage.

**Comment by mattbodd** [comment]
@cijothomas I'm interested in taking this on

**Comment by mattbodd** [comment]
@cijothomas I created a PR with an initial set of tests. Please let me know if these tests are meaningful and what you expected.
