### ISSUE TITLE
[Bug]: TracerProvider::force_flush moved from API to SDK without any way to downcast GlobalTracerProvider

### ISSUE THREAD

**Issue by ramosbugs** [open-telemetry/opentelemetry-rust#1423]
### What happened?

PR #658 (issue #588) moved the `force_flush` function from the `opentelemetry::trace::TracerProvider` trait to the `opentelemetry_sdk::trace::TracerProvider` struct. However, there does not appear to be any API to downcast the `GlobalTracerProvider` to `opentelemetry_sdk::trace::TracerProvider`.

Prior to the 0.18.0 release, it was possible to do the following:
```rust
opentelemetry::global::tracer_provider().force_flush()
```

Since `opentelemetry::global::set_tracer_provider` takes ownership of the provider, I don't think there is any way to actually call this function with the current public API.

cc: @rohithv1997 @TommyCpp @jtescher 

### API Version

0.18.0

### SDK Version

0.18.0

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/blob/main/examples/tracing-jaeger/src/main.rs#L46 Could you see if this is what you are looking for?

**Comment by ramosbugs** [comment]
@cijothomas: Thanks for the quick reply!

The use case here is FaaS/"serverless" (e.g., AWS Lambda). Specifically, we need a way to flush traces after a request completes, but before AWS Lambda freezes the container to wait for the next request (which may never come, in which case unflushed traces are lost). Prior to the 0.18 release, I would have called `opentelemetry::global::tracer_provider().force_flush()` [here](https://github.com/awslabs/aws-lambda-rust-runtime/blob/3231e9f144d73b56759d1acbd8e243d283657ca0/examples/extension-internal-flush/src/main.rs#L43), but that's no longer possible.

Shutting down and registering a new tracing provider for each request seems like it would introduce a lot of unnecessary overhead, when we just need access to the `force_flush` method.

**Comment by ramosbugs** [comment]
Also, I'm willing to contribute a PR to get this done once there's consensus on the API changes.

**Comment by jtescher** [comment]
@ramosbugs how/where is the tracer provider being created in this case?

**Comment by ramosbugs** [comment]
I'm using the following code when the Lambda process starts (i.e., from `main`), before it enters its request loop:
```rust
let batch = BatchSpanProcessor::builder(exporter, opentelemetry::runtime::Tokio)
  .with_max_queue_size(MAX_SPAN_QUEUE_SIZE)
  .build();

let provider = TracerProvider::builder()
  .with_span_processor(batch)
  .with_config(tracer_config)
  .build();

opentelemetry::global::set_tracer_provider(provider);

```

**Comment by ramosbugs** [comment]
One possible solution is to `impl<T> TracerProvider for Arc<T> where T: TracerProvider`. Then, we can just pass a copy of the `Arc<opentelemetry_sdk::trace::TracerProvider>` to `set_tracer_provider` and maintain our own copy for access to `force_flush`.

I don't see anything that requires a mutable reference to the provider, so an `Arc` seems like it should work?

**Comment by jtescher** [comment]
`TracerProvider` is already clone, so you don't need the `Arc`, you can pass a clone to `set_tracer_provider` directly 👍

**Comment by ramosbugs** [comment]
Oh, I totally missed that! Thank you, I will confirm that this works and then close the issue or report back otherwise.
