### ISSUE TITLE
[Bug]: `cargo test` compile errors due to log crate removals

### ISSUE THREAD

**Issue by KallDrexx** [open-telemetry/opentelemetry-rust#1439]
### What happened?

When running `cargo test` from the root of the code base, the following compile errors occur:

```
   Compiling opentelemetry-appender-tracing v0.2.0 (/home/mshapiro/code/opentelemetry-rust/opentelemetry-appender-tracing)
error[E0433]: failed to resolve: use of undeclared crate or module `log`
   --> opentelemetry-appender-tracing/src/layer.rs:415:9
    |
415 |         log::error!("log from log crate");
    |         ^^^ use of undeclared crate or module `log`

error[E0433]: failed to resolve: use of undeclared crate or module `log`
   --> opentelemetry-appender-tracing/src/layer.rs:492:13
    |
492 |             log::error!("log from log crate");
    |             ^^^ use of undeclared crate or module `log`

error[E0433]: failed to resolve: use of undeclared crate or module `tracing_log`
   --> opentelemetry-appender-tracing/src/layer.rs:412:14
    |
412 |         drop(tracing_log::LogTracer::init());
    |              ^^^^^^^^^^^ use of undeclared crate or module `tracing_log`
    |
help: there is a crate or module with a similar name
    |
412 |         drop(tracing_core::LogTracer::init());
    |              ~~~~~~~~~~~~

error[E0433]: failed to resolve: use of undeclared crate or module `tracing_log`
   --> opentelemetry-appender-tracing/src/layer.rs:478:14
    |
478 |         drop(tracing_log::LogTracer::init());
    |              ^^^^^^^^^^^ use of undeclared crate or module `tracing_log`
    |
help: there is a crate or module with a similar name
    |
478 |         drop(tracing_core::LogTracer::init());
    |              ~~~~~~~~~~~~
```

This seems to have been called by PR #1380 being merged, as I don't have this before commit 66c1d5f.

I'm not sure why this does not occur on CI.

### API Version

N/A

### SDK Version

N/A

**Comment by lalitb** [comment]
The tests added as part of PR #1380 should be behind feature flag as well. @Rockin2 fyi.

**Comment by Rockin2** [comment]
Oops. I will fix that.

**Comment by Rockin2** [comment]
Can you assign me this issue?

**Comment by Rockin2** [comment]
We have another problem too. When I run cargo test in the opentelemetry-appender-tracing folder, it doesn't compile too because it needs the testing feature feature.

**Comment by cijothomas** [comment]
> We have another problem too. When I run cargo test in the opentelemetry-appender-tracing folder, it doesn't compile too because it needs the testing feature feature.

https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-appender-tracing/src/layer.rs#L234 Yea all tests using inmemoryexporter needs testing feature.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/actions/runs/7185821321/job/19569877505#:~:text=running%204%20tests,tracing_appender_standalone_with_tracing_log%20...%20ok

The CI check is running fine...

**Comment by Rockin2** [comment]
Instead of putting these tests inside a feature flag, I just added the dependencies in the dep.dependencies. The logic here is we don't have control on whether the user will use tracing_log or not. I could be activated in the application and the opentelemetry-appender-tracing crate doesn't need to depend on it to capture logs from the log crate with tracing.
