### ISSUE TITLE
[Feature]: opentelemetry-appender-tracing should use semantic conventions

### ISSUE THREAD

**Issue by bouk** [open-telemetry/opentelemetry-rust#1445]
### Describe the solution you'd like:

There's an `experimental_metadata_attributes` feature on opentelemetry-appender-tracing that adds some attributes related to the code location: https://github.com/open-telemetry/opentelemetry-rust/blob/4e80e3a2ebf96a166917b169f7d27e44e83cd3da/opentelemetry-appender-tracing/src/layer.rs#L53-L90

These don't use the [semantic convention names](https://opentelemetry.io/docs/specs/semconv/general/attributes/#source-code-attributes), which they should so the field naming is consistent across tooling.

@Rockin2

**Comment by Rockin2** [comment]
Great that we have a convention for those field like ECS! :) Can you assign me this issue please? :) I will do that tomorrow.

**Comment by cijothomas** [comment]
Need to keep in mind that the conventions are still experimental, so we need to do this under feature flags as well.
