### ISSUE TITLE
could not find `SpanExporter` in `opentelemetry_stdout`

### ISSUE THREAD

**Issue by dceravigupta** [open-telemetry/opentelemetry-rust#1460]
### What happened?

I'm trying to add tracing for incoming requests using open telemetry in a hello world web service written in Rust using actix-web framework. Instead of sending collected traces to any observability platform, I was trying to log them to stdout hence decided to use opentelemetry-stdout crate but for some reason, my service keep giving following error `failed to resolve: could not find `SpanExporter` in `opentelemetry_stdout` on build.

Here is my main.rs

    use actix_web::{get, App, HttpResponse, HttpServer, Responder};
    use openssl::ssl::{SslAcceptor, SslFiletype, SslMethod};
   
    use actix_web_opentelemetry::RequestTracing;
    use opentelemetry_sdk::trace::TracerProvider;
    
    #[get("/")]
    async fn hello() -> impl Responder {
        HttpResponse::Ok().body("Hello world!")
    }
    
    #[actix_web::main]
    async fn main() -> std::io::Result<()> {
        // load TLS keys
        // to create a self-signed temporary cert for testing:
        // `openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 365 -subj '/CN=localhost'`
        let mut builder = SslAcceptor::mozilla_intermediate(SslMethod::tls()).unwrap();
        builder
            .set_private_key_file("key.pem", SslFiletype::PEM)
            .unwrap();
        builder
            .set_certificate_chain_file("cert.pem")
            .unwrap();
    
        // Install an OpenTelemetry trace pipeline.
        // Swap for https://docs.rs/opentelemetry-jaeger or other compatible
        // exporter to send trace information to your collector.
        let exporter = opentelemetry_stdout::SpanExporter::default();
    
        // Configure your tracer provider with your exporter(s)
        let provider = TracerProvider::builder()
            .with_simple_exporter(exporter)
            .build();
    
        opentelemetry::global::set_tracer_provider(provider);
    
        HttpServer::new(|| {
            App::new()
                .wrap(RequestTracing::new())
                .service(hello)
        })
        .bind_openssl("127.0.0.1:6000", builder)?
        .run()
        .await
    }

Cargo.toml

    [package]
    name = "xx"
    version = "0.1.0"
    edition = "2021"
    
    [dependencies]
    actix-web = { version = "4", features = ["openssl"] }
    actix-web-opentelemetry = "0.16.0"
    openssl = { version = "0.10" }
    opentelemetry = { version = "0.21" }
    opentelemetry_sdk = { version = "0.21" }
    opentelemetry-stdout = { version = "0.2" }`

### API Version

actix-web-opentelemetry = "0.16.0"
opentelemetry = { version = "0.21" }
opentelemetry_sdk = { version = "0.21" }
opentelemetry-stdout = { version = "0.2" }

### SDK Version

cargo 1.72.0 (103a7ff2e 2023-08-15)

### Relevant log output

```shell
Compiling openssl-sys v0.9.98
   Compiling openssl v0.10.62
   Compiling tokio-openssl v0.6.4
   Compiling xx v0.1.0 (...)
error[E0433]: failed to resolve: could not find `SpanExporter` in `opentelemetry_stdout`
  --> src\main.rs:28:42
   |
28 |     let exporter = opentelemetry_stdout::SpanExporter::default();
   |                                          ^^^^^^^^^^^^ could not find `SpanExporter` in `opentelemetry_stdout`
   |
help: consider importing this trait
   |
1  + use opentelemetry_sdk::export::trace::SpanExporter;
   |
help: if you import `SpanExporter`, refer to it directly
   |
28 -     let exporter = opentelemetry_stdout::SpanExporter::default();
28 +     let exporter = SpanExporter::default();
   |
```

**Comment by lalitb** [comment]
Try with explicitly enabling the `trace` feature for `opentelemetry-stdout`:

```rust
opentelemetry-stdout = { version = "0.2", features = ["trace"] }
```

**Comment by dceravigupta** [comment]
It worked after enabling `trace` feature. Thanks!
