### ISSUE TITLE
[Feature]: Add an Arc to ManualReader or make SharedReader public

### ISSUE THREAD

**Issue by divergentdave** [open-telemetry/opentelemetry-rust#1466]
### Related Problems?

See #1329 for previous discussion.

### Describe the solution you'd like:

Currently, `ManualReader` is not useful on its own. I tried using it in a unit test, but `MeterProviderBuilder::with_reader()` takes ownership of the `MetricReader` implementation that is passed in. Thus, I can't call `ManualReader::collect()` later. I am aware of three uses of `ManualReader`, and all three create their own newtype around `Arc<ManualReader>`, and implement `TemporalitySelector`, `AggregationSelector`, and `MetricReader` on it, dispatching to the inner reader in the natural way. This is done in `opentelemetry-sdk/benches/metric.rs` and `opentelemetry-prometheus/src/lib.rs` in this repository, and in `tracing-opentelemetry`, in `tests/metrics_publishing.rs`.

I think it would make sense to change `ManualReader` so that it is an `Arc` around an inner struct, and thus can be cloned.

### Considered Alternatives

Alternately, the `SharedReader` struct currently in the benchmark could be moved into the library proper, and made public. This would allow users to opt-in to the `Arc`, and reduce the boilerplate they have to write.

**Comment by lalitb** [comment]
If the use-case is for testing, you can use [InMemoryMetricsExporter](https://github.com/open-telemetry/opentelemetry-rust/blob/v0.21.2/opentelemetry-sdk/src/testing/metrics/in_memory_exporter.rs). You should be able to mimic the behavior of ManualReader by keeping the periodic interval very high (for entire test duration), and call `InMemoryMetricsExporter::flush()` for collection, and subsequently `InMemoryMetricsExporter::get_finished_metrics()` to fetch and validate the metrics.

**Comment by divergentdave** [comment]
Ah, I missed that because the module is `#[doc(hidden)]`. Is the `testing` feature intended for use by downstream users, or is that primarily for internal use?

**Comment by lalitb** [comment]
It is part of the [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.28.0/specification/metrics/sdk_exporters/in-memory.md), so should be available to the downstream users for testing purpose.
