### ISSUE TITLE
[Feature]: Expose BatchLogProcessor configuration

### ISSUE THREAD

**Issue by CosminLazar** [open-telemetry/opentelemetry-rust#1468]
### Describe the solution you'd like:

When you configure an OTLP log pipeline the settings for the `BatchLogProcessor` are hardcoded.

e.g.: 
```
    opentelemetry_otlp::new_pipeline()
        .logging()
        .with_log_config(...)
        .with_exporter(...)
        .install_batch(opentelemetry::runtime::Tokio)
```

The settings for the for the `BatchLogProcessor` are
```
        BatchConfig {
            max_queue_size: 2_048,
            scheduled_delay: Duration::from_millis(1_000),
            max_export_batch_size: 512,
            max_export_timeout: Duration::from_millis(30_000),
        }
```

I would like to be able to configure the `BatchConfig` settings.

**Comment by lalitb** [comment]
Agree, this is a valid issue. Will try to fix during this week.

**Comment by CosminLazar** [comment]
Glad to hear that, if you have some hints on how you might want that implemented I might be able to give it a try myself.

**Comment by lalitb** [comment]
That would be awesome @CosminLazar . We need to add `OtlpLogPipeline::with_batch_config` method to configure the batch processor configuration. You can follow the similar code flow for [OtlpTracePipeline::with_batch_config](https://github.com/open-telemetry/opentelemetry-rust/blob/ff64e214064df438a09a5c1695ec73866925f981/opentelemetry-otlp/src/span.rs#L77) for the changes. Assigning to you :)
