### ISSUE TITLE
Make B3 propagator fully support spec

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#147]
The existing implementation of the B3 propagator does not fully implement the HTTP B3 specification. 

Full B3 Specification: https://github.com/openzipkin/b3-propagation

See similar PR in go impl for needed changes: https://github.com/open-telemetry/opentelemetry-go/pull/882

**Comment by TommyCpp** [comment]
If no one is currently working on this one. I'd like to give it a try.

**Comment by jtescher** [comment]
@TommyCpp sounds good! happy to answer questions as you work through it, hopefully the referenced go changes are useful as well.

**Comment by TommyCpp** [comment]
@jtescher Thanks! I think I finished most of the changes but may still need some time to double check with go implementation to make sure I got all test case covered, after that I should have a PR for review.
