### ISSUE TITLE
[Feature]: Use `opentelemetry-semantic-conventions` internally.

### ISSUE THREAD

**Issue by gibbz00** [open-telemetry/opentelemetry-rust#1470]
### Describe the solution you'd like:

Took a look at some of the `ResourceDetector` implementations and noticed that they used hard-coded key strings rather than relying on  `opentelemetry-semantic-conventions`. For example: https://github.com/open-telemetry/opentelemetry-rust/blob/27d338dd954ef7681242ead47a8a61c964dcc428/opentelemetry-sdk/src/resource/env.rs#L78-L80

I'm wondering if this is intentional or if it would be wise to begin using the typeset constants internally. Might not be worth much but perhaps a good first issue for me :)

**Comment by cijothomas** [comment]
@gibbz00 Would you be interested in sending a PR to address this?

(one caveat is the - the semantic conventions are only partially stable)

**Comment by gibbz00** [comment]
Might do. I'm currently a bit pressed for time, so unsure when that would be.

Well hehe, the reason I suggested using the semantic conventions lib internally was to address that exact issue. I thought it would make unified updates to any semantic conventions attributes less of a hassle.

**Comment by cijothomas** [comment]
Though this issue got marked as good-first-issue, I don't think that is actually true. The semantic conventions crate cannot be added as a dependency to the `opentelemetry_sdk` crate, so the only feasible option is to continue to hard code keys for those. We don't expect SDK crate to need semantic conventions for anything other than the one it already has hard code keys.

(Semantic Conventions are meant for instrumentations, resource detectors only)

I'll mark this issue as closed as there is nothing actionable here at the moment!

@robin-thoene Sorry for the confusion. Please feel free to look for other open issues that are in need of help.
