### ISSUE TITLE
[Feature]: Update HTTP dependencie to ^1.0.0

### ISSUE THREAD

**Issue by janbraunsdorff** [open-telemetry/opentelemetry-rust#1476]
### Related Problems?

Hello,

I was wondering why some Documentation about Opentelemetry and hyper not working for me. It turns out, that opentelemety depends on http 0.2 and most of my other crate were updatet to http ^1.0.0 like hyper, hyper-body and axum. 
Is there a plan to also increase the verion which opentelemetry depends on to 1.0.0.
Of course without braking other project or other issues?

Best regards

### Describe the solution you'd like:

Opentelemetry is compatible with http ^1.0.0

### Additional Context

Error Message:

`HeaderMap` and `http::header::map::HeaderMap` have similar names, but are actually distinct types
perhaps two different versions of crate `http` are being used?

```rust
  let ctx = opentelemetry::global::get_text_map_propagator(|pro| {
      pro.extract(&HeaderExtractor(request.headers()))
  });
```

**Comment by TommyCpp** [comment]
This seems to be duplicate with #1427 

We were blocked on tonic when trying to upgrade to http 1.0 but I think we have an idea on how to upgrade now
