### ISSUE TITLE
There should be a way to create a synchronous guage.

### ISSUE THREAD

**Issue by ewoolsey** [open-telemetry/opentelemetry-rust#1483]
Basically, there should be a way to create a gauge that doesn't require a callback to be set. Perhaps there is some magic that one can do currently which allows this with `ObservableGauge` but I have not seen how. There are two main reasons I can think of for this feature.

1. compatibility with the `metrics` facade. Their implementation uses synchronous gauges so theoretically it would be possible to make a `metrics-exporter-opentelemety`. This is my current use case, and as far as I can tell this is unsolvable without this feature.
2. You have have a value that you keep track of that only changes during events, think the balance in a wallet. The observable gauge isn't great here since it doesn't update during the event. A counter would also be problematic in this situation for obvious reasons.

**Comment by lalitb** [comment]
@ewoolsey  there is experimental support for Synchronous gauge added as part of #1410, just in case you are looking for this.

**Comment by ewoolsey** [comment]
@lalitb I swear I did a search for this and somehow didn't find anything. Thanks so much for the link that is exactly what I need to make this work! I'll close with this comment!
