### ISSUE TITLE
Remove aws id generator from core sdk

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1489]
https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/trace/id_generator/aws.rs must be moved to contrib crate and should not be part of core sdk.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#id-generators

**Comment by sreeo** [comment]
how do we proceed with the removal from the core repo? Do we add a deprecated message/warning and release a version?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/pull/1560 You can copy some of the ideas from this PR. (That PR removes an entire crate, but this is just a functionality, so adjust wordings accordingly.)

**Comment by sreeo** [comment]
Would this be the right time to raise a PR where the XrayIdGenerator is removed from the core repo? Or do we wait for a few releases?

**Comment by cijothomas** [comment]
> Would this be the right time to raise a PR where the XrayIdGenerator is removed from the core repo? Or do we wait for a few releases?

Hey sorry I missed this message until now! It should be removed now : https://github.com/open-telemetry/opentelemetry-rust/pull/1820
