### ISSUE TITLE
[Bug]: incorrect docs on SdkMeterProvider.builder()

### ISSUE THREAD

**Issue by justinabrahms** [open-telemetry/opentelemetry-rust#1494]
### What happened?

https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/metrics/meter_provider.rs#L41-L45

Looks like there was copy+paste error from the method below.

### API Version

main

### SDK Version

main

**Comment by cijothomas** [comment]
Thanks for reporting! Mind sending a PR with a fix, if you have some cycles?

**Comment by TommyCpp** [comment]
should be patched with #1499. Will close this for now
