### ISSUE TITLE
Add trace exception tracking method

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#151]
A `record_exception` method should be added to the [Span API](https://github.com/open-telemetry/opentelemetry-rust/blob/master/src/api/trace/span.rs#L25-L125). See the [spec change](https://github.com/open-telemetry/opentelemetry-specification/pull/697) for details.

**Comment by TommyCpp** [comment]
I am curious how should we represent stacktrace in Rust. Here we want to record `Err` instead of `panic`, which by itself doesn't have  a way to get stacktrace in stable. There is a backtrace method in nightly though.

**Comment by jtescher** [comment]
@TommyCpp Good question. Seems as though the error crates seem to be building up crate-specific backtraces currently to compensate like https://docs.rs/eyre/0.6.0/eyre/struct.Report.html or https://docs.rs/anyhow/1.0.31/anyhow/struct.Chain.html.

One possibility would be `record_exception(message: String, backtrace: Option<String>)` and let people build it up themselves, or possibly have features to accept crate-specific error types. The former may be simpler as the ecosystem / std lib are still evolving here and we don't want to have to make breaking changes here ideally. Did you have alternatives in mind?

**Comment by TommyCpp** [comment]
@jtescher Good idea! But maybe it make more sense to accept an `Box<dyn Error>` as first param? And if user have some kind of message they can always override `fmt` method.

 Just my thought but it feels like we should be recording some kind of `Error` here. And when they stablize [Error::backtrace](https://doc.rust-lang.org/std/error/trait.Error.html#method.backtrace) we could use it as default if no backtrace is provided by user.

**Comment by jtescher** [comment]
@TommyCpp Yeah could be best to go with `Error` for now. Also the exception nomenclature in the spec is a little unfortunate. `record_error(error: Box<dyn Error>)`  or `record_err(err: Box<dyn Error>)` seem more natural for rust.

**Comment by jtescher** [comment]
Also depding on the impl `&dyn Error` may be preferred here to avoid forcing consumers of the API to box.

**Comment by TommyCpp** [comment]
Yeah but to be fair expection probably would be intutive for Java and some other languages. Anyway, mind if I work on this?
