### ISSUE TITLE
Prometheus exporter dependency

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1557]
https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-prometheus/Cargo.toml#L26 Currently, exporter depends on the `prometheus` crate. This crate is not the [official prometheus](https://prometheus.io/docs/instrumenting/clientlibs/) client.

This issue is opened to explore if we should switch to the official client library - https://crates.io/crates/prometheus-client , or maybe remove the dependency altogether.

**Comment by hdost** [comment]
Let's continue this in https://github.com/open-telemetry/opentelemetry-rust/issues/1551
