### ISSUE TITLE
Memory optimization for metric datapoints

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1566]
[Metric datapoints](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/metrics/data/mod.rs#L102-L104) currently store the starttime and endtime of the data point.

Since starttime and endtime will be same for each and every datapoint within a metric, it can be moved to the [Sum struct](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/metrics/data/mod.rs#L78) itself, instead of repeating it for each datapoint. (Similar for Gauge/Histograms too).

**Comment by cijothomas** [comment]
This will be a breaking change for folks authoring metric exporters, and must be done before SDK stable release.

**Comment by hdost** [comment]
Is that the case ?
Start time should be the first point in time something existed 
End time is usually when the datapoint was recorded.

**Comment by cijothomas** [comment]
> Is that the case ?

Yes. Every datapoint/metricpoint(time-series) in the same metric has same start/end time for a collection.

**Comment by hdost** [comment]
> > Is that the case ?
> 
> 
> 
> Yes. Every datapoint/metricpoint(time-series) in the same metric has same start/end time for a collection.



> This field indicates to consumers the
// start time for points with cumulative and delta
// AggregationTemporality, and it should be included whenever possible
// to support correct rate calculation.

From the proto

**Comment by cijothomas** [comment]
What does the proto tell? I am not able to follow your concern. Could you elaborate or send a unit test showing the issue?

**Comment by hdost** [comment]
Perhaps for sum its not an issue since we are just adding all structures together, but if in a collection for a histogram you need to aggregate latencies. The observation time matters.

**Comment by cijothomas** [comment]
Yes I can see your point, but the current implementation in this repo does not support that - it uses same start and end for all datapoints.
Also, I don't think we ever record the precise time at which the measurement was reported (too much perf cost) - we only say it is between the start and end time. It is possible to go more precise, at the cost of more perf.

The data model has some pictures (Histograms and Sums), which is aligned with my proposal - the actual recordings occur somewhere between t1 and t2. 
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#histogram

Anyway, I'll send a PR with the change.

**Comment by lalitb** [comment]
Just to be clear, start-time could be moved up, and end-time/aggregation-time would remain in data point - is it so?

https://github.com/open-telemetry/opentelemetry-proto/blob/9d139c87b52669a3e2825b835dd828b57a455a55/opentelemetry/proto/metrics/v1/metrics.proto#L156C1-L157C17

// Data points with the 0 value for TimeUnixNano SHOULD be rejected
// by consumers.
