### ISSUE TITLE
[Bug]: Span kind is always set to "internal" in v0.22.0

### ISSUE THREAD

**Issue by frigus02** [open-telemetry/opentelemetry-rust#1575]
### What happened?

SpanKind is no longer reported correctly to exporters. It's always set to SpanKind::Internal.

To reproduce, change opentelemetry-stdout/examples/basic.rs:

```diff
     let tracer = tracer_provider.tracer("stdout-test");
-    let mut span = tracer.start("test_span");
+    let mut span = tracer.span_builder("test_span").with_kind(opentelemetry::trace::SpanKind::Server).start(&tracer);
     span.set_attribute(KeyValue::new("test_key", "test_value"));
```

In version 0.21.0, the exporter logs the specified kind. In 0.22.0, it always logs `"kind":1` ([i.e. internal](https://github.com/open-telemetry/opentelemetry-rust/blob/ab9415a8cd8b288d985e94a2482e261e9941ed9f/opentelemetry-stdout/src/trace/transform.rs#L125)).

I believe the issue is that `build_with_context` takes the span kind out of the span builder:

https://github.com/open-telemetry/opentelemetry-rust/blob/ab9415a8cd8b288d985e94a2482e261e9941ed9f/opentelemetry-sdk/src/trace/tracer.rs#L193

It then passes the builder to `build_recording_span`, which tries to take it out again:

https://github.com/open-telemetry/opentelemetry-rust/blob/ab9415a8cd8b288d985e94a2482e261e9941ed9f/opentelemetry-sdk/src/trace/tracer.rs#L149

### API Version

0.22.0

### SDK Version

0.22.0

### What Exporters are you seeing the problem on?

N/A

**Comment by cijothomas** [comment]
Thanks for trying the new release and reporting the bug. Yes, it is a pretty bad bug! Exposes big testing gaps. Sorry about that, will likely need a ".1" release, given this is a regression of a core capability.

**Comment by frigus02** [comment]
It happens. Thanks for the quick fix, Cijo.

I agree, a point release would be great. I don't think I can release an update for opentelemetry-application-insights without that. It just depends too much on the span kind. That's also why it has tests that caught this. 🙂

**Comment by cijothomas** [comment]
> opentelemetry-application-insights without that. It just depends too much on the span kind.e

Oh yes! (my team also builds and maintains application insights clients and otel based exporters, though none for Rust outselves)
