### ISSUE TITLE
[Bug]:  OpenTelemetryTracingBridge is waiting a LoggerProvider

### ISSUE THREAD

**Issue by germankuber** [open-telemetry/opentelemetry-rust#1593]
### What happened?

new function on OpenTelemetryTracingBridge is waiting a LoggerProvider instead of Trace GlobalTracerProvider

### API Version

0.3.0

### SDK Version

0.3.0

### What Exporters are you seeing the problem on?

OTLP

**Comment by lalitb** [comment]
Please refer to the documentation here - https://crates.io/crates/opentelemetry-appender-tracing:

_A [Log Appender](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/glossary.md#log-appender--bridge) that bridges logs from the [tracing crate](https://tracing.rs/tracing/#events) to OpenTelemetry logs._

So it uses LoggerProvider.

**Comment by cijothomas** [comment]
@germankuber If there are suggestions to further improve the doc, please do let us know.
I'll close this issue now, given this is expected behavior.
