### ISSUE TITLE
Remove sampler interface from API

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#160]
It is an SDK-specific rather than API concern.

**Comment by siyopao** [comment]
Hi @jtescher. Does this mean move `api::Sampler` to `sdk::trace::sampler`? And if so, what would you like to rename the current concrete `sdk::trace::sampler::Sampler`?

**Comment by jtescher** [comment]
Yeah seems like the spec wants the trait to be moved to SDK, but not sure what the most common trait / impl naming convention should be here. Looking at std lib lots of traits are the same as the method name e.g. `ToString`, `AsRef`, `IntoIter`, etc.

Could do `pub trait ShouldSample` and `impl ShouldSample for Sampler`?

**Comment by siyopao** [comment]
Okay, cool. Thanks. I'll work with that.
