### ISSUE TITLE
[Bug]: the Meter::i64_histogram() api removed 

### ISSUE THREAD

**Issue by funArash** [open-telemetry/opentelemetry-rust#1602]
### What happened?

opentelemetry-0.22.0/src/metrics/meter.rs removed the `Meter::i64_histogram()` API

### API Version

0.22.0

### SDK Version

0.22.1

### What Exporters are you seeing the problem on?

OTLP

**Comment by lalitb** [comment]
As per the otel [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#histogram-operations) the histogram should only record non-negative values, so this API was removed in #1371.

**Comment by funArash** [comment]
Thanks for the quick response. 👍🏼
