### ISSUE TITLE
Add OTLP exporter

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#161]
See the spec change [here](https://github.com/open-telemetry/opentelemetry-specification/pull/699) for details.

**Comment by jtescher** [comment]
@awiede I can't assign you to this issue. You may have to interact with this repo before you can be assigned? (probably abuse prevention)

**Comment by awiede** [comment]
🤷 this works too

**Comment by jtescher** [comment]
Yep works now that you've commented 👍

**Comment by jtescher** [comment]
Resolved in #173
