### ISSUE TITLE
Add semantic convention constants module

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#162]
Add semantic conventions for [tracing](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions), [resources](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/resource/semantic_conventions), and [metrics](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/metrics/semantic_conventions).

**Comment by frigus02** [comment]
I would have happy to give this a go. Just want to check that I would go in the right direction. My thinking was to replicate the [semcov package from opentelemetry-go](https://github.com/open-telemetry/opentelemetry-go/tree/master/semconv).

That would mean creating a bunch of constant `Key`s in `semcov::trace` and `semcov::resource` modules. (Looks like semantic conventions for metrics are still work in progress.) And those would be usable like this:

```rust
use opentelemetry::sdk;
use opentelemetry::semcov;

sdk::Resource::new(vec![
    semcov::resource::SERVICE_NAME.string("my-service"),
    semcov::resource::SERVICE_NAMESPACE.string("my-namespace"),
])

tracer
    .span_builder("something")
    .with_attributes(vec![
        semcov::trace::ENDUSER_ID.string("marry"),
        semcov::trace::NET_PEER_NAME.string("example.com"),
        semcov::trace::NET_PEER_PORT.i64(80),
    ])
```

Does this look like it's going in the right direction?

**Comment by jtescher** [comment]
@frigus02 this seems reasonable, what do you think about going with the JS approach initially and make a new crate in this repo for the semantic conventions? Seems like there is a fair chance that these will undergo some churn so avoiding more breaking changes in the core otel crate would be nice. Could start with `opentelemetry_samantic_conventions::trace:: NET_PEER_NAME` and re-export under a different name from `opentelemetry` once naming choices have settled a bit?

**Comment by frigus02** [comment]
Yeah, I like the idea. I agree about the likely churn and avoiding breaking changes for the main crate.

I think in order to create `const` `Key`s, we need to add a `const fn` to `Key`. Is that correct? I suppose it's not too unreasonable to make that function public. Something like this for example:

```rust
impl Key {
    pub const fn from_lowercase_str(value: &'static str) -> Self {
        Key(Cow::Borrowed(value))
    }
}
```

**Comment by jtescher** [comment]
I think the const method is right, the method name is a bit tricky here to not be confusing. Have to differentiate this constructor from normal str conversion. Maybe `from_static`? or `from_static_str`? the lowercase part could possibly be a `debug_assert!` if the spec prohibits mixed case key names.

**Comment by frigus02** [comment]
Sounds good. I'm going to open a draft PR with the structure soon so we can see how it looks like.

The lowercase part probably doesn't matter, to be honest. I copied the function from an example I had lying around.

**Comment by frigus02** [comment]
The PR is up. I'm going to look for a way to copy the documentation for all the different attributes now 😄
