### ISSUE TITLE
Investigate Potential to bypass LogRecord cloning when emitting LogRecord to LogProcessor(s)

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-rust#1650]
https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/logs/log_emitter.rs#L210 This clone needs some rethinking. Currently, every processor, even the ones that can stream event directly will have to suffer from this clone cost. I think we should just pass ref to logrecord to processors, and if a processor wants to batch it, then it can do the clone and pay the cost. This should give a significant cost reduction.

_Originally posted by @cijothomas in https://github.com/open-telemetry/opentelemetry-rust/issues/1649#issuecomment-2026570453_

**Comment by cijothomas** [comment]
I meant to say - its best if we can do this, irrespective of the number of processors, not just optimize for the 1-processor scenario. Span current does the special case for single processor..But I think it should be possible to always pass ref or mut ref to processors.

**Comment by lalitb** [comment]
updated title accordingly.

**Comment by lalitb** [comment]
Ok, It was much simpler to add a special case to avoid LogData cloning in case of single processor ( I believe that would be the most common use-case). Have added that change as part of #1636  (as changes are closely tied to that PR). I can see vast improvement in stress test with that:

**Main branch**:
```
Number of threads: 8
Throughput: 16,356,200 iterations/sec
Throughput: 15,894,400 iterations/sec
Throughput: 16,018,200 iterations/sec
Throughput: 16,344,800 iterations/sec
PR branch: (with Resource propagation )
```

**PR branch: (with Resource propagation at startup)**:
```
Number of threads: 8
Throughput: 19,301,400 iterations/sec
Throughput: 19,789,000 iterations/sec
Throughput: 20,133,600 iterations/sec
Throughput: 19,763,000 iterations/sec
```

**PR branch: (with Resource propagation + avoid LogData clone for single processor)**
```
Number of threads: 8
Throughput: 28,997,800 iterations/sec
Throughput: 29,057,800 iterations/sec
Throughput: 28,755,800 iterations/sec
Throughput: 29,712,000 iterations/sec
```
