### ISSUE TITLE
[Bug]: Global metrics provider gets shutdown when local provider is dropped

### ISSUE THREAD

**Issue by bwalk-at-ibm** [open-telemetry/opentelemetry-rust#1661]
### What happened?

https://github.com/open-telemetry/opentelemetry-rust/pull/1623 introduced `Drop` implementation for `SdkMeterProvider` for proper shutdown semantics. This however introduced a bug with the preferred usage pattern like it is demonstrated in the [demo](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/examples/basic-otlp/src/main.rs).

Here's what I assume happens: when building the metrics provider [we register a copy of the provider](https://github.com/open-telemetry/opentelemetry-rust/blob/d5392dc1df13b51553577a51d736eac9b29e7125/opentelemetry-otlp/src/metric.rs#L244) as the global metrics provider. The `SdkMeterProvider` holds references to the underlying data like the pipelines in an `Arc`, so this behaviour is all good. However, when *any* provider (like the original provider) is dropped (like it happens in the example code and which seems to be the expected pattern because it is encouraged to use the global metrics provider) and since `Drop` is implemented on the `SdkMeterProvider` will call `shutdown()` which will terminate the associated pipelines which are shared with the registered global metrics provider. Hence, we see no metrics and get an error when the global metrics provider gets dropped at application end.

### API Version

0.22

### SDK Version

0.22.1

### What Exporters are you seeing the problem on?

OTLP

**Comment by lalitb** [comment]
@bwalk-at-ibm Your analysis is correct. We shouldn't have `Drop` implemented for `SdkMeterProvider`.
One of the option could be to replace the existing code:

```rust
#[derive(Clone, Debug)]
pub struct SdkMeterProvider {
    pipes: Arc<Pipelines>,
    meters: Arc<Mutex<HashMap<Scope, Arc<SdkMeter>>>>,
    is_shutdown: Arc<AtomicBool>,
}
impl Drop for SdkMeterProvider {
    fn drop(&mut self) {
        if let Err(err) = self.shutdown() {
            global::handle_error(err);
        }
    }
}
```

with

```rust
#[derive(Clone, Debug)]
pub struct SdkMeterProvider {
    inner: Arc<SdkMeterProviderInner>,
}

pub struct SdkMeterProviderInner {
    pipes: Pipelines,
    meters: Mutex<HashMap<Scope, Arc<SdkMeter>>>,
    is_shutdown: AtomicBool,
}

impl Drop for SdkMeterProviderInner {
    fn drop(&mut self) {
        if let Err(err) = self.shutdown() {
            global::handle_error(err);
        }
    }
}
```

This will ensure that the shutdown is only invoked when all the references to `SdkMeterProvider` are dropped.

Apart from this, separate from this issue, we also need to discuss -

 -  The function opentelemetry_otlp::new_pipeline() call chain also sets the global static provider. Should it maintain this behavior, or should it be adjusted to simply create and return the provider/meter without modifying the static provider? This will get rid of cloning.
 
 - Should the convenience interface opentelemetry_otlp::new_pipeline() be removed altogether, and let the application use the standard way of creating the MeterProvider and Meters?
