### ISSUE TITLE
[Bug]: Cannot decode opentelemetry-collector exported trace data

### ISSUE THREAD

**Issue by caibirdme** [open-telemetry/opentelemetry-rust#1662]
### What happened?

I used the opentelemetry-collector(golang) to export the trace data into two files with different format(proto -> proto.log, json -> json.log), and Then I tried to use  the opentelemtry_proto crate(rust) to decode the exported data, but both reported Error:
```
// proto
DecodeError { description: "invalid tag value: 0", stack: [] }
// json
Error("invalid type: string \"1713099631002478000\", expected u64")
``` 

Steps to Reproduce:

```rust
// decode proto
use opentelemetry_proto::tonic::trace::v1::TracesData;
fn main() {
  decode_proto();
  decode_json();
}

fn decode_proto() {
    let content = std::fs::read("proto.log").unwrap();
    let w: TracesData = prost::Message::decode(content.as_slice()).unwrap(); // DecodeError { description: "invalid tag value: 0", stack: [] }
}

fn decode_json() {
    let content = std::fs::read("json.log").unwrap();
    let w: TracesData = serde_json::from_slice(content.as_slice()).unwrap(); // Error("invalid type: string \"1713099631002478000\", expected u64"
}
```

Then to generate the json and proto log file

1. Start a otel-collector: [opentelemetry-collector-contrib:v0.98](https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.98.0), here's the config file:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  file/proto:
    path: ./proto.log
    format: proto
  file/json:
    path: ./json.log
    format: json
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/proto, file/json]
```
start it to receive trace and write trace into two files: `./otelcol-contrib --config config.yaml`

2. Install [telemetrygen](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/telemetrygen) to produce one trace data:
```
go install github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen@latest

// produce a trace and send it to collector(default:  :4317, collector listened)
telemetrygen traces --otlp-insecure --child-spans 1
```

3. these two log files are created (proto.log, json.log)

Run the rust code above, you can see the error

### API Version

0.5.0

### SDK Version

0.5.0

### What Exporters are you seeing the problem on?

N/A

### Relevant log output

```shell
json.log:

{"resourceSpans":[{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"telemetrygen"}}]},"scopeSpans":[{"scope":{"name":"telemetrygen"},"spans":[{"traceId":"19f73715f92355fa9d50701e67b3eccb","spanId":"8d0cb062d5dc97ee","parentSpanId":"f061362452234d00","name":"okey-dokey-0","kind":2,"startTimeUnixNano":"1713099631002478000","endTimeUnixNano":"1713099631002601000","attributes":[{"key":"net.peer.ip","value":{"stringValue":"1.2.3.4"}},{"key":"peer.service","value":{"stringValue":"telemetrygen-client"}}],"status":{}},{"traceId":"19f73715f92355fa9d50701e67b3eccb","spanId":"f061362452234d00","parentSpanId":"","name":"lets-go","kind":3,"startTimeUnixNano":"1713099631002478000","endTimeUnixNano":"1713099631002601000","attributes":[{"key":"net.peer.ip","value":{"stringValue":"1.2.3.4"}},{"key":"peer.service","value":{"stringValue":"telemetrygen-server"}}],"status":{}}]}],"schemaUrl":"https://opentelemetry.io/schemas/1.4.0"}]}
```

**Comment by lalitb** [comment]
```json
"startTimeUnixNano":"1713099631002478000"
```

@caibirdme  - This seems to be incorrect in json.log? The span start time should be 64 bit integer as per the proto [specs](https://github.com/open-telemetry/opentelemetry-proto/blob/342e1d4c3a1fe43312823ffb53bd38327f263059/opentelemetry/proto/trace/v1/trace.proto#L189).

You may have to check the otel collector `file/json` exporter on why it is encoding it as string ?

**Comment by caibirdme** [comment]
According to protobuf definition, [int64,fixed64,uint64 will be serialized into string in json](https://protobuf.dev/programming-guides/proto3/#json)
