### ISSUE TITLE
Revisit shutdown_signal_provider methods at API level

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-rust#1679]
I think we need to revisit `shutdown_*_provider` methods as they are at the API level. The instrumented libraries shouldn't have the method to shutdown the LoggerProvider enabled by the application.

_Originally posted by @lalitb in https://github.com/open-telemetry/opentelemetry-rust/pull/1643#discussion_r1576473716_

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/pull/1643#discussion_r1579840322 We may be able to this entirely at API level, for the logging signal. (still need it/similar capability for metrics,traces)

**Comment by TommyCpp** [comment]
> We may be able to this entirely at API level

To clearify you mean remove shutdown, get logger, get logger provider, set logger provider entirely for logging signal?

**Comment by cijothomas** [comment]
For v0.23 release:
This is not an issue for logs, as logs removed the global shutdown completely.
Not an issue for traces, as global shutdown existed even before this release.
For metrics, this is newly introduced in v0.23. An example on how to shutdown even without the global_shutdown : https://github.com/open-telemetry/opentelemetry-rust/pull/1739
