### ISSUE TITLE
Add configuration options from environment variables

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#168]
See the [spec change](https://github.com/open-telemetry/opentelemetry-specification/pull/666) and [the followup](https://github.com/open-telemetry/opentelemetry-specification/pull/758) for details.

**Comment by ozerovandrei** [comment]
Note that OTLP Exporter spec was updated: [exporter.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md)
