### ISSUE TITLE
[Feature]: Add `add_link`

### ISSUE THREAD

**Issue by mladedav** [open-telemetry/opentelemetry-rust#1687]
### Related Problems?

Currently, links cannot be added to started spans.

#7 removed the method on a `Span` because it cited the spec as saying links can be added only during creation.

[The doc](https://github.com/open-telemetry/opentelemetry-specification/blob/6af1448a3a822d3c952ca5eb8189c68605aecad1/specification/trace/api.md#add-link) now has it as a part of its stable API.

### Describe the solution you'd like:

Add the method back.

### Additional Context

The linked issue which removed the method also citied [similar issue in go](https://github.com/open-telemetry/opentelemetry-go/issues/329), but they have since [added it back](https://github.com/open-telemetry/opentelemetry-go/issues/3919). The latter issue has some context.

**Comment by lalitb** [comment]
This has been added back as part of #1515

**Comment by TommyCpp** [comment]
Close as completed
