### ISSUE TITLE
[Feature]: Support attribute Value variants for KeyValueList and bytes

### ISSUE THREAD

**Issue by gen-xu** [open-telemetry/opentelemetry-rust#1723]
### Related Problems?

[otlp protobuf ](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/common/v1/common.proto#L37) for value variants has `KeyValueList` and `bytes` variants 
```protobuf
message AnyValue {
  // The value is one of the listed fields. It is valid for all values to be unspecified
  // in which case this AnyValue is considered to be "empty".
  oneof value {
    string string_value = 1;
    bool bool_value = 2;
    int64 int_value = 3;
    double double_value = 4;
    ArrayValue array_value = 5;
    KeyValueList kvlist_value = 6;
    bytes bytes_value = 7;
  }
}
```
while the [`opentelemetry::Value`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/common.rs#L244) only supports up to the `Array` variants
```rust
#[derive(Clone, Debug, PartialEq)]
pub enum Value {
    /// bool values
    Bool(bool),
    /// i64 values
    I64(i64),
    /// f64 values
    F64(f64),
    /// String values
    String(StringValue),
    /// Array of homogeneous values
    Array(Array),
}
```

Consider adding support for `KeyValueList` and  `bytes` support?

### Describe the solution you'd like:

Something like this? Admittedly the `Vec<>` may be wrapped with enum variants for slice to eliminate the need of copy in some scenarios
```rust
#[derive(Clone, Debug, PartialEq)]
pub enum Value {
    /// bool values
    Bool(bool),
    /// i64 values
    I64(i64),
    /// f64 values
    F64(f64),
    /// String values
    String(StringValue),
    /// Array of homogeneous values
    Array(Array),
    /// Key-Value list
    KeyValueList(Vec<KeyValue>),
    /// Bytes
    Bytes(Vec<u8>)
}
```

**Comment by lalitb** [comment]
As I understand, there are two separate `value` types defined in the specs:
1. As defined for standard set of attributes [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute). These are used in traces, metrics and resources.

   ```
   The attribute value is either:
   A primitive type: string, boolean, double precision floating point (IEEE 754-1985) or signed 64 bit integer.
   An array of primitive type values. The array MUST be homogeneous, i.e., it MUST NOT contain values of different types.
   ```
    `otel-rust` implements it as [Value](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/common.rs#L244)



2. As defined for log-attributes, and log-body [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#type-any):
   ```
   Type any
   Value of type any can be one of the following:

   A scalar value: string, boolean, signed 64 bit integer, or double precision floating point (IEEE 754-1985)

   A byte array,

   An array (a list) of any values,

   A map<string, any>,

   [since 1.31.0] An empty value (e.g. null).
   ```
   `otel-rust` implements it as [AnyValue](https://github.com/open-telemetry/opentelemetry-rust/blob/60a3cbe8c8f5278892004bf41b15361f222dc3c2/opentelemetry/src/logs/record.rs#L40). This is superset of attribute value in 1 above.

My best guess is that otel-proto uses only one type (the superset one) for all the scenarios.

**Comment by gen-nimble** [comment]
Thanks for the reply and direct me to the spec! I didn't realize the log attributes value has a different spec than the standart one, or more specifically it's intended for OTLP to be more expressive / as a superset to the Otel spec as mentioned in [this](https://github.com/open-telemetry/opentelemetry-specification/issues/2581) issue.
I guess we can close this issue then.
