### ISSUE TITLE
opentelemetry-stdout to have all features

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1732]
Currently stdout exporter has [feature flags for logs,metric and traces](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-stdout/Cargo.toml#L18-L21).
Given this crate is primarily for learning purposes, proposing to remove the feature flags from this crate.

**Comment by TommyCpp** [comment]
We can make all three default but keep the feature by signal. In case someone only want to enable one or two signal. Also a good practice on how to choose signal as API and SDK will have the similar issue
