### ISSUE TITLE
Tracer does weak->Arc upgrade twice in hot path leading to bottleneck

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1801]
`Tracer` holds a weakref to its `TracerProvider` and attempts to [upgrade that to an `Arc`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/trace/tracer.rs#L59) *twice* in the hot path - one during span start and then again during span end. This is affecting throughput due to contention.

This issue is already [fixed for Logs](https://github.com/open-telemetry/opentelemetry-rust/issues/1209), opening a new issue to track fixing the same for traces.

**Comment by TommyCpp** [comment]
1. Make the span processor shutdown from any reference #1836 
2. Add `shutdown` to sdk tracer provider
3. Remove `global::shutdown_global_tracer_provider`
4. Now tracer provider can take a `TracerProviderInner` Arc pointer.

**Comment by cijothomas** [comment]
This is done. Closing the issue.
