### ISSUE TITLE
Switch to noop propagators as default global propagator

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#181]
See the [spec change](https://github.com/open-telemetry/opentelemetry-specification/pull/719) for details. Note the section on span context propagation as well.

**Comment by frigus02** [comment]
For anyone else reading, the change to make global propagators noop is here: https://github.com/open-telemetry/opentelemetry-specification/pull/721. It's not merged into the spec, yet.

**Comment by frigus02** [comment]
I think this is now replaced by #221

**Comment by jtescher** [comment]
thanks @frigus02
