### ISSUE TITLE
Add metrics aggregation tests to ensure correctness

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1817]
The [current tests](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/metrics/mod.rs#L164-L176) are only covering Counters.

We need to replicate the same for all instruments. 
Multi-threaded tests are nice to have, but not a must before beta.

**Comment by utpilla** [comment]
I would like to take this up.

**Comment by cijothomas** [comment]
Thanks! Assigned. Lack of test is giving me less confidence to do big refactoring to get perf boost. For now I'll focus on Counters, which do have some coverage.

**Comment by cijothomas** [comment]
Closing as we have this mostly covered.
