### ISSUE TITLE
opentelemetry-otlp dependencies need higher msrv

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1827]
From https://github.com/open-telemetry/opentelemetry-rust/pull/1826

Running msrv check for opentelemetry-otlp package
 Downloading crates ...
  Downloaded async-stream v0.3.5
  Downloaded base64 v0.21.7
  Downloaded axum v0.6.20
  Downloaded crc32fast v1.4.2
  Downloaded flate2 v1.0.30
  Downloaded hashbrown v0.14.5
  Downloaded either v1.12.0
  Downloaded axum-core v0.3.4
  Downloaded equivalent v1.0.1
  Downloaded indexmap v1.9.3
  Downloaded httpdate v1.0.3
  Downloaded async-stream-impl v0.3.5
  Downloaded matchit v0.7.3
  Downloaded hyper-rustls v0.24.2
  Downloaded subtle v2.5.0
  Downloaded hex v0.4.3
  Downloaded http-body v0.4.6
  Downloaded adler v1.0.2
  Downloaded tokio-io-timeout v1.2.0
  Downloaded mime v0.3.17
  Downloaded cc v1.0.98
  Downloaded want v0.3.1
  Downloaded sync_wrapper v0.1.2
  Downloaded tower-service v0.3.2
  Downloaded openssl-probe v0.1.5
  Downloaded try-lock v0.2.5
  Downloaded zeroize v1.7.0
  Downloaded httparse v1.8.0
  Downloaded pin-project-internal v1.1.5
  Downloaded untrusted v0.9.0
  Downloaded pin-project v1.1.5
  Downloaded prost v0.12.6
  Downloaded base64 v0.22.1
  Downloaded anyhow v1.0.86
  Downloaded prost-derive v0.12.6
  Downloaded tracing-attributes v0.1.27
  Downloaded spin v0.9.8
  Downloaded ipnet v2.9.0
  Downloaded tokio-rustls v0.24.1
  Downloaded rustls-pki-types v1.7.0
  Downloaded miniz_oxide v0.7.3
  Downloaded tokio-rustls v0.25.0
  Downloaded rustls-pemfile v1.0.4
  Downloaded indexmap v2.2.6
  Downloaded hashbrown v0.12.3
  Downloaded rustls-native-certs v0.7.0
  Downloaded tower-layer v0.3.2
  Downloaded itertools v0.12.1
  Downloaded serde_urlencoded v0.7.1
  Downloaded hyper-timeout v0.4.1
  Downloaded rustls-native-certs v0.6.3
  Downloaded h2 v0.3.26
  Downloaded rustversion v1.0.17
  Downloaded rustls-pemfile v2.1.2
  Downloaded sct v0.7.1
  Downloaded reqwest v0.11.27
  Downloaded hyper v0.14.28
  Downloaded tonic v0.11.0
  Downloaded tower v0.4.13
  Downloaded webpki-roots v0.26.1
  Downloaded webpki-roots v0.25.4
  Downloaded tokio-util v0.7.11
  Downloaded rustls-webpki v0.101.7
  Downloaded rustls v0.21.12
  Downloaded rustls-webpki v0.102.4
  Downloaded rustls v0.22.4
  Downloaded encoding_rs v0.8.34
  Downloaded ring v0.17.8
error: package `prost-derive v0.12.6` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.65.0
Either upgrade to rustc 1.70 or newer, or use
cargo update -p prost-derive@0.12.6 --precise ver
where `ver` is the latest version of `prost-derive` supporting rustc 1.65.0

**Comment by lalitb** [comment]
Had a quick look. Both tonic and prost have 1.70.0 as `msrv`, so we do need to bump OpenTelemetry `msrv` too. We have been bumping the `msrv` for all creates within OpenTelemetry together. Should we continue following this, or only bump for `otel-proto` and `otel-otlp`? Just to add:
- `tokio-rs/tracing` and `tokio-rs/tokio` are on 1.63 (if that should be consideration)
- Debian stable comes with (default) [1.63 rustc version](https://tracker.debian.org/pkg/rustc).

**Comment by cijothomas** [comment]
1.70 has released on June 2023, ~ 1 year ago. We should be okay to bump our msrv to 1.70, but given tokio/tracing, debian is less aggresive, we should wait more.

5/28 SIG Call:
Bump to 1.70 for otlp alone, to not affect every OTel Rust users. And modify CI to check msrv separately for OTLP.
