### ISSUE TITLE
OTLPExporter msrv check in CI

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1863]
https://github.com/open-telemetry/opentelemetry-rust/pull/1840/files has explicitly updgraded msrv for otlp exporter. But the CI check is not checking this for OTLP exporter now.

https://github.com/open-telemetry/opentelemetry-rust/blob/main/scripts/msrv.sh#L14-L17

Opening an issue to track adding the msrv check for otlp. It could be done via an env variable to control the version or other ideas are welcome.

**Comment by lalitb** [comment]
Do we need to bump msrv for opentelemetry-proto too, as that too depends on tonic and prost?

**Comment by cijothomas** [comment]
closed via https://github.com/open-telemetry/opentelemetry-rust/pull/1864
