### ISSUE TITLE
[Feature]: Support `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` env var

### ISSUE THREAD

**Issue by Mossaka** [open-telemetry/opentelemetry-rust#1892]
### Related Problems?

This environment variable is a standardized OTLP env var defined in https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_traces_endpoint

In addition, this request to make `OTEL_EXPORTER_OTLP_PROTOCOL_HTTP_PROTOBUF` `OTEL_EXPORTER_OTLP_PROTOCOL_GRPC`, and `OTEL_EXPORTER_OTLP_PROTOCOL_HTTP_JSON` public

### Describe the solution you'd like:

The opentelemetry_otlp crate should support this environment variable

**Comment by lalitb** [comment]
Isn’t [OTEL_EXPORTER_OTLP_TRACES_ENDPOINT ](https://github.com/open-telemetry/opentelemetry-rust/blob/e0fb7fe3b7ab343cdf2f702b04d04976dc5542ca/opentelemetry-otlp/src/span.rs#L26) already supported ?

**Comment by lalitb** [comment]
@Mossaka please see above comment if this issue is good to close, as all three mentioned env variables are supported?

**Comment by Mossaka** [comment]
Yes, my bad please close it

**Comment by object88** [comment]
I realize that this is a smaller part of this issue, but can these:
```
const OTEL_EXPORTER_OTLP_PROTOCOL_HTTP_PROTOBUF: &str = "http/protobuf";
const OTEL_EXPORTER_OTLP_PROTOCOL_GRPC: &str = "grpc";
const OTEL_EXPORTER_OTLP_PROTOCOL_HTTP_JSON: &str = "http/json";
```
be made public?  There are a lot of great constants, and it feels like they would be useful when I'm writing by code.  Thanks!
