### ISSUE TITLE
LogRecord Attributes - preallocate attributes vec?

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1896]
![image](https://github.com/open-telemetry/opentelemetry-rust/assets/5232798/9f4e85bb-10aa-4b41-98be-6e9ce1b5113a)
Since we don't pre-allocate, the vec starts with size 1, and often requires re-allocating. Would we start with a default size of, say 5? 
(don't ask me why 5, just a magic number!)

Opening an issue to track this improvement. The change can improve current throughput, benchmark by 10-20% (as they all need ~5 attributes.)

**Comment by lalitb** [comment]
Thanks, let's track this potential improvement with benchmark of both memory and throughput while handling this.

**Comment by cijothomas** [comment]
From 7/2 SIG meeting:
Start with default = 8. 
In future, we can make it configurable, if we chose to and there is demand.
