### ISSUE TITLE
CI msrv check failure

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-rust#1915]
https://github.com/open-telemetry/opentelemetry-rust/actions/runs/9844926143/job/27179358230?pr=1913

error: package `cc v1.0.106` cannot be built because it requires rustc 1.67 or newer, while the currently active rustc version is 1.65.0
Either upgrade to rustc 1.67 or newer, or use
cargo update -p cc@1.0.106 --precise ver
where `ver` is the latest version of `cc` supporting rustc 1.65.0

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/pull/1674/files seem to be fixing it. If not ,lets fix it separately.

**Comment by lalitb** [comment]
old issue, so closing. The CI is successful currently.
