### ISSUE TITLE
LogExporter need vec of LogRecord?

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1919]
`LogProcessor` is forced to construct a Vec to pass the `LogRecord` to the Exporter (because Exporter's exporter method expects Vec), thereby requiring heap allocation.
https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/logs/log_processor.rs#L104

For sync exporters like etw, the heap allocation is not required, but SDK currently forces it.

Opening an issue to track addressing this. Options include having the exporter take a slice or some iterator so internal implementation details is not required to be exposed, but also can avoid the heap allocation.

**Comment by Might1331** [comment]
Hey there, can I pick this up ? FYI: I am not a contributor for this project as of now.

**Comment by lalitb** [comment]
@Might1331  Yes please. Thanks.

**Comment by lalitb** [comment]
@cijothomas We are not targeting this for beta right?

**Comment by cijothomas** [comment]
> @cijothomas We are not targeting this for beta right?

correct!

**Comment by cijothomas** [comment]
> Hey there, can I pick this up ? FYI: I am not a contributor for this project as of now.

Happy to get more contributions! All are welcome to contribute, but there is a CLA (legal agreement) to be signed. Once you send a PR, github will show you the process. It is straightforward mostly. If you are working on behalf of your employer, you'd want to consult your employer before signing CLA.

https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md#how-to-send-pull-requests

**Comment by Might1331** [comment]
Gotcha, thank you very much. Went through the "Contributing.md" doc. Will raise a PR soon. Thanks again

**Comment by Might1331** [comment]
@cijothomas Is there a common channel where I can ask for doubts with setting up the project locally. Specifically, There is not much description for the "Prerequisites to build the protocol compiler protoc from source" section.

**Comment by lalitb** [comment]
@Might1331 You won't need to build from source if you are using newer Linux distros (e.g. ubuntu 22.04 or higher). The default protobuf version from their internal registry should work fine. 

To build from source: https://github.com/protocolbuffers/protobuf/tree/main/src

For discussions, we use Github discussions, or otel-rust channel in [slack's cncf workspace.](https://slack.cncf.io/).

**Comment by lalitb** [comment]
@Might1331 Wondering if you are able to troubleshoot the protoc compiler issue mentioned above, Let me know if you need any help further in this issue.

**Comment by Might1331** [comment]
Need some more time to setup on my windows environment, will resume this weekend.

**Comment by Might1331** [comment]
@lalitb Getting following when attempting to push my branch
```
PS C:\Users\prata\OneDrive\Desktop\rust\opentelemetry-rust> git push origin logProcessorOptimization
remote: Permission to open-telemetry/opentelemetry-rust.git denied to Might1331.
fatal: unable to access 'https://github.com/open-telemetry/opentelemetry-rust/': The requested URL returned error: 403
```
Could you please help me get access to push my branch ? Followed the contribution.md doc

**Comment by lalitb** [comment]
@Might1331 Do you still have the issues?  Ensure that the ssh keys are configured correctly in you local setup - https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
