### ISSUE TITLE
LogRecord Attributes - avoid heap allocations

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1920]
We recently decided to [pre-allocate up to 8](https://github.com/open-telemetry/opentelemetry-rust/pull/1908) attributes, to avoid reallocation/copy costs, but attributes are still always on the heap. 
Opening an issue to track improving this, so that, up to 8 attributes can be stack allocated, and then fallback to heap for more attributes. This, along with https://github.com/open-telemetry/opentelemetry-rust/issues/1919, allow one to write logs without any allocation when using synchronous exporters like etw/user_events that require no batching.

We could add a dependency on [SmallVec](https://docs.rs/smallvec/) or make a home-grown solution. For an example implementation, [.NET's `TagList`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/TagList.netcore.cs) can be referred, which optimizes for up to 8 attributes.

We may need a feature flag to control this, as some scenarios (eg: Kernel mode) has less stack available.

**Comment by lalitb** [comment]
fixed in #1965 . The feature flag as discussed in #2055 would be added as required. Will create a separate issue for supporting kernel mode applications.
