### ISSUE TITLE
Pre-beta release with performance improvements?

### ISSUE THREAD

**Issue by jaemk** [open-telemetry/opentelemetry-rust#1930]
### Describe the solution you'd like:

Would it be possible to get a pre-beta release containing the recent performance improvements from #1833 ? I understand there are a number of unreleased breaking changes, but it would be great to have the improvements available without having to build from a fork. Thanks!

**Comment by cijothomas** [comment]
We plan to do a release today. Metrics will still remain alpha in this release, but logs are moving to beta.
(Metrics beta with more improvements was originally planned for this release, but is delayed by few more weeks.)

**Comment by jaemk** [comment]
Thanks @cijothomas! Something to expect in the next few days?
