### ISSUE TITLE
[Bug]:  opentelemetry-prometheus can not be used with latest opentelemetry

### ISSUE THREAD

**Issue by ttys3** [open-telemetry/opentelemetry-rust#1950]
### What happened?

opentelemetry-prometheus can not be used with latest opentelemetry (0.24)

I see https://github.com/open-telemetry/opentelemetry-rust/pull/1932 , do not know why update all others but exclude opentelemetry-prometheus ?

### API Version

0.24

### SDK Version

0.24

### What Exporter(s) are you seeing the problem on?

Prometheus

### Relevant log output

```shell
compliation failed:


error[E0277]: the trait bound `PrometheusExporter: MetricReader` is not satisfied
   --> src/telemetry.rs:63:22
    |
63  |         .with_reader(reader)
    |          ----------- ^^^^^^ the trait `MetricReader` is not implemented for `PrometheusExporter`
    |          |
    |          required by a bound introduced by this call
    |
    = help: the following other types implement trait `MetricReader`:
              ManualReader
              PeriodicReader
note: required by a bound in `MeterProviderBuilder::with_reader`
   --> xxxx/opentelemetry_sdk-0.24.1/src/metrics/meter_provider.rs:205:27
```
```

**Comment by sbernauer** [comment]
I'm also running into it. We could raise a PR bumping to opentelemetry 0.24, but I'm not really sure if it will be accepted, given https://github.com/open-telemetry/opentelemetry-rust/pull/1792 said

> Also removed opentelemetry-prometheus from CI for now, as it is not planned for the upcoming release : https://github.com/open-telemetry/opentelemetry-rust/issues/1719

**Comment by sbernauer** [comment]
I guess let's just give it a try :) I did the needed changes and created https://github.com/open-telemetry/opentelemetry-rust/pull/1957

Tested them using the following Cargo.toml and it seems to work
```
[patch.crates-io]
opentelemetry-prometheus = { git = "https://github.com/sbernauer/opentelemetry-rust", branch = "feat/otel-prom-0.17.0" }
```

**Comment by ttys3** [comment]
@sbernauer wow, I also [made a workaround](https://github.com/ttys3/opentelemetry-rust/commit/e51611edcc340b2673b86b60daf3c3ccf7fd0b0c) 2 days ago

```toml
[patch.crates-io]
opentelemetry-prometheus = { git="https://github.com/ttys3/opentelemetry-rust.git", branch="opentelemetry-prometheus-sdk-0.24" }
```
