### ISSUE TITLE
[Bug]: `opentelemetry-otlp/examples/basic-otlp-http` doesn't work with `otel/opentelemetry-collector:latest`

### ISSUE THREAD

**Issue by saxon-parker** [open-telemetry/opentelemetry-rust#1958]
### What happened?

The `opentelemetry-otlp/examples/basic-otlp-http` example doesn't work with the collector image `otel/opentelemetry-collector:latest`

Trying specific version of the otel collector, the example does work with `otel/opentelemetry-collector:0.103.0`, but fails with tag `otel/opentelemetry-collector:0.104.0` and later.

Similarly, trying the [`jaegertracing/all-in-one` container](https://hub.docker.com/r/jaegertracing/all-in-one) as the collector, the example will work with up tag `1.58`, but fails with tag `1.59` and later.

### API Version

0.24.0

### SDK Version

0.24.1

### What Exporter(s) are you seeing the problem on?

OTLP

### Relevant log output

```shell
OpenTelemetry trace error occurred. error sending request for url (http://localhost:4318/v1/traces)
Error: Other("[Other(reqwest::Error { kind: Request, url: Url { scheme: \"http\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"localhost\")), port: Some(4318), path: \"/v1/logs\", query: None, fragment: None }, source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(Io, Os { code: 104, kind: ConnectionReset, message: \"Connection reset by peer\" })) })]")



OpenTelemetry trace error occurred. error sending request for url (http://localhost:4318/v1/traces)
Error: Other("[Other(reqwest::Error { kind: Request, url: Url { scheme: \"http\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"localhost\")), port: Some(4318), path: \"/v1/logs\", query: None, fragment: None }, source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) })]")
```

**Comment by ewoolsey** [comment]
I'm seeing the same thing.
