### ISSUE TITLE
[Bug]: OpenTelemetry trace and log error when executing otlp example.

### ISSUE THREAD

**Issue by Taxalo** [open-telemetry/opentelemetry-rust#1967]
### What happened?

If you are using jaeger 1.59.0 and try to execute the opentelemetry-otlp basic-otlp example an error will apear with, saying `stream closed because of a broken pipe`.

```rs
OpenTelemetry log error occurred. Exporter otlp encountered the following errors: the grpc server returns error (Unknown error): , detailed error message: transport error tonic::transport::Error(Transport, hyper::Error(Io, Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }))
OpenTelemetry trace error occurred. Exporter otlp encountered the following error(s): the grpc server returns error (Unknown error): , detailed error message: transport error tonic::transport::Error(Transport, hyper::Error(Io, Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }))
Error: Other("[ExportErr(Status { code: Unknown, message: \", detailed error message: transport error tonic::transport::Error(Transport, hyper::Error(Io, Custom { kind: BrokenPipe, error: \\\"stream closed because of a broken pipe\\\" }))\" })]")
``` 

If you are using jaeger 1.58.0, it will return another error:

```rs
OpenTelemetry log error occurred. Exporter otlp encountered the following errors: the grpc server returns error (Operation is not implemented or not supported): , detailed error message: unknown service opentelemetry.proto.collector.logs.v1.LogsService
Error: Other("[ExportErr(Status { code: Unimplemented, message: \", detailed error message: unknown service opentelemetry.proto.collector.metrics.v1.MetricsService\" })]")
```

This seems to happen when doing a shutdown of meter_provider.

This same issue was reported to tracing-opentelemetry (https://github.com/tokio-rs/tracing-opentelemetry/issues/157) because their example also fails 

### API Version

0.24.0

### SDK Version

0.24.1

### What Exporter(s) are you seeing the problem on?

Jaeger

**Comment by lalitb** [comment]
@Taxalo Are you trying the example against jaeger-all-in-one collector? The existing example only tests against otel-collector, which works fine.

**Comment by Taxalo** [comment]
I am trying with jaeger-all-in-one, correct. 

I understand that it should also work with jaeger, right?

**Comment by lalitb** [comment]
Can you try with bit older version of jaeger-all-in-one, good to know if it ever worked?

**Comment by czwinzscher** [comment]
This might be related to https://github.com/jaegertracing/jaeger/issues/5737

**Comment by Taxalo** [comment]
I have tried from jaeger 1.54 to 1.59. They do not work. Versions prior or equal to 1.58 return the second error I mentioned. Is this only on my end?

**Comment by czwinzscher** [comment]
Well the second error says that "Operation is not implemented or not supported". Afaik jaeger only supports traces but not logs and metrics. What happens when you comment out the logs and metrics exporters?
