### ISSUE TITLE
Need for Cow for 'static str?

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#2011]
SeverityText: https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/logs/record.rs#L28

Name(Added for storing Tracing's eventname as top-level field) : https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/logs/record.rs#L7

Target(Added for storing Tracing/Logs scope as top-level field) : https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/logs/record.rs#L17

We should be able to simplify the API to accept just &'static str instead of `Cow`. Opening an issue to see if there is any reasons why `Cow` was used for the above, and if not, remove the `Cow`.

**Comment by lalitb** [comment]
Thanks for raising the issue. From tracing_core::metadata:
https://github.com/tokio-rs/tracing/blob/527b4f66a604e7a6baa6aa7536428e3a303ba3c8/tracing-core/src/metadata.rs#L57
```rust
    /// The name of the span described by this metadata.
    name: &'static str,

    /// The part of the system that the span that this metadata describes
    /// occurred in.
    target: &'a str,
```
Atlease name can be of type `&static str.

**Comment by lalitb** [comment]
And also the severity-text - https://github.com/tokio-rs/tracing/blob/527b4f66a604e7a6baa6aa7536428e3a303ba3c8/tracing-core/src/metadata.rs#L527
```rust
    pub fn as_str(&self) -> &'static str {
        match *self {
            Level::TRACE => "TRACE",
            Level::DEBUG => "DEBUG",
            Level::INFO => "INFO",
            Level::WARN => "WARN",
            Level::ERROR => "ERROR",
        }
    }
```

**Comment by TommyCpp** [comment]
Just note that if we only allows `&'static str` then users can only use compling time value. i.e if I want to set the `event_name` to the user ID of the incoming request, I will not be able to if the `set_event_name` only accepts `&'static str`. 

I think we should keep `Cow` for any fields that may use runtime string value

**Comment by cijothomas** [comment]
> .e if I want to set the event_name to the user ID of the incoming request, I will not be able to if the set_event_name only accepts &'static str.

That is not the intent. EventName was promoted to top-level field in LogRecord to support `tracing` like scenarios only, where `eventname` should be known at compile time. UserId/others should be treated as normal attributes only.

(We expect to provide advanced filtering based on that in the future, and it is intentionally expected to be compile time only.)
