### ISSUE TITLE
[Feature]: Include fields from spans in logs generated by OpenTelemetryTracingBridge

### ISSUE THREAD

**Issue by lukasfri** [open-telemetry/opentelemetry-rust#2087]
### Describe the solution you'd like:

I'd like the log entries generated by `OpenTelemetryTracingBridge` (`opentelemetry-appender-tracing`) to include the fields-data in the spans which the event was emitted inside, similar to tracing-subscriber which does this with its fmt::layer() when used in the Full format ([source code](https://github.com/tokio-rs/tracing/blob/527b4f66a604e7a6baa6aa7536428e3a303ba3c8/tracing-subscriber/src/fmt/format/mod.rs#L974)).

### Considered Alternatives

You can simply repeat all the fields that are attached to the spans manually ofcourse, but this is hugely cumbersome and removes a large part of the nice ergonomics of tracing::instrument.

### Additional Context

Given the green light, I could maybe take a stab at it myself and submit a PR.

**Comment by cijothomas** [comment]
Can you elaborate more on this ask? Given Logs are correlated to Traces, attaching each attribute to every Log is very inefficient/costly.

**Comment by lukasfri** [comment]
> Can you elaborate more on this ask? Given Logs are correlated to Traces, attaching each attribute to every Log is very inefficient/costly.
@cijothomas 

I agree, my issue boiled down to the tracing log-events not being respected in instrumented functions (issue https://github.com/open-telemetry/opentelemetry-rust/issues/1378 ). I'll close this and simply wait for a solution to that issue instead/the proposal to turn opentelemetry-rust into a system built on tracing. Sorry for wasting your time!

**Comment by Yamakaky** [comment]
I have another usecase on this subject. The linked issue talks about correlating traces and logs. If we take for example a classic accept loop:
```rust
loop {
    let connection = accept();
    let span = info_span!("connection", client_ip = ...);
    span.in_scope(|| {
        info!("handling connection");
        handle(connection);
    });
}
```
In that case, `fmt::layer()` will print the client_ip with the log, but the OTEL logs will not include it. It could technically be recovered once trace correlation is working, but that's not very ergonomic (nor performant i assume). If adding all fields is too inefficient, is there a way to whitelist a few fields that would be copied from the trace?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/oteps/pull/207 A related proposal (which got stalled :( ...)

**Comment by Yamakaky** [comment]
I see. I guess for now having a manual processor would be fine. I assume you mean `LogProcessor` instead of `LogRecordProcessor`? Would a Layer work too?

**Comment by lalitb** [comment]
> It might be possible to achieve this with a LogRecordProcessor which can inspect current context and push additional attributes to the LogRecord. (This will also have challenges as there is common understanding on "Context" between OpenTelemetry and Tracing)

API to add/update the attributes is part of #2103.

**Comment by salimeid** [comment]
Trying to understand the PR and proposal being discussed here.

We have a similar scenario: we have a field which is set in the parent span and need the field to be added to every log emitted inside the span.

Propagating the field everywhere by manually adding it to logs is not going to be achievable.
