### ISSUE TITLE
Remove unnecessary public APIs for creating KeyValue structs

### ISSUE THREAD

**Issue by utpilla** [open-telemetry/opentelemetry-rust#2090]
We have an additional set of public APIs to create `KeyValue` struct apart from `KeyValue::new()`. These APIs don't offer anything additional in terms of feature or performance. They simply offer an alternative way to create `KeyValue` struct by creating the Key first and then the Value instead of having them created together.

I think we could remove these APIs just to keep our public API surface smaller. I'm opening this issue to check if anyone has any opinions on this.

https://github.com/open-telemetry/opentelemetry-rust/blob/66f29b876f4c5d0c1551c65e6d92d1ae2e6ea744/opentelemetry/src/common.rs#L36-L73

**Comment by cijothomas** [comment]
@TommyCpp Do you know if there is a strong reason why this should be kept?

**Comment by TommyCpp** [comment]
This is mostly for ergonomics. Maybe a better way is to implement `From<i64/f64>` for `Key`. Then user can use `KeyValue::new` directly because we ask for anything that `Into<Key>`

**Comment by utpilla** [comment]
Completed in #2091
