### ISSUE TITLE
[Bug]: Support tokio >1.38

### ISSUE THREAD

**Issue by amfaber** [open-telemetry/opentelemetry-rust#2094]
### What happened?

The opentelemetry project currently requires tokio "~1.38.0", as changed in this commit https://github.com/open-telemetry/opentelemetry-rust/commit/57bcd59989ecea1eca7b6b8c73dd87fddeb4e07c

The comment indicates that this is to not require a bump of OTel's msrv from 1.65 to 1.70.
However, this requirement prevents projects that want to use OTel's crates from using newer tokio versions, even if they have a rust version that is way newer than 1.70 (as is my case).

Perhaps the requirement could be reverted to just "1" to allow consumers to choose the tokio version, with some other workaround for CI? I am not sure what the best way forward is.

### API Version

0.24

### SDK Version

0.24

**Comment by lalitb** [comment]
We can do msrv patching specific to CI as done here - https://github.com/open-telemetry/opentelemetry-rust/pull/2081
@amfaber if you would like to contribute, else I can do this sometime this week.

**Comment by frederikhors** [comment]
```
cargo update
    Updating crates.io index
error: failed to select a version for `tokio`.
    ... required by package `opentelemetry_sdk v0.25.0`
    ... which satisfies dependency `opentelemetry_sdk = "^0.25.0"` of package `name v0.1.0`
    ... which satisfies path dependency `name` of package `app v0.1.0`
versions that meet the requirements `~1.38.0` are: 1.38.1, 1.38.0

all possible versions conflict with previously selected packages.

  previously selected package `tokio v1.40.0`
    ... which satisfies dependency `tokio = "^1.40.0"` of package `app v0.1.0`

failed to select a version for `tokio` which could resolve this conflict
```

**Comment by amfaber** [comment]
Incredible speed of resolution! Big ups and thank you 👍

**Comment by davidbarsky** [comment]
Commenting here because I had to help resolve a similar issue at work: it's generally not the best idea to have modifiers/operators in a Cargo.toml: checking in a `Cargo.lock` should be sufficient.

**Comment by aumetra** [comment]
Just out of curiosity, is there a patch release planned to release this?

**Comment by cijothomas** [comment]
No patch planned, as we are targeting to do the next release in ~3 weeks time. Given that there is release every ~3 weeks from now (till 1.0), do you really want a patch?

**Comment by frederikhors** [comment]
Why it is so difficult to release a patch?

**Comment by cijothomas** [comment]
> Why it is so difficult to release a patch?

We are not saying it is very difficult. There is some amount of work to be done to release patches. Trying to avoid it unless there is an actual demand to do so, given we plan more frequently releases going fwd.

If you really need a patch release, please reply and we can do that.

**Comment by cijothomas** [comment]
@aumetra @frederikhors @amfaber Please comment here and let us know if you need us to push a patch release with this change.

**Comment by amfaber** [comment]
No need from my side

**Comment by theduke** [comment]
Context: I have dependencies that require tokio 1.39+, because of the switch to mio v1.

**Comment by cijothomas** [comment]
> +1 Could you make a patch release for this please

0.26 release already includes this.
