### ISSUE TITLE
Span lifetime / active span state

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#21]
Currently spans are stored in a [thread local span stack](https://github.com/open-telemetry/opentelemetry-rust/blob/master/src/sdk/trace/tracer.rs#L32), and either manually added and removed via [mark_span_as_active](https://github.com/open-telemetry/opentelemetry-rust/blob/master/src/api/trace/tracer.rs#L78) / [mark_span_as_inactive](https://github.com/open-telemetry/opentelemetry-rust/blob/master/src/api/trace/tracer.rs#L91) or for the scope of a given closure by using  [with_span](https://github.com/open-telemetry/opentelemetry-rust/blob/master/src/api/trace/tracer.rs#L110).

This has certain drawbacks: spans marked as active and not later marked as inactive will not be dropped, marking as inactive is unexpected as it is not part of the spec, etc.

We should investigate if there are more reliable / intuitive / ergonomic ways of coordinating active span information between components. E.g. web framework middleware needing to set the active span for use later in the application.

**Comment by iredelmeier** [comment]
See also #15 (I think they're related but separate)

**Comment by jtescher** [comment]
Closing this in favor of #15
