### ISSUE TITLE
[Feature]: Allow setting TraceContext on opentelemetry::logs::LogRecord

### ISSUE THREAD

**Issue by KodrAus** [open-telemetry/opentelemetry-rust#2106]
### Describe the solution you'd like:

The new `opentelemetry::logs::LogRecord` trait supports a subset of the data on the `opentelemetry_sdk::logs::LogRecord` struct. One thing it's missing is the ability to set the `TraceContext`.

This is something I was using to ensure logs emitted via OpenTelemetry would include trace context, even if that context is not managed via OpenTelemetry itself. Since the `TraceContext` is optional, we should be able to tell when processing the resulting record whether the caller explicitly set a context, and fill it in with OpenTelemetry's current if not.

A method on `LogRecord` like `fn set_trace_context(&mut self, ctxt: TraceContext)` would cover my needs.

**Comment by lalitb** [comment]
Thanks @KodrAus. this seems valid. do you want to contribute the PR, as I would be able to pick this up sometime next week.

**Comment by KodrAus** [comment]
I’m happy to put a PR together for this 👍 I imagine at some point you’ll be locking down those traits so they can be stabilized.

**Comment by lalitb** [comment]
Thanks @KodrAus. Yes, we are targeting RC in Oct, so would have stable API by then,

**Comment by KodrAus** [comment]
I've opened #2129 for this.

As an aside, it was probably discussed somewhere, but I thought the API here was a little surprising. The `LogRecord` trait appears to mostly be setters for the `LogRecord` struct so am not sure why it's preferable over using the `LogRecord` struct itself. It seems like it could be a compatibility hazard going forwards, since you can't introduce new methods without breaking changes, a no-op or panicking default, or forcing additional trait bounds on users of the `Logger` trait to extend it. None of those options are really appealing in the long term. There could be some bigger plan here I'm missing though since I'm only a casual observer.
