### ISSUE TITLE
Add DDSketch aggregation support

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#212]
Existing crates: https://github.com/mheffner/rust-sketches-ddsketch

**Comment by TommyCpp** [comment]
Hm my question is do we want to implement our own version or should we just use the existing crates. I haven't got the chance to check the crates but it seems in early stage?

**Comment by jtescher** [comment]
@TommyCpp I haven't looked into the crate much, I guess whichever is easier to maintain, generally it's nice to have fewer dependencies but if this is complex enough then it makes sense to import

**Comment by TommyCpp** [comment]
Sounds good. Mind if I work on this? Could take a while since I'd love to read the paper to make sure we get the right implementation.

**Comment by jtescher** [comment]
Sounds good

**Comment by TommyCpp** [comment]
close via #218
