### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jerusdp** [open-telemetry/opentelemetry-rust#2136]
### What happened?

Blocked from updating opentelemetry_sdk from v0.24.1 to v0.25.0 by compatibility with latest tokio version (1.40.0)

### API Version

0.24.0
upgrading to 0.25.0

### SDK Version

0.24.1
upgrading to 0.25.0

### Relevant log output

```shell
error: failed to select a version for `tokio`.
    ... required by package `opentelemetry_sdk v0.25.0`
    ... which satisfies dependency `opentelemetry_sdk = "^0.25.0"` of package `ghdash v0.1.7 (/media/topleft/garden/ghdash)`
versions that meet the requirements `~1.38.0` are: 1.38.1, 1.38.0

all possible versions conflict with previously selected packages.

  previously selected package `tokio v1.40.0`
    ... which satisfies dependency `tokio = "^1.40.0"` of package `ghdash v0.1.7 (/media/topleft/garden/ghdash)`

failed to select a version for `tokio` which could resolve this conflict
```

**Comment by 4t145** [comment]
Same issue. I want to know what problems will occur if we use a tokio version higher than 1.38?

**Comment by lalitb** [comment]
Closing as this is fixed in main branch.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/issues/2144#issuecomment-2374344387
