### ISSUE TITLE
[Bug]: Locked to tokio version ~1.38.0

### ISSUE THREAD

**Issue by silesmo** [open-telemetry/opentelemetry-rust#2144]
### What happened?

Version 0.25.0 is locked to tokio version ~1.38.0 which disallows the use of tokio above version 1.38.1. The current release of tokio is version 1.40.0.

### API Version

0.25.0

### SDK Version

0.25.0

### Relevant log output

```shell
error: failed to select a version for `tokio`.
    ... required by package `opentelemetry_sdk v0.25.0`
    ... which satisfies dependency `opentelemetry_sdk = "^0.25.0"` of package 
versions that meet the requirements `~1.38.0` are: 1.38.1, 1.38.0

all possible versions conflict with previously selected packages.

  previously selected package `tokio v1.40.0`
    ... which satisfies dependency `tokio = "^1.40.0"` of package
```

**Comment by ymgyt** [comment]
FYI: https://github.com/open-telemetry/opentelemetry-rust/issues/2094

**Comment by cijothomas** [comment]
Thanks for reporting this. The fix is already in, and will be part of next release which is expected by Sep 30th.
