### ISSUE TITLE
Datadog Exporter

### ISSUE THREAD

**Issue by tustvold** [open-telemetry/opentelemetry-rust#216]
Datadog uses a custom trace export format defined [here](https://docs.datadoghq.com/api/v1/tracing/#send-traces). In addition to the JSON format documented there, official implementations use msgpack - see [here](https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/payload.go).

I have found the beginnings of a datadog exporter for the opentelemetry collector [here](https://github.com/DataDog/opentelemetry-collector-contrib/tree/master/exporter/datadogexporter) but it would be preferable for Rust applications to be able to export directly to DataDog.

I'd be happy to submit an implementation if this would be of interest

**Comment by jtescher** [comment]
@tustvold a few others have expressed the need for a DataDog exporter so I think this would be great! Could be added to the contrib repo here or in your own repo if you prefer.

**Comment by TommyCpp** [comment]
It would be nice if we can have some kind of links to those vendor component that not in contrib repo so that ppl can find what they want more easily

**Comment by jtescher** [comment]
@TommyCpp yeah very true. We could start a list in the main readme maybe? There is also https://opentelemetry.io/registry/ which tries to be a central repository across languages.
