### ISSUE TITLE
be able to send logs only of a specific target

### ISSUE THREAD

**Issue by vincenzopalazzo** [open-telemetry/opentelemetry-rust#2172]
### Discussed in https://github.com/open-telemetry/opentelemetry-rust/discussions/2162

<div type='discussions-op-text'>

<sup>Originally posted by **vincenzopalazzo** October  1, 2024</sup>
Currently, the log wrapper will send all the logs of all the crates, but sometimes, we want just collect logs for the crate we want, like `RUST_LOG=<crate>:debug,<crate>:info` 

It is possible to do it with the current the open telemetry log? or if there is another way can you point me to the right direction?</div>

**Comment by vincenzopalazzo** [comment]
>Are you using tracing or log crate?

I am using `log`

**Comment by lalitb** [comment]
You can create a separate logger to filter the specific logs you want, and chain that logger together with logger created by OpenTelemetryLogBridge. This will ensure that those filtered logs are not sent to the Otel. Something like this - https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=87bca189d636131a34e7adb8e1cace8e
