### ISSUE TITLE
[bug] cannot send message to batch processor as the channel is full

### ISSUE THREAD

**Issue by vincenzopalazzo** [open-telemetry/opentelemetry-rust#2177]
While running my server and collecting the logs with open telemetry, I keep receiving this error from time to time `OpenTelemetry log error occurred. cannot send message to the batch processor as the channel is full`

I was wondering why this error occurs, and if it is a bug.

FYI: this is the configuration that I am using the following library https://github.com/vincenzopalazzo/opentelemetry-log contains a simple configuration https://github.com/vincenzopalazzo/opentelemetry-log/blob/main/src/log.rs#L22

**Comment by cijothomas** [comment]
This is a valid message indicating you are producing logs at a faster rate than it gets exported. The current behavior is to drop, and not apply backpressure. You can increase max size of buffer, increase exporter frequency etc.
Sadly, not much documentation around these. Hoping to get them fixed soon.

**Comment by vincenzopalazzo** [comment]
Thanks @cijothomas

Can you point me to the documentation to lean more about these parameters?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/logs/log_processor.rs#L370-L373
