### ISSUE TITLE
Metric option configuration

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#22]
Current `MetricOptions` implementation does not work for [with_monotonic](https://github.com/open-telemetry/opentelemetry-rust/blob/master/src/api/metrics/mod.rs#L137). The issue is the options do not know which instrument they are being created for.

We could consider moving to returning builders instead of accepting all options here?

**Comment by iredelmeier** [comment]
The question of what to return seems similar to the current span situation, per #13 and #14. It would be nice to be able to use consistent patterns across both 🤞
