### ISSUE TITLE
Support OTEL_EXPORTER environment variable

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#220]
See the [spec change](https://github.com/open-telemetry/opentelemetry-specification/pull/943) for details.

**Comment by TommyCpp** [comment]
I think it's gonna be a tricky one. [The PR doesn't include support for external/vendor exporters](https://github.com/open-telemetry/opentelemetry-specification/pull/943#discussion_r489025356) but all our exporter feels like external exporters since they don't live in the main create.

**Comment by jtescher** [comment]
@TommyCpp yeah good point. Maybe we hold off on this one until we see if any other language implements this. Could look at what is available, or have another crate that depends on _all_ the standard exporters which adds this functionality, none of these seem like great options currently though.

**Comment by TommyCpp** [comment]
https://github.com/open-telemetry/opentelemetry-specification/issues/985 seems to conclude that this should be a optional env. If that's the case we could just don't implement it.

**Comment by jtescher** [comment]
@TommyCpp sounds good, closing for now. If folks want this we can re-open later.
