### ISSUE TITLE
`opentelemetry-otlp` documentation mentioning `tls-tonic` feature flag that does not exist

### ISSUE THREAD

**Issue by lochetti** [open-telemetry/opentelemetry-rust#2200]
At the feature flags section of the [documentation](https://docs.rs/opentelemetry-otlp/latest/opentelemetry_otlp/#feature-flags), the feature flag `tls-tonic` is mentioned, but when we look at the [available feature flags](https://docs.rs/crate/opentelemetry-otlp/latest/features) it does not exist at version 0.26.0.

So maybe it is just a matter of removing the bullet point that mentions `tls-tonic` from the documentation?

**Comment by lalitb** [comment]
@lochetti Thanks for raising the issue. If you would like to contribute the fix?
