### ISSUE TITLE
Update the default propagator to be noop

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#221]
See the [spec change](https://github.com/open-telemetry/opentelemetry-specification/pull/930) for details.

**Comment by morigs** [comment]
Do I understand correctly that the noop propagator has not yet been implemented?

And the main change is to replace composite propagator [here ](https://github.com/open-telemetry/opentelemetry-rust/blob/b47794e5818d7ba39115933ea7f752b8784cf025/src/global/propagation.rs#L11)with noop?

**Comment by frigus02** [comment]
Yes, that is exactly how I understand it as well. There is no NoopPropagator, yet. So we need to implement one. And we need to make the noop propagator the new default. The location you linked is correct.

**Comment by morigs** [comment]
Looking at the Go implementation. They [use ](https://github.com/open-telemetry/opentelemetry-go/blob/230bdd10f0d3a2d00eaebcb153a5341f0882548f/global/internal/propagator.go#L40)empty composite text map propagator
It seems this is possible with [current ](https://github.com/open-telemetry/opentelemetry-rust/blob/master/src/sdk/propagation/composite.rs)`CompositeTextMapPropagator` implementation

**Comment by frigus02** [comment]
Oh yes. That sounds good to me 👍
