### ISSUE TITLE
Export `otel.status_code` tag in Zipkin exporter

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#223]
See the [spec change](https://github.com/open-telemetry/opentelemetry-specification/pull/967) for details (may not be exported currently).

**Comment by danrusei** [comment]
can't the otel.status_code & otel.status_description be added to tags (into_zipkin_span function) ?

tags.insert("otel.status_code".into(), span_data.status_code.to_string());
tags.insert("otel.status_description".into(), span_data.status_message.clone());

Display has to be implemented for StatusCode enum.

**Comment by jtescher** [comment]
@danrusei yeah should be easy to add, I don't think that anything else needs to format status codes that way, I believe the other exports use the numeric values. Could just add a function from `StatusCode`  -> `&'static str` that formats the way zipkin expects maybe?

**Comment by jtescher** [comment]
Resolved in #236
