### ISSUE TITLE
Instrumentation Scope and cloning

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#2246]
Follow up to https://github.com/open-telemetry/opentelemetry-rust/pull/2220

I think we should remove the Cow, and make scope take owned versions. Scopes are created only very few times in the app, so there should not be perf concerns.
https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/common.rs#L422

if perf is a concern, we can make Instrumentation Scope be an Arc of InstrumentationScopeInner to make cloning cheap.

**Comment by cijothomas** [comment]
@stormshield-fabs I think you mentioned this in the PR but i am not able to locate that comment now! Can you help check if this cleanup is needed?

**Comment by cijothomas** [comment]
tagging for 0.27 as we want to avoid breaking changes after 0.27

**Comment by stormshield-fabs** [comment]
This was brought up in https://github.com/open-telemetry/opentelemetry-rust/pull/2220#discussion_r1810075412

**Comment by cijothomas** [comment]
> This was brought up in [#2220 (comment)](https://github.com/open-telemetry/opentelemetry-rust/pull/2220#discussion_r1810075412)

Thanks! I was searching for it, but wasn't able to locate easily!!
Would you be able to address this?
