### ISSUE TITLE
TraceProvider::with_exporter immediately drops BatchSpanProcessor

### ISSUE THREAD

**Issue by frigus02** [open-telemetry/opentelemetry-rust#225]
While testing #224, I came across an issue.

## Steps to reproduce

1. Checkout the PR (at the point of writing https://github.com/open-telemetry/opentelemetry-rust/pull/224/commits/ffa96df67008202b784b64d0986e255ffd26cac1).
1. Open `examples/stdout.rs` and change:
   ```diff
   + #[tokio::main]
   + async fn main() {
   - fn main() {
   ```
1. Run `cargo run --example stdout` and observe the span being printed to the console.
1. Run `cargo run --example stdout --features tokio` and observe that nothing is printed. With the tokio feature enabled it used the BatchSpanProcessor setup by TraceProvider::with_exporter.

## Analysis

I reproduced it on master as well and with a few print statements found that the `BatchSpanProcessorWorker` is immediately dropped after calling with_exporter.

See my experiments here: https://github.com/open-telemetry/opentelemetry-rust/commit/13fc775f92967eced4ba3581129d6091112ed8f3

The reason is that with_exporter uses either [`tokio::task::spawn_blocking`](https://docs.rs/tokio/0.2.22/tokio/task/fn.spawn_blocking.html) or [`async_std::task::spawn_blocking`](https://docs.rs/async-std/1.6.4/async_std/task/fn.spawn_blocking.html) (see [sdk::TraceProvider](https://github.com/open-telemetry/opentelemetry-rust/blob/0fa4e7d506cb52520607fa5da70d0efa15e1f6cb/src/sdk/trace/provider.rs)). Both of those expect a blocking function, not a function returning a future. This means the BatchSpanProcessorWorker is never polled.

## Possible solution

I assume the reason for using `spawn_blocking` is that the exporters currently run blocking, so it's good to run on a special thread for blocking work. The solution for the problem then is most likely to execute the future using block_on:

```rust
let spawn = |future| {
    tokio::task::spawn_blocking(|| {
        futures::executor::block_on(future);
        // or tokio::runtime::Handle::current().block_on(future)
        // or async_std::task::block_on(future)
    })
};
let batch = sdk::BatchSpanProcessor::builder(exporter, spawn, async_std::stream::interval);
```

If I do this, however, the program never exits. You can test this with the above linked example. The BatchSpanProcessorWorker just keeps running because it does never receive a shotdown message.

I'm not sure why, yet. I think the provider should be dropped and then notify all registered span processors. But that does not seem to happen.

If I manually call shutdown for all span processors, the worker stops properly, exports the remaining spans, and then the program exits.

I'm happy to work on a fix, but I would like to hear your thoughts first. What's the best way to proceed here?

**Comment by frigus02** [comment]
>  I think the provider should be dropped and then notify all registered span processors.

I'm pretty sure this happens because:

- A `TraceProvider` stores it's data in an inner struct inside an `Arc`.
- We call `shutdown` for all span processors when this inner struct is dropped.
- The inner struct owns a list of named `Tracer`s.
- Each `Tracer` owns a `TraceProvider`, which now forms a loop.
- We never drop named tracers, so there is always going to be a strong reference to the inner struct of the provider.

There is an additional reference to the provider in `global` as well.

**Comment by jtescher** [comment]
@frigus02 good catch, looks like we may need to go with something more along the lines of: 

```rust
std::thread::spawn(|| {
    futures::executor::block_on(async { future.await });
})
```

**Comment by frigus02** [comment]
I tested using `std::thread::spawn`. Results:
- It executes the BatchSpanProcessorWorker correctly
- It does not automatically wait for the thread to finish, which leads to a panic when using the stdout exporter:
  ```
  thread '<unnamed>' panicked at 'timer error: the timer is shutdown, must be called from the context of Tokio runtime
  ```

So in a way usig spawn_blocking is nice, because it plays nicely with the tokio/async_std runtime.

Can you think of a nice way to solve `shutdown` not being called at the moment because of the references?

**Comment by frigus02** [comment]
> Can you think of a nice way to solve shutdown not being called at the moment because of the references?

```rust
#[tokio::main]
async fn main() {
    let pipeline = stdout::new_pipeline().install();
    pipeline.tracer.in_span("test", |cx| {});

    drop(pipeline); // Dropping the pipeline could unregister the global provider, freeing up the reference.
}
```

Or maybe it's better to be explicit:

```rust
#[tokio::main]
async fn main() {
    let (tracer, uninstall) = stdout::new_pipeline().install();
    tracer.in_span("test", |cx| {});

    uninstall(); // Calling uninstall could unregister the global provider and clear named tracer, freeing up all references.
}
```

**Comment by jtescher** [comment]
@frigus02 yeah combination of drop guard, and having tracers have weak references to tracer providers should make things better.
