### ISSUE TITLE
metrics export duplicate data every 60s

### ISSUE THREAD

**Issue by domyway** [open-telemetry/opentelemetry-rust#2254]
I custom a metric export bellow: 

```
use core::fmt;
use std::fmt::{Debug, Formatter};

use async_trait::async_trait;
use opentelemetry::metrics::Result;
use opentelemetry_proto::tonic::collector::metrics::v1::ExportMetricsServiceRequest;
use opentelemetry_sdk::metrics::{
    data::{ResourceMetrics, Temporality},
    exporter::PushMetricsExporter,
    reader::{AggregationSelector, TemporalitySelector},
    Aggregation, InstrumentKind,
};

use crate::service::metrics::otlp_grpc::handle_grpc_request;

/// An interface for OTLP metrics clients
#[async_trait]
pub trait MetricsClient: fmt::Debug + Send + Sync + 'static {
    async fn export(&self, metrics: &mut ResourceMetrics) -> Result<()>;
    fn shutdown(&self) -> Result<()>;
}

/// Export metrics in OTEL format.
pub struct O2MetricsExporter {
    client: Box<dyn MetricsClient>,
    temporality_selector: Box<dyn TemporalitySelector>,
    aggregation_selector: Box<dyn AggregationSelector>,
}

impl Debug for O2MetricsExporter {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MetricsExporter").finish()
    }
}

impl TemporalitySelector for O2MetricsExporter {
    fn temporality(&self, kind: InstrumentKind) -> Temporality {
        self.temporality_selector.temporality(kind)
    }
}

impl AggregationSelector for O2MetricsExporter {
    fn aggregation(&self, kind: InstrumentKind) -> Aggregation {
        self.aggregation_selector.aggregation(kind)
    }
}

#[async_trait]
impl PushMetricsExporter for O2MetricsExporter {
    async fn export(&self, metrics: &mut ResourceMetrics) -> Result<()> {
        self.client.export(metrics).await
    }

    async fn force_flush(&self) -> Result<()> {
        // this component is stateless
        Ok(())
    }

    fn shutdown(&self) -> Result<()> {
        self.client.shutdown()
    }
}

impl O2MetricsExporter {
    /// Create a new metrics exporter
    pub fn new(
        client: impl MetricsClient,
        temporality_selector: Box<dyn TemporalitySelector>,
        aggregation_selector: Box<dyn AggregationSelector>,
    ) -> O2MetricsExporter {
        O2MetricsExporter {
            client: Box::new(client),
            temporality_selector,
            aggregation_selector,
        }
    }
}

pub(crate) struct O2MetricsClient {}

impl fmt::Debug for O2MetricsClient {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("O2MetricsClient")
    }
}

impl O2MetricsClient {
    pub fn new() -> Self {
        O2MetricsClient {}
    }
}

#[async_trait]
impl MetricsClient for O2MetricsClient {
    async fn export(&self, metrics: &mut ResourceMetrics) -> Result<()> {
        if let Err(e) = handle_grpc_request(
            "default",
            ExportMetricsServiceRequest::from(&*metrics),
            true,
        )
        .await
        {
            log::error!("o2 metrics export fail : {e}")
        }

        Ok(())
    }

    fn shutdown(&self) -> Result<()> {
        Ok(())
    }
}

```

and then init it with .with_interval 60s: 
```
pub async fn init_meter_provider() -> Result<SdkMeterProvider, anyhow::Error> {
    let exporter = O2MetricsExporter::new(
        O2MetricsClient::new(),
        Box::new(DefaultTemporalitySelector::new()),
        Box::new(DefaultAggregationSelector::new()),
    );
    let reader = PeriodicReader::builder(exporter, runtime::Tokio)
        .with_interval(Duration::from_secs(
            get_config().common.traces_span_metrics_export_interval, // defualt is 60s
        ))
        .build();
    let provider = SdkMeterProvider::builder()
        .with_reader(reader)
        .with_resource(Resource::new(vec![KeyValue::new(
            "service.name",
            "myservice",
        )]))
        .with_view(new_view(
            Instrument::new().name(format!("{}_span_duration_milliseconds", NAMESPACE)),
            Stream::new().aggregation(Aggregation::ExplicitBucketHistogram {
                boundaries: SPAN_METRICS_BUCKET.to_vec(),
                record_min_max: false,
            }),
        )?)
        .build();
    global::set_meter_provider(provider.clone());
    Ok(provider)
}
```

and I record jsut one metric data :

```
TRACE_METRICS_SPAN_HISTOGRAM.record(
            item.duration,
            &[
                KeyValue::new("organization", item.organization),
                KeyValue::new("traces_stream_name", item.traces_stream_name),
                KeyValue::new("service_name", item.service_name),
                KeyValue::new("operation_name", item.span_name),
                KeyValue::new("status_code", item.span_status),
                KeyValue::new("span_kind", item.span_kind),
            ],
        );
```

and then O2MetricsClient.export will be call every 60s , and then every time the old data will be pass to handle_grpc_request.  
I think the first time call the O2MetricsClient.export , ResourceMetrics will be cleaned and next 60s call export again, handle_grpc_request will not handle the duplicate data.  

Am I using it incorrectly, or did I misunderstand something?

**Comment by cijothomas** [comment]
Its not clear what versions of opentelemetry crates are being used. Could you ensure the latest release is used, and if that does not help, please share a minimal repro app, so we can investigate.

**Comment by domyway** [comment]
[otel-metrics.zip](https://github.com/user-attachments/files/17605396/otel-metrics.zip)

step: 
1. run server.rs  
2. run client.rs 

client send one span to server, but server handle_grpc_request will print duplicate data every 5s

**Comment by cijothomas** [comment]
@domyway Please share a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) so we can investigate.
Also its not clear what is meant by "duplicate data". Could you elaborate more on that?

**Comment by domyway** [comment]
> @domyway Please share a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) so we can investigate. Also its not clear what is meant by "duplicate data". Could you elaborate more on that?

minimal repro code: 
[otel-metrics.zip](https://github.com/user-attachments/files/17608833/otel-metrics.zip)

1. please download and unzip otel-metrics.zip
2. run server.rs, it will record one histogram data when a span export to server, and then after 5s, metric exporter will export the histogram to function handle_grpc_request, handle_grpc_request will print the whole ExportMetricsServiceRequest . which is the record . and every 5s, the handle_grpc_request will be executed,  although the server just recevie one span and just do one record. 
3. run client, it will create just one span to the server (step 2) and exit. 

duplicate data: 

```
ExportMetricsServiceRequest { resource_metrics: [ResourceMetrics { resource: Some(Resource { attributes: [KeyValue { key: "service.name", value: Some(AnyValue { value: Some(StringValue("openobserve")) }) }], dropped_attributes_count: 0 }), scope_metrics: [ScopeMetrics { scope: Some(InstrumentationScope { name: "o2", version: "", attributes: [], dropped_attributes_count: 0 }), metrics: [Metric { name: "span_duration_milliseconds", description: "span duration milliseconds", unit: "ms", metadata: [], data: Some(Histogram(Histogram { data_points: [HistogramDataPoint { attributes: [KeyValue { key: "service_name", value: Some(AnyValue { value: Some(StringValue("test")) }) }], start_time_unix_nano: 1730596926929379000, time_unix_nano: 1730596944287281000, count: 1, sum: Some(10.0), bucket_counts: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], explicit_bounds: [0.0, 5.0, 10.0, 25.0, 50.0, 75.0, 100.0, 250.0, 500.0, 750.0, 1000.0, 2500.0, 5000.0, 7500.0, 10000.0], exemplars: [], flags: 0, min: Some(10.0), max: Some(10.0) }], aggregation_temporality: Cumulative })) }], schema_url: "" }], schema_url: "" }] }
```

every 5s above duplicate data except the time_unix_nano will print . 
if handle_grpc_request function is store the data to disk , it store too many dup data .  and it is normal?

**Comment by cijothomas** [comment]
@domyway This is far from *minimal*. I won't have bandwidth to investigate at the moment.

I suggest to use a *minimal* repro (start with https://github.com/open-telemetry/opentelemetry-rust/blob/main/examples/metrics-basic/src/main.rs).


> every 5s above duplicate data except the time_unix_nano will print .

If you are using cumulative, then that would be the expected behavior. Metrics are always exported irrespective of whether they had a new update or not, so only change would be the end time. (If this is the issue, then no need to work on minimal repro.)

**Comment by domyway** [comment]
> If you are using cumulative, then that would be the expected behavior. Metrics are always exported irrespective of whether they had a new update or not, so only change would be the end time. (If this is the issue, then no need to work on minimal repro.)

Metrics are always exported irrespective of whether they had a new update or not ， is this design specification？

**Comment by cijothomas** [comment]
@domyway Cumulative is expected to behave like that, yes.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader
_For synchronous instruments with Cumulative aggregation temporality, [MetricReader.Collect](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#collect) MUST receive data points exposed in previous collections regardless of whether new measurements have been recorded._

The choice of using Delta vs Cumulative is typically determined by the backend. Prometheus is the most prominent backend which *expects* cumulative. Many vendors (including my employer Microsoft) has metric backends that expects delta. There are definitely pros and cons with cumulative and deltas, but its best to discuss them outside of this repo.

Here's a talk about this topic from a recent conference : https://www.youtube.com/watch?v=hmm39H2Tfew&list=PLj6h78yzYM2O0Z03hAYpoN_EjNbwTxZ4m
