### ISSUE TITLE
Internal logging in BatchProcessor when buffer full

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#2273]
Opening a separate issue to specifically tracking internal logging when BatchProcessor gets full.
https://github.com/open-telemetry/opentelemetry-rust/issues/2175#issuecomment-2394816345

1. We certainly don't want to log each time the buffer is full
2. A good balance might be to keep a count of items-dropped-due-to-buffer-full.
3. This count can be exposed as a Metric itself.
4. And/Or this count can be emitted as a internal log upon shutdown/drop with severity WARN if non-zero items were dropped.

2,4 is what OTel .NET has implemented: See https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/BatchExportProcessor.cs#L102 and https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/BatchExportProcessor.cs#L207

**Comment by scottgerring** [comment]
Hey @cijothomas , I can pick this one up !
