### ISSUE TITLE
Consistent way to set resource to provider

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#2294]
Originally posted here : https://github.com/open-telemetry/opentelemetry-rust/issues/1810#issuecomment-2466420943.

@pitoniak32 Agree to make Trace follow the same as other.

**Comment by cijothomas** [comment]
For 0.27.1 maybe we can mark the existing way as deprecated, and actual removal in 0.28

**Comment by pitoniak32** [comment]
I will open a PR to have further discussion about how we should handle the other config items that are handled via this config struct.
