### ISSUE TITLE
Error Flagging with Status Codes

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#234]
See the [spec change](https://github.com/open-telemetry/opentelemetry-specification/pull/966) for details.

**Comment by drexler** [comment]
@jtescher i'll take this one on.

**Comment by drexler** [comment]
Blocked on https://github.com/open-telemetry/opentelemetry-proto/pull/224. I'll push my branch once that merges.

**Comment by jtescher** [comment]
Closed via #315
