### ISSUE TITLE
Consider moving the propagators to from contrib to SDK

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#235]
See the [spec change](https://github.com/open-telemetry/opentelemetry-specification/pull/1043) and the [comment that explains it](https://github.com/open-telemetry/opentelemetry-specification/issues/637#issuecomment-644846847) for details.

**Comment by awiede** [comment]
Should probably do the same thing for the [AWS ID Generator](https://github.com/open-telemetry/opentelemetry-rust/blob/master/opentelemetry-contrib/src/id_generator/aws_xray_id_generator.rs). I think the [logic in the comment](https://github.com/open-telemetry/opentelemetry-specification/issues/637#issuecomment-644846847) holds for that as well.
