### ISSUE TITLE
tracing minimum version dependency

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#2373]
Opening an issue to continue the discussion in https://github.com/open-telemetry/opentelemetry-rust/pull/2128#issuecomment-2478644843

**Comment by lalitb** [comment]
I think relatively easy non-breaking solution would be to remove use of `name:` metadata from the otel macros, and introduce them later.
```rust
macro_rules! otel_info {
    (name: $name:expr $(,)?) => {
        #[cfg(feature = "internal-logs")]
        {
            tracing::info!( name: $name, target: env!("CARGO_PKG_NAME") ~, "");
        }
        #[cfg(not(feature = "internal-logs"))]
        {
            let _ = $name; // Compiler will optimize this out as it's unused.
        }
    };
```

**Comment by cijothomas** [comment]
but is there anything preventing us from requiring the minimum version of tracing that supports name?

**Comment by lalitb** [comment]
>  but is there anything preventing us from requiring the minimum version of tracing that supports name?

Yes I think this should be fine to go with.
