### ISSUE TITLE
OTLP Exporter - initialize Reqwest::Blocking client must be done in non async context

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#2400]
Related to https://github.com/open-telemetry/opentelemetry-rust/issues/1757
Currently, initializing OTLP Exporter causes the creation of Reqwest::blocking client creation. If the user's main thread is a tokio::main or other asyn runtime context, this panics.

Reqwest::blocking client must be created separately to avoid this panic. Options include spinning up a throwaway thread, just for the sake of initializing the blocking client, or delaying the creation of client until 1st export.

Required for https://github.com/open-telemetry/opentelemetry-rust/issues/2386

**Comment by cijothomas** [comment]
@pitoniak32 Something you want to give a try?

**Comment by pitoniak32** [comment]
I can take a look at it. It might take me a little bit since I will probably need to do some research. I'll let you know if I run into issues though

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-rust/issues/2189 can be closed once this is addressed.
