### ISSUE TITLE
Add prometheus exporter env vars

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#242]
See https://github.com/open-telemetry/opentelemetry-specification/pull/1021 for details.

**Comment by morigs** [comment]
The exporter doesn't seem to have a built-in server right now. He probably should have it like the rest of the exporters. I would like to suggest to expose builder interface similar to otlp exporter

**Comment by TommyCpp** [comment]
@morigs Sounds good. Just the other exporters don't have a http server but rather a http client. So maybe need a new trait for http server. We encountered problems that certain http client cannot run without particular runtime(like tokio) when we added http client into other expoters. So we choose to define a trait for http client and ask user to choose the one compatible with their runtime.

**Comment by jtescher** [comment]
Seems like there are 3 cases that may be relevant: 

1. Showing prometheus integrated with the [`push`](https://docs.rs/prometheus/0.10.0/prometheus/index.html#features) feature enabled, which is the most similar to the trace exporters.
1. Integrating prometheus into projects that have an existing web server (actix-web, rocket, etc), likely as middleware.
1. Allowing projects that do _not_ have an existing web server to still expose prometheus metrics over http.

This issue specifically is just about adding a `from_env` method to the builder and pulling values in accordingly from env vars, but issues could be opened for the above 3.

**Comment by morigs** [comment]
I think the second case is being covered at the moment. Case number one is quite rare, but of course must be covered too.
It seems to me that it is necessary to implement case 3 while keeping the interface for case 2.
It might be worth making a separate exporter for push gateway.
@jtescher What do you think?

**Comment by jtescher** [comment]
@morigs opened an issue to track it https://github.com/open-telemetry/opentelemetry-rust/issues/293

**Comment by LanceEa** [comment]
@jtescher - If no one has grabbed this one yet, then I wouldn't mind helping out. 

Based on a review of the link you posted it seems the Prometheus Exporter currently only has the host and port being defined. I see under the general section the `OTEL_RESOURCE_ATTRIBUTES` is stable. Should we also consider adopting that as well as part of this issue? 

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration

Cheers,
Lance

**Comment by TommyCpp** [comment]
I think it's nice to also support `OTEL_RESOURCE_ATTRIBUTES` env var.

**Comment by LanceEa** [comment]
Ok sounds good. I will add that to the PR. 

The contributing guide for this exporter doesn't mention anything about updating the changelog. Should I do that as part of this PR and if so would this be a bump to `v0.9.0` or just a patch `v0.8.1`?

**Comment by TommyCpp** [comment]
We usually update the changelog when we cut a new release. There is no requirement for contributors to include a change log entry. But it is definitely welcome to add one as it helps when we cut the release.
