### ISSUE TITLE
Expoters uses reqwest panic without tokio

### ISSUE THREAD

**Issue by TommyCpp** [open-telemetry/opentelemetry-rust#248]
As [the issue](https://github.com/seanmonstar/reqwest/issues/719) points out, reqwest relys on tokio to work. Currently, any expoters with reqwest as http client will panic with following error without tokio (For example, the datadog and zipkin expoters example are broken).
```
there is no reactor running, must be called from the context of Tokio runtime
```
Possible solution could be move away from reqwest or try to implement async and sync uploader with non-blocking and blocking client (But I guess this doesn't really solve the problem to running those expoters with `async-std`)

**Comment by jtescher** [comment]
@TommyCpp true, we chould switch them to use [isahc](https://github.com/sagebind/isahc) like the jaeger collector client does?

**Comment by TommyCpp** [comment]
I could give it a try to see how it goes
