### ISSUE TITLE
Update trace config max defaults

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#268]
See the spec change here for details https://github.com/open-telemetry/opentelemetry-specification/pull/942

**Comment by morigs** [comment]
Do I understand correctly that the task is reduced to replacing [these constants](https://github.com/open-telemetry/opentelemetry-rust/blob/b47794e5818d7ba39115933ea7f752b8784cf025/src/sdk/trace/config.rs#L80-L82) with the values of environment variables (with a default value of 1000 of course)?

**Comment by jtescher** [comment]
@morigs the conventions so far in this workspace have been to have constants (that need to be updated here) and the struct or builder to have a `from_env` method that would use the env vars

**Comment by morigs** [comment]
Ok. So `default()` should always use values of 1000.
But where `from_env` should be located? Is it ok to be right inside [`impl Config`](https://github.com/open-telemetry/opentelemetry-rust/blob/b47794e5818d7ba39115933ea7f752b8784cf025/src/sdk/trace/config.rs#L30)?
So usage would be `Config::default().from_env()`?
This will require adding `.from_env ()` to all places where config was created, because environment variables must always be respected (imho).

**Comment by jtescher** [comment]
@morigs I personally prefer that env vars should always be used when available as well. This project went with the explicit version both because of conventions set by the golang impl (e.g. [`FromEnv`](https://github.com/open-telemetry/opentelemetry-go/blob/1f7c2206522accd0a176ed8d93183f1168d70939/sdk/resource/env.go#L36), [`WithProcessFromEnv`](https://github.com/open-telemetry/opentelemetry-go/blob/d6dd84f6fa740ddfcf028dab0d79c07513b072cb/exporters/trace/jaeger/env.go#L94), etc) as that is the most widely used distribution, as well as the ambiguity when using struct constructor with defaults. 

E.g. `Config { max_events_per_span: 100, ..Default::default() }` wouldn't pick up the variables.

It does have the somewhat substantial downside that consumers of the API may be confused when they set env vars that do not have the effect they expect. I would be open to re-evaluating the decision to use explicit from env if you want to open an issue for that (e.g. we could make all fields private across the projects to force going through constructors that would pick up the environment)

**Comment by morigs** [comment]
> consumers of the API may be confused when they set env vars that do not have the effect they expect
Totally agreed
> if you want to open an issue for that (e.g. we could make all fields private across the projects to force going through constructors that would pick up the environment)
I believe it's better to go this way. But I'm new to the OTel ecosystem and don't know all conventions and best practices. So I rely on your decision

**Comment by frigus02** [comment]
I'd be happy to move to private fields and automated environment lookup as well.

This would also enable us to add new configuration options without making that a breaking change, I think.
