### ISSUE TITLE
Add an exporter for Google Cloud Trace

### ISSUE THREAD

**Issue by djc** [open-telemetry/opentelemetry-rust#271]
I'd like to export my tracing data to Google Cloud Trace for a project running in GCP. I'd be happy to do the legwork to implement this and contribute it to this project, but I'm pretty new to OpenTelemetry, tracing and GCP (though not to Rust and the tokio ecosystem), so if someone has some pointers on what needs to be done, that'd be great.

**Comment by TommyCpp** [comment]
I think there is a [existing repo](https://github.com/vivint-smarthome/opentelemetry-stackdriver) that export data to Google stack driver. Is this something that you are looking for?

**Comment by djc** [comment]
Maybe! There seems to be very little documentation, so not sure how I'd actually deploy it.

**Comment by TommyCpp** [comment]
close as there is https://crates.io/crates/opentelemetry-stackdriver existing

**Comment by djc** [comment]
Yeah, I'm mostly maintaining it, so I guess the situation is okay for now.
