### ISSUE TITLE
Track batch span processor metrics

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#272]
Consider adding a way to track processor metrics. See https://github.com/open-telemetry/opentelemetry-rust/pull/245#issuecomment-704608797 for discussion.

**Comment by plantfansam** [comment]
In OpenTelemetry Ruby and also [in Lua](https://github.com/yangxikun/opentelemetry-lua/blob/main/lib/opentelemetry/metrics_reporter.lua) we have a default no-op [MetricsReporter](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/sdk/lib/opentelemetry/sdk/trace/export/metrics_reporter.rb), but users can supply their own class which conforms to the `MetricsReporter` interface (see e.g. the [OTLP Exporter constructor](https://github.com/open-telemetry/opentelemetry-ruby/pull/510/files#diff-34fb5aed920b31dca334d76d897e2cd337ee9ac0380b550ee3aef6f5eab60eb5R58)). Not sure how one might accomplish this Rustily, but if you want to supply some guidance I'm happy to try to port over!

**Comment by cijothomas** [comment]
It is an important, but not mandatory capability for OTel Tracing. (no stable spec for this, but could be coming)
Removing from sdk stable milestone.

**Comment by cijothomas** [comment]
Closing issue as there is no spec or convention defined for this. Once there is a spec/convention, we can add this.
