### ISSUE TITLE
APis return Box<dyn Error> which isn't compatibile with useful ecosystem crates

### ISSUE THREAD

**Issue by cpcloud** [open-telemetry/opentelemetry-rust#282]
A number of APIs, especially the `new_pipeline().install()` flavors return `Box<dyn Error>`. This trait bound is incompatible with useful ecosystem crates like `anyhow`, whose `Context` trait requires `Box<dyn Error + Send + Sync + 'static>`.

I'm happy to submit a PR to fix this. Are there any APIs where we _don't_ want this trait bound?

**Comment by frigus02** [comment]
Good point. Using `Box<dyn Error + Send + Sync + 'static>` seems sensible to me. I can't think of a reason why we wouldn't want this. Can you, @jtescher?

**Comment by jtescher** [comment]
Yeah this sounds good. We want to unify the error types with the current `MetricsError` type in the future, but this can come first 👍
