### ISSUE TITLE
Add required-features to benches configuration

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-rust#300]
Currently `cargo bench` fails with errors:
<details>
  <summary>Click to expand</summary>
  <pre>
   Compiling opentelemetry v0.9.1 (D:\projects\opentelemetry-rust)
error[E0432]: unresolved import `opentelemetry::api::metrics`
 --> benches\ddsketch.rs:2:25
  |
2 | use opentelemetry::api::metrics::{InstrumentKind, Number, NumberKind};
  |                         ^^^^^^^ could not find `metrics` in `api`

error[E0432]: unresolved import `opentelemetry::sdk::export::metrics`
 --> benches\ddsketch.rs:3:33
  |
3 | use opentelemetry::sdk::export::metrics::Aggregator;
  |                                 ^^^^^^^ could not find `metrics` in `export`

error[E0433]: failed to resolve: could not find `metrics` in `sdk`
 --> benches\ddsketch.rs:8:9
  |
8 |         metrics::aggregators::{ArrayAggregator, DDSKetchAggregator, DDSketchConfig},
  |         ^^^^^^^ could not find `metrics` in `sdk`

error[E0432]: unresolved imports `opentelemetry::api::metrics`, `opentelemetry::sdk::export::metrics`
 --> benches\ddsketch.rs:5:10
  |
5 |     api::metrics::Descriptor,
  |          ^^^^^^^ could not find `metrics` in `api`
6 |     sdk::{
7 |         export::metrics::Quantile,
  |                 ^^^^^^^ could not find `metrics` in `export`

error[E0432]: unresolved imports `opentelemetry::api::metrics`, `opentelemetry::sdk::export::metrics`, `opentelemetry::sdk::metrics`
  --> benches\metric.rs:7:9
   |
7  |         metrics::{Descriptor, Meter},
   |         ^^^^^^^ could not find `metrics` in `api`
...
11 |         export::metrics::{AggregatorSelector, Processor},
   |                 ^^^^^^^ could not find `metrics` in `export`
12 |         metrics::{accumulator, aggregators},
   |         ^^^^^^^ could not find `metrics` in `sdk`

error[E0433]: failed to resolve: use of undeclared type or module `DDSKetchAggregator`
  --> benches\ddsketch.rs:28:9
   |
28 |         DDSKetchAggregator::new(&DDSketchConfig::new(0.001, 2048, 1e-9), NumberKind::F64);
   |         ^^^^^^^^^^^^^^^^^^ use of undeclared type or module `DDSKetchAggregator`

error[E0433]: failed to resolve: could not find `metrics` in `export`
   --> benches\metric.rs:102:53
    |
102 |     ) -> Option<Arc<dyn opentelemetry::sdk::export::metrics::Aggregator + Send + Sync>> {
    |                                                     ^^^^^^^ could not find `metrics` in `export`

error[E0433]: failed to resolve: use of undeclared type or module `DDSketchConfig`
  --> benches\ddsketch.rs:28:34
   |
28 |         DDSKetchAggregator::new(&DDSketchConfig::new(0.001, 2048, 1e-9), NumberKind::F64);
   |                                  ^^^^^^^^^^^^^^ use of undeclared type or module `DDSketchConfig`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error[E0433]: failed to resolve: use of undeclared type or module `DDSKetchAggregator`
  --> benches\ddsketch.rs:38:72
   |
38 |     let new_aggregator: Arc<(dyn Aggregator + Send + Sync)> = Arc::new(DDSKetchAggregator::new(
   |                                                                        ^^^^^^^^^^^^^^^^^^ use of undeclared type or module `DDSKetchAggregator`

error[E0433]: failed to resolve: use of undeclared type or module `DDSketchConfig`
  --> benches\ddsketch.rs:39:10
   |
39 |         &DDSketchConfig::new(0.001, 2048, 1e-9),
   |          ^^^^^^^^^^^^^^ use of undeclared type or module `DDSketchConfig`

error: could not compile `opentelemetry`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0433]: failed to resolve: use of undeclared type or module `ArrayAggregator`
  --> benches\ddsketch.rs:53:22
   |
53 |     let aggregator = ArrayAggregator::default();
   |                      ^^^^^^^^^^^^^^^ use of undeclared type or module `ArrayAggregator`

error[E0433]: failed to resolve: use of undeclared type or module `ArrayAggregator`
  --> benches\ddsketch.rs:63:72
   |
63 |     let new_aggregator: Arc<(dyn Aggregator + Send + Sync)> = Arc::new(ArrayAggregator::default());
   |                                                                        ^^^^^^^^^^^^^^^ use of undeclared type or module `ArrayAggregator`

error[E0412]: cannot find type `DDSKetchAggregator` in this scope
  --> benches\ddsketch.rs:46:78
   |
26 | fn ddsketch(data: Vec<f64>) {
   |            - help: you might be missing a type parameter: `<DDSKetchAggregator>`
...
46 |         if let Some(new_aggregator) = new_aggregator.as_any().downcast_ref::<DDSKetchAggregator>() {
   |                                                                              ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `ArrayAggregator` in this scope
  --> benches\ddsketch.rs:68:78
   |
52 | fn array(data: Vec<f64>) {
   |         - help: you might be missing a type parameter: `<ArrayAggregator>`
...
68 |         if let Some(new_aggregator) = new_aggregator.as_any().downcast_ref::<ArrayAggregator>() {
   |                                                                              ^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to 12 previous errors

Some errors have detailed explanations: E0412, E0432, E0433.
For more information about an error, try `rustc --explain E0412`.
error: build failed
  </pre>
</details>

The following change to Cargo.toml resolves this issue:
```toml
[[bench]]
name = "metric"
harness = false
required-features = ["metrics"]

[[bench]]
name = "ddsketch"
harness = false
required-features = ["metrics"]
```

if everyone agrees with this I'm ready to submit a PR

**Comment by frigus02** [comment]
Sounds like a good idea 👍
