### ISSUE TITLE
Add note about prerequisites to CONTRIBUTING.md

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-rust#302]
As a new contributor I had some problems setting up opentelemetry-rust.
 `opentelemetry-otlp` requires following:
- protoc
- cmake
- llvm (+ LIBCLANG_PATH env)

I think this should be described in the CONTRIBUTING.md. I can submit a PR

**Comment by jtescher** [comment]
@morigs sounds good! It is unfortunate that the grpc requirements have to be set up to work on any project in this workspace.
