### ISSUE TITLE
examples/basic-otlp fails to compile

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-rust#306]
<details>
<summary>Click to expand</summary>
<pre>
error[E0277]: the trait bound `opentelemetry::exporter::metrics::stdout::ExportBatch: serde::ser::Serialize` is not satisfied
   --> examples\basic-otlp\src\main.rs:29:34
    |
29  |             serde_json::to_value(batch)
    |                                  ^^^^^ the trait `serde::ser::Serialize` is not implemented for `opentelemetry::exporter::metrics::stdout::ExportBatch`
    | 
   ::: C:\Users\gogam\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_json-1.0.59\src\value\mod.rs:962:8
    |
962 |     T: Serialize,
    |        --------- required by this bound in `serde_json::to_value`

error: aborting due to previous error
</pre>
</details>

I believe the simplest way to fix this is to add `serialize` feature to Cargo.toml

```
opentelemetry-otlp = { path = "../../opentelemetry-otlp", features = ["serialize"] }
```

**Comment by frigus02** [comment]
Your suggestions sounds correct to me.

We should probably also build all examples in CI to ensure we don't accidentally break them.

**Comment by morigs** [comment]
👌 I'll submit a PR soon
Please, create a separate issue for CI if you consider it necessary
