### ISSUE TITLE
Ensure compliance with b3 propagator spec

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#314]
See the clarification of the spec here https://github.com/open-telemetry/opentelemetry-specification/pull/1045

**Comment by TommyCpp** [comment]
I think we almost dodge all the bullets on this one. :joy:  The only difference is 

>  MUST attempt to extract B3 encoded using single and multi-header
  formats. The single-header variant takes precedence over
  the multi-header version. 

When extract we will follow users' choice on encoding. But if user select `SingleAndMultiHeader`, we will try single first. Wonder if we want to change it to always try single format first and fall back to multiple version when single format is not present or invalid.


The rest of the change should already be covered. See details below

> MUST preserve a debug trace flag, if received, and propagate
  it with subsequent requests. Additionally, an OpenTelemetry implementation
  MUST set the sampled trace flag when the debug flag is set.

We set the sampled and debug flag in SpanContext,
https://github.com/open-telemetry/opentelemetry-rust/blob/dbe57cc2c356b29ec356377c671e7c9e00dfee99/src/sdk/propagation/b3.rs#L135

> MUST NOT reuse `X-B3-SpanId` as the id for the server-side span.

I think we use the result of extraction as remote span context, so we will always generate new span for operation in the application
https://github.com/open-telemetry/opentelemetry-rust/blob/dbe57cc2c356b29ec356377c671e7c9e00dfee99/src/sdk/propagation/b3.rs#L282

>  MUST NOT propagate `X-B3-ParentSpanId` as OpenTelemetry does not support
  reusing the same id for both sides of a request.

We don't inject this header
https://github.com/open-telemetry/opentelemetry-rust/blob/dbe57cc2c356b29ec356377c671e7c9e00dfee99/src/sdk/propagation/b3.rs#L235-L254
