### ISSUE TITLE
api::Value is much more loosely typed than the spec

### ISSUE THREAD

**Issue by djc** [open-telemetry/opentelemetry-rust#317]
In particular, it allows heterogenous arrays and has a `Bytes` variant that doesn't seem to appear in the spec. Would it be useful to define it more like this?

```rust
enum Primitive {
    Bool(bool),
    Int(i64),
    Float(f64),
    String(String),
}

enum Array {
    Bool(Vec<Option<bool>>),
    Int(Vec<Option<i64>>),
    Float(Vec<Option<f64>>),
    String(Vec<Option<String>>),
}

enum Value {
    Primitive(Primitive),
    Array(Array),
}
```

https://github.com/open-telemetry/opentelemetry-specification/blob/9e6a3de19cb3db983b2e4d56b37ec6313fd4ffc6/specification/common/common.md#attributes

**Comment by jtescher** [comment]
Additional discussion around optional array values: https://github.com/open-telemetry/opentelemetry-specification/pull/1155

**Comment by djc** [comment]
After #323, #332 and #333, I think this is now in a pretty good shape.
