### ISSUE TITLE
Move SpanProcessor into sdk and update the type of span parameter to sdk::Span

### ISSUE THREAD

**Issue by TommyCpp** [open-telemetry/opentelemetry-rust#327]
While applying today's change into my zpage brach. I found one issue with span parameter type being `&dyn api::Span`. 
As defined in spec, 
> span - a read/write span object for the started span.

the span should be a [read/write span object](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#additional-span-interfaces), which means it should be able to read all information added into span such as span name, start time, etc. But the current type(`&dyn api::Span`) only provides write API. So ideally we should update the type into `&sdk::Span`. 

But it's kind of confusing to have a type in api module(SpanProcessor) to depend on a type from sdk module(sdk::Span). So we might as well move SpanProcessor into sdk. The other reason is SpanProcessor is defined in sdk instead of api in spec.

**Comment by jtescher** [comment]
Hm maybe the SDK should provide something like a `ReadSpan` trait that the sdk's `Span` implements? Seems like the write side is covered.

**Comment by TommyCpp** [comment]
@jtescher Yes the write side is covered by api level span definition. But the whole `read/write span` is a concept only apply to sdk so I think we should still move the SpanProcessor into sdk. Then maybe we could have a something like
```rust
pub trait ReadableSpan: api::Span{
    fn span_data(&self) -> SpanData
}
```
 I can work on this if those sound reasonable.

**Comment by jtescher** [comment]
True it is more defined in the SDK than the API in the spec. Sounds reasonable to me.
