### ISSUE TITLE
Update ExportResult: use std::result::Result type

### ISSUE THREAD

**Issue by frigus02** [open-telemetry/opentelemetry-rust#331]
Update [`ExportResult`](https://github.com/open-telemetry/opentelemetry-rust/blob/866ae41bd238a293a9da25e8d457da3162df3aa9/opentelemetry/src/exporter/trace/mod.rs#L21) to match the latest version in the spec:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#exportbatch

> ExportResult is one of:
> - **Success** - The batch has been successfully exported. For protocol exporters this typically means that the data is sent over the wire and delivered to the destination server.
> - **Failure** - exporting failed. The batch must be dropped. For example, this can happen when the batch contains bad data and cannot be serialized.

Since this only defines 2 states now (error and success), we should probably go the idiomatic Rust route and use a `std::result::Result`.

**Comment by jtescher** [comment]
Is this type actually necessary anymore if there are only two possibilities? or would a result type of some kind be more idiomatic?

**Comment by TommyCpp** [comment]
I think we can define a `ExportError` as `Failure` and use `Result` as return type.

**Comment by frigus02** [comment]
Yeah, that's a good point. Let's use a `Result` type. I guess we either wait until #286 and make some kind of `ExportError` or we start with `Box<dyn Error + Send + Sync + 'static>`?

I wonder if we should keep the name `ExportResult` as a type alias or if we just go with a standard `Result`.

**Comment by jtescher** [comment]
Seems like the only purpose here may be calling an error handler as both success and failure will drop the span data. If that is the case then #263 may be the only code path that would use this type?

**Comment by frigus02** [comment]
Yeah, that's how I understand this as well.
