### ISSUE TITLE
Consider moving base64 and binary propagators to contrib

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#336]
They are not currently part of the spec, we should consider moving them before GA

**Comment by TommyCpp** [comment]
:+1: Also wonder would it make sense to revisit how we structure the contrib. I think something like
```
opentelemetry-contrib
|--trace
|  |--propagator
|  |--exporter
|
|--metric
   |--..
```
maybe more align with main crate?
