### ISSUE TITLE
Consider allowing multiple attributes to be set at once

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#338]
Currently span attributes must be set one at a time, and take a (likely uncontended) lock each time. Consider whether it is worth it to have a second method that takes an array of kv, or if the method should take a generic. Possibly not necessary, but we should decide before GA

**Comment by TommyCpp** [comment]
I don't see why we can't implement one. This should improve ergonomics and  seems easy to add.  I think maybe take a generic iterator of KV?

**Comment by jtescher** [comment]
Give it a shot and see if it is ergonomic, can look at the benchmarks too to see if batch inserts matter there

**Comment by TommyCpp** [comment]
So I image we could also close this issue and remove it from GA checklist?
