### ISSUE TITLE
Sampler::TraceIdRatioBased problem

### ISSUE THREAD

**Issue by zloypacifist** [open-telemetry/opentelemetry-rust#351]
I've used code from example basic

```
use opentelemetry::global;
use opentelemetry::sdk::{trace as sdktrace};
use std::error::Error;
use opentelemetry::api::trace::{Tracer, TraceContextExt};
use opentelemetry::sdk::trace::{Config, Sampler};

fn init_tracer() -> Result<
    (sdktrace::Tracer, opentelemetry_jaeger::Uninstall),
    Box<dyn Error>,
> {
    opentelemetry_jaeger::new_pipeline()
        .with_service_name("test")
        .with_trace_config(Config::default().with_default_sampler(Sampler::TraceIdRatioBased(0.25)))
        .install()
}

fn main() -> Result<(), Box<dyn Error + Send + Sync + 'static>> {
    let _uninstall = init_tracer().unwrap();

    let tracer = global::tracer("ex.com/basic");

    tracer.in_span("operation", |cx| {
        let _span = cx.span();
        tracer.in_span("Sub operation...", |cx| {
            let _span = cx.span();
            // some sub operation
        });
    });

    Ok(())
}
```
With sampler always on everything works fine, but when I use Sampler::TraceIdRatioBased(0.25) sometimes I receive in jaeger just sub span. So span "operation" didn't sampled, but "Sub operation" sampled
![image](https://user-images.githubusercontent.com/2009979/98520210-8e6d5980-2293-11eb-9d6c-d192fb7af4b6.png)

How can I use ratio < 1.0

**Comment by frigus02** [comment]
Hm, good question. You might was to use the `ParentBased` sampler. If I understand it correctly, it will only make a sample decision for root spans. All child spans use the same decision as their parent. So you should only sample full traces.

```rust
opentelemetry_jaeger::new_pipeline()
    .with_service_name("test")
    .with_trace_config(Config::default().with_default_sampler(Sampler::ParentBased(Box::new(Sampler::TraceIdRatioBased(0.25)))))
    .install()
```

**Comment by zloypacifist** [comment]
> Hm, good question. You might want to use the `ParentBased` sampler. If I understand it correctly, it will only make a sample decision for root spans. All child spans use the same decision as their parent. This should make it so only full traces get sampled.
> 
> ```rust
> opentelemetry_jaeger::new_pipeline()
>     .with_service_name("test")
>     .with_trace_config(Config::default().with_default_sampler(Sampler::ParentBased(Box::new(Sampler::TraceIdRatioBased(0.25)))))
>     .install()
> ```

Doesn't work.
```
use opentelemetry::global;
use opentelemetry::sdk::{trace as sdktrace};
use std::error::Error;
use opentelemetry::api::trace::{Tracer, TraceContextExt};
use opentelemetry::sdk::trace::{Config, Sampler};

fn init_tracer() -> Result<
    (sdktrace::Tracer, opentelemetry_jaeger::Uninstall),
    Box<dyn Error>,
> {
    opentelemetry_jaeger::new_pipeline()
        .with_service_name("test")
        .with_trace_config(Config::default().with_default_sampler(Sampler::ParentBased(Box::new(Sampler::TraceIdRatioBased(0.25)))))
        .install()
}

fn main() -> Result<(), Box<dyn Error + Send + Sync + 'static>> {
    let _uninstall = init_tracer().unwrap();

    let tracer = global::tracer("ex.com/basic");

    tracer.in_span("operation", |cx| {
        let _span = cx.span();
        tracer.in_span("Sub operation...", |cx| {
            // some sub operation
        });
        tracer.in_span("Sub operation2...", |cx| {
            // some sub operation
        });
    });

    Ok(())
}
```
Now span "operation" doesn't sample at all. sub and sub2 sampled separately.
![image](https://user-images.githubusercontent.com/2009979/98534630-8ff44d00-22a6-11eb-8b4d-01f1e9099684.png)

**Comment by jtescher** [comment]
@zloypacifist  thanks for reporting this, it appears to be a bug in the parent based sampler where dropped parent spans are being filtered out, making the children root spans.

**Comment by zloypacifist** [comment]
thank you very much, fix works fine!
