### ISSUE TITLE
Implement the standard performance benchmark

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#356]
See the spec change for details https://github.com/open-telemetry/opentelemetry-specification/pull/748

**Comment by cijothomas** [comment]
https://github.com/ThomsonTan/opentelemetry-specification/blob/main/specification/performance-benchmark.md The spec for this is stale with no movement. Its not marked with typical "experimental" or "stable" status either. Given we have benchmarks in this repo (and stress tests), closing this item. We can continue to add benchmarks, but don't think we need this tracking issue.
