### ISSUE TITLE
Add link to Gitter room in README

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-rust#36]

**Comment by VineethReddy02** [comment]
Hey!
I don't see any room with name opentelemetry-rust. I was expecting rust room with the same name as go opentelemetry-go. Can someone point me the gitter room for rust.

**Comment by iredelmeier** [comment]
@VineethReddy02 https://gitter.im/open-telemetry/opentelemetry-rust

Want me to assign this to you?

**Comment by VineethReddy02** [comment]
Yesh! I can take this up.
