### ISSUE TITLE
`Sampler::AlwaysOff` behavior doubts (AKA how to disable data sampling)

### ISSUE THREAD

**Issue by wronan** [open-telemetry/opentelemetry-rust#376]
Ladies and gentlemen, I'm having doubts about the logic behind `Sampler::AlwaysOff`

Being new to the tracking concept it's my understanding that Sampler offers
* inheritance (`ParentBased`),
* direct setting of the sampling ratio (`TraceIdRatioBased`),
* default sampling (`AlwaysOn`)
* and no sampling at all (`AlwaysOff`)

Here comes my problem: shouldn't `Sampler::AlwaysOff` mean that no sampling is in play thus all traces are logged? Documentation says `Never sample the trace`.

But judging from the [code](https://github.com/open-telemetry/opentelemetry-rust/blob/a0ade712c0dcc059a311868110eb168eb177fffd/opentelemetry/src/sdk/trace/sampler.rs#L114) all traces are dropped with this variant (`SamplingDecision::Drop`). Shouldn't rather `SamplingDecision::RecordOnly` be the result of [this match](https://github.com/open-telemetry/opentelemetry-rust/blob/a0ade712c0dcc059a311868110eb168eb177fffd/opentelemetry/src/sdk/trace/sampler.rs#L114)?

If not then how can I achieve `SamplingDecision::RecordOnly`? Because it looks like it never happens.

I'd like to hear your opinion / receive some guidance here before I attempt to fix the problem.

**Comment by jtescher** [comment]
@wronan you can see the spec for the sampler here: https://github.com/open-telemetry/opentelemetry-specification/blob/15ac35c174f097b37e4e7b8a3653700bb2e7e763/specification/trace/sdk.md#alwaysoff, any deviations from the spec you find are indeed bugs, but in this case it looks like that is the required result.

Happy to accept a docs pr if they are not clear about how the sampler works in this codebase too 👍

**Comment by wronan** [comment]
Oh... indeed that's what specification says.

I'd still argue that since `Sampler::AlwaysOn` means that sampling is enabled and only some portion of the traces is being stored, then `Sampler::AlwaysOff` means that sampling is disabled thus all traces are being stored instead of none of them like it's currently implemented.

My goal is to trace every request - without sampling.
Even if I employ `TraceIdRatioBased(1.0)` then this happens https://github.com/open-telemetry/opentelemetry-rust/blob/a0ade712c0dcc059a311868110eb168eb177fffd/opentelemetry/src/sdk/trace/sampler.rs#L132 and even `1.0` should mean "no sampling" - data is still being sampled.

Could you maybe suggest to me how to achieve `RECORD_ONLY` variant of https://github.com/open-telemetry/opentelemetry-specification/blob/15ac35c174f097b37e4e7b8a3653700bb2e7e763/specification/trace/sdk.md#shouldsample? `DROP` is used, `RECORD_AND_SAMPLE` is used but not `RECORD_ONLY`.

Do you understand my doubts now? Looks like sampling can't be disabled.
Or maybe it's by design, sampling shouldn't be disabled and I can't trace all request?

**Comment by wronan** [comment]
I think I get it now - sorry for the mess.
`Sampler::AlwaysOn` records all data. To me such nomenclature seems a bit misleading because I'd bet my life on it that if "sampler" is ON then it means that incoming data will be sampled (meaning not all data is being stored). Apparently here it means something completely different.

Still wondering what `RecordOnly` variant of `SamplingDecision` is for though.
Seems like I have to dig deeper into the documentation.
Thanks you your attempts in helping me despite my ignorance @jtescher 
I think this issue may be closed.

**Comment by jtescher** [comment]
@wronan yeah the nomenclature in the spec is not always the most intuitive, feel free to open issues or PRs at https://github.com/open-telemetry/opentelemetry-specification to add clarity.
