### ISSUE TITLE
Define default for service.name

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#384]
See the spec change for details https://github.com/open-telemetry/opentelemetry-specification/pull/1269

**Comment by denismaxim0v** [comment]
Should be closed?

**Comment by ymtdzzz** [comment]
seems to be already defined?
https://github.com/open-telemetry/opentelemetry-rust/blob/879d6ff9d251db158da7a5720ff903fa6cb7c1e2/opentelemetry-sdk/src/resource/env.rs#L79-L97

**Comment by ivanitskiy** [comment]
I just tried a few things with [mini-redis](https://github.com/tokio-rs/mini-redis/blob/069a8e5ee0de445ad3e642548d196ef6b4fa8bc1/src/bin/server.rs#L71). It seems to me it doesn't use `CARGO_BIN_NAME`.

steps:
1. using this docker `docker run -d --rm --name jaeger -e COLLECTOR_OTLP_ENABLED=true -p 16686:16686 -p 4317:4317 -p 4318:4318 jaegertracing/all-in-one:latest`
2. start mini-redis server `RUST_LOG=debug cargo run --bin mini-redis-server --features otel`
3. set a value `RUST_LOG=debug cargo run --bin mini-redis-cli --features otel -- set foo bar `
4. then validate in Jaeger traces:
<img width="1253" alt="image" src="https://github.com/open-telemetry/opentelemetry-rust/assets/4936227/112d49c2-a560-4e70-a624-39ee614f1710">
5. it does use env variable  **OTEL_SERVICE_NAME** `OTEL_SERVICE_NAME=whatever RUST_LOG=debug cargo run --bin mini-redis-server --features otel`
<img width="1645" alt="image" src="https://github.com/open-telemetry/opentelemetry-rust/assets/4936227/a46711d9-e676-46e7-9d0c-5be5ead16bcf">

however when i change mini-redis code to use `CARGO_BIN_NAME` via  `with_resource()`:
```git diff
diff --git a/src/bin/server.rs b/src/bin/server.rs
index 701a1f1..ad4df39 100644
--- a/src/bin/server.rs
+++ b/src/bin/server.rs
@@ -12,12 +12,12 @@ use clap::Parser;
 use tokio::net::TcpListener;
 use tokio::signal;
 
-#[cfg(feature = "otel")]
-// To be able to set the XrayPropagator
-use opentelemetry::global;
 #[cfg(feature = "otel")]
 // To configure certain options such as sampling rate
-use opentelemetry::sdk::trace as sdktrace;
+use opentelemetry::sdk::{trace as sdktrace, Resource};
+#[cfg(feature = "otel")]
+// To be able to set the XrayPropagator
+use opentelemetry::{global, KeyValue};
 #[cfg(feature = "otel")]
 // For passing along the same XrayId across services
 use opentelemetry_aws::trace::XrayPropagator;
@@ -71,6 +71,10 @@ fn set_up_logging() -> Result<(), TryInitError> {
         .with_trace_config(
             sdktrace::config()
                 .with_sampler(sdktrace::Sampler::AlwaysOn)
+                .with_resource(Resource::new(vec![
+                    KeyValue::new("service.name", env!("CARGO_BIN_NAME")),
+                    KeyValue::new("service.version", env!("CARGO_PKG_VERSION")),
+                ]))
                 // Needed in order to convert the trace IDs into an Xray-compatible format
                 .with_id_generator(sdktrace::XrayIdGenerator::default()),
         )
```
<img width="1660" alt="image" src="https://github.com/open-telemetry/opentelemetry-rust/assets/4936227/6bd31f39-53af-4ae8-9d2f-18d903b2ad23">

**Comment by djc** [comment]
Maybe open a new issue and refer to the relevant PR to make sure this doesn't get lost?
