### ISSUE TITLE
Propagate Resource from Span to proto (Tonic)

### ISSUE THREAD

**Issue by markdingram** [open-telemetry/opentelemetry-rust#386]
The excellent change to add Tonic in https://github.com/open-telemetry/opentelemetry-rust/pull/352 didn't inherit the fix to populate Resource from the Span to proto from https://github.com/open-telemetry/opentelemetry-rust/pull/366

Will provide a PR unless something is already in the works?

**Comment by jtescher** [comment]
Ah yeah looks like that one got missed, PRs appreciated 👍

**Comment by markdingram** [comment]
this was merged in https://github.com/open-telemetry/opentelemetry-rust/commit/4390213c700443369e6b34bedf754ccb81c208eb
