### ISSUE TITLE
prometheus: metrics keep increasing on their own

### ISSUE THREAD

**Issue by MatteoJoliveau** [open-telemetry/opentelemetry-rust#394]
Hi folks! I'm experiencing a weird behaviour with the `opentelemetry-rust` crate and Actix Web.

Here's what's happening:

Whenever a metric is kicked off, it starts increasing on its own without any other interaction with the system. E.g. A counter increasing on every HTTP request keeps ticking up even if no requests are coming in.

I prepared a little [repro project](https://github.com/matteojoliveau/actix-prom-bug) with 3 examples: one using [actix-web-opentelemetry](https://docs.rs/actix-web-opentelemetry) (basically just a wrapper around `opentelemetry-prometheus` with an Actix middleware to record HTTP metrics and the `/metrics` endpoint implementation), one using `opentelemetry-prometheus` directly to expose the `/metrics` endpoint, and one using the [prometheus](https://docs.rs/prometheus) crate on its own,

The pure-prometheus example works fine, the other two present the described behaviour.

I'm having a hard time figuring out why this is happening, and if I'm either doing something wrong or if the problem is elsewhere.

Anyone has any idea?

**Comment by jtescher** [comment]
Thanks for reporting this, I think there is an issue merging metrics that could cause this.

**Comment by TommyCpp** [comment]
The bug I observe is that we "replay" the last delta of the sum when we refresh the metrics page. For example, if I access the greeter 3 times. Then check the metrics page. The value would be 3, 6, 9... for each time I refresh the metrics page.

I think the issue is here we added the sum of the aggregator from the instrument into the aggregator from the processor. But we didn't reset the sum in instrument. 
https://github.com/open-telemetry/opentelemetry-rust/blob/1bcbe77d4f87eccf20028cbbb4aaf3b7aad7ec5d/opentelemetry/src/sdk/metrics/processors/basic.rs#L137-L138

Reset the `other_sum` here to zero should fix this.
https://github.com/open-telemetry/opentelemetry-rust/blob/1bcbe77d4f87eccf20028cbbb4aaf3b7aad7ec5d/opentelemetry/src/sdk/metrics/aggregators/sum.rs#L70-L77

**Comment by jtescher** [comment]
@TommyCpp thanks for looking into this. Should that line actually be `if stale && stateless && !has_memory`?

**Comment by TommyCpp** [comment]
> @TommyCpp thanks for looking into this. Should that line actually be `if stale && stateless && !has_memory`?

Yeah that's a bug. But not the one that causing it. We should have something like this
```rust
           // The following branch updates stateful aggregators. Skip these updates
            // if the aggregator is not stateful or if the aggregator is stale.
            if stale || stateless {
                // If this processor does not require memory, stale, stateless
                // entries can be removed. This implies that they were not updated
                // over the previous full collection interval.
                if stale && stateless && !has_memory {
                    return false;
                }
                return true; // if it's stale. Skip the remaining part that update the cumulative  since there is no point to update it if there is no changes since last collection.
            } 
```
So the real issue is that we updated the cumulative value with the current value when there is no updated in this round of collection.

**Comment by jtescher** [comment]
@TommyCpp was preparing to cut a release. Let me know when you have something ready and we can get this fix in 👍

**Comment by TommyCpp** [comment]
@jtescher Sorry I forget it earlier. Opened it. 

Also, I think the `opentelemetry.rs` of this repro project can be a good example of `opentelemetry-rust`. I guess we can include it?

**Comment by jtescher** [comment]
@TommyCpp either way. The examples here are a little prometheus specific in that it explicitly renders in that format. Think the metrics examples that aren't otlp seem to do better within the context of the exporter

**Comment by MatteoJoliveau** [comment]
Let me say I'm absolutely astonished at the speed and efficiency this issue was accepted and fixed. I opened it with the hope of gathering more information about the problem at hand and maybe get some insight into the library to work around it while waiting for a fix. Never would I expect to have it patched so quickly. I can only thank you folks so much, I can get back to my work now and confidently adopt OTel in my project knowing that it's backed by such friendly individuals.

I'll wait for the next release to get back to metrics exposition, thank you so much @TommyCpp and @jtescher!
