### ISSUE TITLE
Split Jaeger exporter into its own crate

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-rust#4]
This will remove the main crate's dependency on Jaeger.

See the [cargo workspace docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-workspace-section) for more info on how we can accomplish this.

**Comment by iredelmeier** [comment]
This might be a bit trickier than I initially thought since the SDK currently depends on code from the Jaeger exporter.

**Comment by jtescher** [comment]
Could possibly add a `trace` feature that would accomplish a similar goal considering that currently there is only jaeger support
