### ISSUE TITLE
Move integration code out of the main opentelemetry crate

### ISSUE THREAD

**Issue by djc** [open-telemetry/opentelemetry-rust#403]
Into separate integration crates. This makes for more smaller crates, but makes sure we don't have dependencies in the core that we shouldn't have (which causes to have to upgrade in lockstep with their releases).

**Comment by djc** [comment]
Things that probably qualify:

* async-std
* bincode?
* regex?
* tokio
* tonic
* reqwest
* surf

**Comment by jtescher** [comment]
👍 could also consider http and the testing utils as candidates

**Comment by TommyCpp** [comment]
For proto definition. I'd suggest we move it to a separate it into separate crate(`opentelemetry-proto` maybe)? And support `grpcio` or `tonic` there.

**Comment by djc** [comment]
If we need to support grpcio *and* tonic, those should probably be two separate crates IMO.

**Comment by djc** [comment]
I spent the morning looking at this. The `Injector` and `Extractor` interfaces are tricky, because coherence requires that implementations for foreign types live in the same crate as the trait definitions. I did some experiments with using propagator types that implemented `Extractor<T>` (with `T` something like `http::HeaderMap`), but this clashes with the design of the global propagator, which cannot easily abstract over a particular type of propagator.

I did remove the regex dependency (#411, in favor of a small function that validates the trace state key) and moved bincode to dev-dependencies (#413, along with some other dependency management).

**Comment by djc** [comment]
#415 moves the dependencies on http, reqwest and surf into a separate opentelemetry-http crate. At this point I'm inclined to leave tokio and async-std in, as they're pretty stable anyway (especially now that tokio has gone 1.0).

**Comment by jtescher** [comment]
@djc is the work related to this issue complete? or should we keep this issue open

**Comment by TommyCpp** [comment]
I want to mention that we need to update the doc in `opentelemetry/lib.rs`. Especially the `Crate Feature Flags` part.
https://github.com/open-telemetry/opentelemetry-rust/blob/f79586b4caae79d26abd3e6ba69fa230c7c68f0e/opentelemetry/src/lib.rs#L36-L54

**Comment by djc** [comment]
@TommyCpp thanks for taking care of the documentation update.

I think this ticket is complete, closing.

**Comment by TommyCpp** [comment]
@jtescher @djc I don't think we published the `opentelemetry-aws` and `opentelemetry-datadog`. Should we do that?

**Comment by jtescher** [comment]
@TommyCpp yeah I think we could probably cut a new release, want to prepare the changelogs?
