### ISSUE TITLE
Upgrade to Tokio 1.0

### ISSUE THREAD

**Issue by alexkirsz** [open-telemetry/opentelemetry-rust#420]
rust-opentelemetry currently depends on Tokio 0.2. [Tokio 1.0 released on December 22](https://tokio.rs/blog/2020-12-tokio-1-0) and some of the ecosystem has started moving over to it ([hyper](https://github.com/hyperium/hyper/blob/master/CHANGELOG.md#v0140-2020-12-23), [reqwest](https://github.com/seanmonstar/reqwest/blob/HEAD/CHANGELOG.md#v0110), [rusoto](https://github.com/rusoto/rusoto/blob/master/CHANGELOG.md#0460---2021-01-05), etc.).

**Comment by mraerino** [comment]
i'm working on this

**Comment by mraerino** [comment]
Fix here: https://github.com/open-telemetry/opentelemetry-rust/pull/421
