### ISSUE TITLE
PipelineBuilder::with_collector_endpoint API is error prone

### ISSUE THREAD

**Issue by danburkert** [open-telemetry/opentelemetry-rust#426]
When passing a malformed URI to [`PipelineBuilder::with_collector_endpoint`](https://github.com/open-telemetry/opentelemetry-rust/blob/b2ab7996c6dcc5f0df6ee4185570d156f7c969ff/opentelemetry-jaeger/src/exporter/mod.rs#L211), the failure to parse the URI is silently discarded and trace collection is not enabled.  This is easy to mess up, for instance by passing `127.0.0.1:14268/api/traces` instead of `http://127.0.0.1:14268/api/traces`.

**Comment by jtescher** [comment]
Few options here, could have the builder accept a `http::Uri` directly, or warn using the global error handler if invalid, or change to `Option<Result<http::Uri>>` and have the builder return an error if the uri is not valid.

**Comment by djc** [comment]
The first option seems neat but would make it a little harder to use. The last option sounds good to me.
