### ISSUE TITLE
Rename batch span processor delay and timeout env vars

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#434]
See the spec change for details https://github.com/open-telemetry/opentelemetry-specification/pull/1325

**Comment by samschlegel** [comment]
Just leaving a note that when this is done we should make sure to keep compatibility with the old env vars, as reverting back to the defaults for these values can lead to silently dropped spans. 

Might try tackling https://github.com/open-telemetry/opentelemetry-rust/issues/272 in the next couple weeks which could help people catch regressions like that
