### ISSUE TITLE
Add macros!

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-rust#47]
This might take some experimentation to get right ergonomically.

**Comment by jtescher** [comment]
Closing this for now, can re-open if there is renewed interest in creating a more ergonomic macro API

**Comment by schickling** [comment]
I'd definitely love to see what a macro-based API could look like. The current Otel Rust API is fairly verbose and increases the app code footprint significantly.

**Comment by TommyCpp** [comment]
I think while we explore the opportunity.  https://github.com/tokio-rs/tracing has a set of macro API and it has integration with open telemetry repo so this maybe a temporary solution
