### ISSUE TITLE
opentelemetry-otlp how to name service: OTLPResourceNoAttributes

### ISSUE THREAD

**Issue by clux** [open-telemetry/opentelemetry-rust#475]
Currently, all my traces show up as top level `OTLPResourceNoAttributes`:

![trace viewer screenshot](https://user-images.githubusercontent.com/134092/110450403-12591600-80bb-11eb-8f8b-447b0a44cd61.png)

Is there a way to inject the service name with `opentelemetry-otlp` like in [opentelemetry-jaeger](https://docs.rs/opentelemetry-jaeger/0.11.0/opentelemetry_jaeger/struct.PipelineBuilder.html#method.with_service_name)?

**Comment by TommyCpp** [comment]
There isn't a service name concept in OTEL. So the [convention](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#resource) here(and in opentelemetry-jaeger) is to use `service.name` resource to represent the service name

**Comment by clux** [comment]
Hm, ok. I could open a bug against Tempo in that case.

Btw, in golang the way I see this is done is by naming the tracer:
https://github.com/joe-elliott/tempo-otel-example/blob/492add7ad56769c0b0bbc80499f42dcb8cde8131/main.go#L47-L50
which gets picked up by Tempo.

**Comment by TommyCpp** [comment]
> Btw, in golang the way I see this is done is by naming the tracer:
> https://github.com/joe-elliott/tempo-otel-example/blob/492add7ad56769c0b0bbc80499f42dcb8cde8131/main.go#L47-L50
> which gets picked up by Tempo.

Actually, that is the instrument library name, which will appear as a tag `otlp.instrumentation.library.name` in Jaeger. The service name is setup here https://github.com/joe-elliott/tempo-otel-example/blob/492add7ad56769c0b0bbc80499f42dcb8cde8131/main.go#L115-L119. You should see the service name as `demo-service` instead of `demo-app`.

So I think Tempo does check the `service.name`. Mind share an example of how do you set up the `service.name` resource in Rust?

**Comment by clux** [comment]
Oh, yes, you are right, I do see `demo-service`.

The way I did it in rust was to set the fields with `#[insturment]`:

```rust
#[instrument(skip(ctx), fields(traceID, service.name = "foo-controller"))]
async fn reconcile(foo: Foo, ctx: Context<Data>) -> Result<ReconcilerAction, Error> {
    Span::current().record("traceID", &field::display(&telemetry::get_trace_id()));
```

which shows up on the interface, but as a tag rather than the service name:
![Screenshot from 2021-03-10 18-01-09](https://user-images.githubusercontent.com/134092/110675384-b978a300-81ca-11eb-9fd2-a8af17f1a058.png)

**Comment by clux** [comment]
Ahhh, it's a Resource. Thank you.

Added:

```
        .with_trace_config(opentelemetry::sdk::trace::config().with_resource(
            opentelemetry::sdk::Resource::new(vec![opentelemetry::KeyValue::new("service.name", "foo-controller")]),
        ))
```

and it worked.

**Comment by TommyCpp** [comment]
Good to know. Since this was defined in spec, we do have a const value for `service.name`. You can find it here https://github.com/open-telemetry/opentelemetry-rust/blob/e9595b67ba9ecf60abd92c44637baab146cbe870/opentelemetry-semantic-conventions/src/resource.rs#L27
