### ISSUE TITLE
Add OTLP span exporter using HTTP/Binary protocol

### ISSUE THREAD

**Issue by TommyCpp** [open-telemetry/opentelemetry-rust#477]
As per [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp). Add a OTLP exporter using http and binary.

Also may need to think about how do we build a builder pipeline to allow users to choose transportation protocol and request body format.

**Comment by danrusei** [comment]
If no one is working on this, I could give it a try.
