### ISSUE TITLE
env tag for DatadogExporter

### ISSUE THREAD

**Issue by andoriyu** [open-telemetry/opentelemetry-rust#478]
Unless I'm missing something there is no way to add `env` tag to spans that get sent to datadog? Without that tag all instances of a service would be grouped into a single service on DD side.

**Comment by andoriyu** [comment]
Never mind, I figured it out. I could use https://docs.rs/opentelemetry/0.12.0/opentelemetry/sdk/trace/struct.Config.html#method.with_resource for such task.

**Comment by siyopao** [comment]
Hi! Sorry, I am running in to the same problem and I am trying `with_resource` but it doesn't seem to work. What I have is
```
opentelemetry_datadog::new_pipeline()
        .with_service_name("whatever")
        .with_trace_config(
            trace::config().with_resource(Resource::new(vec![KeyValue::new(
                "env", "foo"
            )])),
        )
```
but the traces are still ending up in `env:none`. Is this the approach you used?

Thanks!
