### ISSUE TITLE
Will the datadog exporter automatically correlate logs and traces?

### ISSUE THREAD

**Issue by GSGerritsen** [open-telemetry/opentelemetry-rust#484]
If I use the `opentelemetry-datadog` crate, would I need to manually inject `trace_id` and `span_id` into logs somehow (such as in [this guide](https://docs.datadoghq.com/tracing/connect_logs_and_traces/opentelemetry)) or would this happen automatically?

I'm currently attempting to do this (using the `tracing` crate) like this:
```
info!(
    dd.trace_id = trace_id.to_u128() as u64, 
    dd.span_id = span_id.to_u64(),
    ...rest of the data
);
```
But the logs aren't being extracted from the traces in the APM dashboard. So I'm wondering if it might be easier to just use the datadog crate directly. I'm currently using `opentelemetry_otlp` as the pipeline, which sends to an opentelemetry collector, which then sends to datadog.

Edit: it actually looks like `opentelemetry-datadog` hasn't been published yet, so as an additional question is there any update on when that might be available?

**Comment by TommyCpp** [comment]
There is currently no correlation between logs and traces, so you will have to do it manually. As for the crate itself, we are just finishing up few PRs before we push the next release. So it should be out soon
