### ISSUE TITLE
opentelemetry_otlp not support uds endpoint

### ISSUE THREAD

**Issue by quanweiZhou** [open-telemetry/opentelemetry-rust#486]
use unix domain socket address get err : ExportFailed(InvalidUri(InvalidUri(InvalidFormat)))

**Comment by TommyCpp** [comment]
We don't currently support building the otlp exporter using tonic with UDS. Although UDS is supported by tonic, it requires a different configuration from other addresses. But it would be nice to have that feature, will mark this as a positional improvement.

**Comment by quanweiZhou** [comment]
@TommyCpp version = "0.14.0"  
opentelemetry_otlp::new_pipeline has already support UDS
but opentelemetry_otlp::new_metrics_pipeline not support UDS

**Comment by TommyCpp** [comment]
@quanweiZhou Yeah I delayed the implementation mostly because we need some work on the metrics provider builder to make it consistent with the tracer provider builder. But we can add it if needed.
