### ISSUE TITLE
Flushing spans without shutting down the instrumentation

### ISSUE THREAD

**Issue by LukeMathWalker** [open-telemetry/opentelemetry-rust#499]
Is there a way to trigger flushing of all in-flight spans without shutting down the instrumentation?
E.g. a flushing equivalent of [`global::shutdown_tracer_provider`](https://docs.rs/opentelemetry/0.13.0/opentelemetry/global/fn.shutdown_tracer_provider.html)?

**Comment by jtescher** [comment]
Yeah the tracer provider API needs to expose a method to access [`SpanProcessor::force_flush`](https://docs.rs/opentelemetry/0.13.0/opentelemetry/sdk/trace/trait.SpanProcessor.html#tymethod.force_flush).

**Comment by TommyCpp** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#forceflush
Could just invoke the `forcepush` method of global tracer provider
