### ISSUE TITLE
Split Prometheus exporter into its own crate

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-rust#5]
This will remove the main crate's dependency on Prometheus.

See the [cargo workspace docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-workspace-section) for more info on how we can accomplish this.

**Comment by iredelmeier** [comment]
This is a bit trickier than I initially thought since the SDK currently depends on code from the Prometheus exporter.

**Comment by jtescher** [comment]
This could also be a `metrics` feature, making the dependency optional
