### ISSUE TITLE
Datadog crates enables reqwest's default features...

### ISSUE THREAD

**Issue by fasterthanlime** [open-telemetry/opentelemetry-rust#513]
...which forces a dependency on OpenSSL.

I feel like this line:

https://github.com/open-telemetry/opentelemetry-rust/blob/4d58d4b7d9c5377012f6dfb6e675b87625a04762/opentelemetry-datadog/Cargo.toml#L32

should include `default-features = false`, so that downstream crates can specify what reqwest features they'd like.

**Comment by djc** [comment]
Yup, that would make sense. Would you mind submitting a PR?
