### ISSUE TITLE
Batch span processor on_end mutex

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#520]
It would be nice to remove the mutex around the batch span processor channel to avoid locking when exporting spans. https://github.com/open-telemetry/opentelemetry-rust/blob/607b32a417e9d6e3cc1353135649d95ba2377e6c/opentelemetry/src/sdk/trace/span_processor.rs#L232-L240

**Comment by TommyCpp** [comment]
Maybe we could just clone the `sender`?. Internally it's just `Arc`s so the clone operation should be light. 
The only concern one might have is too many senders could cause OOM as the capacity of the bound channel is `capacity + num of sender`. But then `try_send` is non-blocking and all the cloned sender should be dropped when the function returns.

**Comment by jtescher** [comment]
@TommyCpp could try, may be useful to look at the benchmarks and try a few approaches. I think cloning was slower last time I tried for some reason.

**Comment by TommyCpp** [comment]
I built a [benchmark](https://github.com/TommyCpp/opentelemetry-rust/blob/tommycpp/issue-520/opentelemetry/benches/batch_span_processor.rs) with tokio runtime. The preliminary result on removing mutex seems to be promising. 
```
Benchmarking BatchSpanProcessor/batch span processor: Collecting 5000 samples in estimated 7.2104 s (5000                                                                                                           BatchSpanProcessor/batch span processor                        
                        time:   [1.5888 ms 1.5997 ms 1.6113 ms]
                        change: [-44.416% -43.990% -43.497%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 178 outliers among 5000 measurements (3.56%)
  5 (0.10%) low mild
  46 (0.92%) high mild
  127 (2.54%) high severe
```
