### ISSUE TITLE
Add support for OTEL_EXPORTER_JAEGER_TIMEOUT

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#528]
See the spec change for more details https://github.com/open-telemetry/opentelemetry-specification/pull/1612

**Comment by drexler** [comment]
@jtescher mind assigning this to me? Thanks.

**Comment by drexler** [comment]
@jtescher  finally got round to this. Quick question, with [`surf` lacking support for timeouts](https://github.com/http-rs/surf/issues/274), would using `isahc` as a backing client for surf be an ok approach with this? Most likely, this will need a documentation update to accompany that to let users know it's not a pure `surf` http client under the hood when opting for that as their http client.

**Comment by jtescher** [comment]
@drexler could you [`select`](https://docs.rs/futures/0.3.14/futures/future/fn.select.html) between the surf request and an [`async_std::future::timeout`](https://docs.rs/async-std/1.9.0/async_std/future/fn.timeout.html)? Surf support exists mainly to facilitate the async-std ecosystem currently I believe.
