### ISSUE TITLE
Update Cargo.toml authors?

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-rust#53]
@jtescher thoughts on updating the `authors` to point to something generic, like "OpenTelemetry authors"? Not sure if there's a corresponding email.

**Comment by jtescher** [comment]
Yeah that seems best. I copied the name / email from [ruby impl](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/api/opentelemetry-api.gemspec#L14-L15) for the jaeger exporter, could go with that https://github.com/open-telemetry/opentelemetry-rust/blob/master/opentelemetry-jaeger/Cargo.toml#L4
