### ISSUE TITLE
Add a Base64 decoder

### ISSUE THREAD

**Issue by xd009642** [open-telemetry/opentelemetry-rust#54]
Often span IDs between applications are encoded into base64, currently you need to use an external crate i.e. https://crates.io/crates/base64 it would be more user friendly

**Comment by jtescher** [comment]
@xd009642 are you interested in contributing a PR for this? I'd be happy to help you get started.

**Comment by xd009642** [comment]
Yeah I can take a look some point this week

**Comment by xd009642** [comment]
Quick question would the preferred way be to do a separate base64 propagator? Or to more simply just add a trait similar to `BinaryFormat` to the `BinaryPropagator` called `Base64Format`?

**Comment by MikeGoldsmith** [comment]
I think an additional trait would be the right way - different propagator implementations may want the base64 encoded string.
