### ISSUE TITLE
otlp surf support enables default curl client

### ISSUE THREAD

**Issue by joshtriplett** [open-telemetry/opentelemetry-rust#544]
I'd like to use surf with `h1-client-rustls`, rather than the default `curl-client`. Would it be possible for otlp's surf support to use `default-features = false` and support whatever the default surf client is?

**Comment by TommyCpp** [comment]
You could implement [`HttpClient`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-http/src/lib.rs#L48-L56). Then you can build your own HTTP client and set it via [`HttpConfig`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/src/span.rs#L204-L210) to OTLP pipeline.

**Comment by joshtriplett** [comment]
I realize that, but it would be nice to use the existing built-in support and just disable the specific feature forcing the use of curl-client.

**Comment by jtescher** [comment]
@joshtriplett is #546 what you had in mind?
