### ISSUE TITLE
Allow option to split oversiezd jaeger UDP batches

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#545]
Currently the Jaeger exporter will simply error if the batch size is too large. It would be better to have an option to split and export multiple sub-batches instead.

**Comment by DCjanus** [comment]
From [this line](https://github.com/open-telemetry/opentelemetry-rust/blob/ae4aeb364cd7054fe43a6fee8d340b6959624f3c/opentelemetry-jaeger/src/exporter/agent.rs#L71), looks like the only way to known actual size of payload, is actual write batch to buffer.

That means, to split oversized batches, maybe we have to code like this:

```
FUNCTION EMIT( BATCH ):
    WRITE ( BUFFER )
    IF LEN ( BUFFER ) <= SIZE_LIMIT:
        WRITE_TO_SOCKET ( BUFFER )
        RETURN
    HALF_A, HALF_B = SPLIT( BATCH )
    EMIT ( HALF_A )
    EMIT ( HALF_B )
```

I'm not sure is this ok

**Comment by jtescher** [comment]
@DCjanus yes that looks like the right approach
