### ISSUE TITLE
Need for a Viable Security Scanning Tool 

### ISSUE THREAD

**Issue by xyira** [open-telemetry/opentelemetry-rust#557]
A security workflow does not currently exist as part of the CI/CD or security workflows in the Rust repository. This is necessary to satisfy the security requirements of https://github.com/open-telemetry/opentelemetry-specification/issues/1333.

CodeQL is the common security scanning tool that is used currently for all of the supported OpenTelemetry language repositories (Go, Java, Javascript, Python, C++, etc.). Unfortunately CodeQL does not offer support for Rust. Thus an alternative would need to be found. 

We evaluated different possibilities but there seems to be limited available code scanning tools for Rust that could be integrated with Github Actions. The following code scanning tools for Rust could work:

* [Rust Audit Check](https://github.com/actions-rs/audit-check). This tool however only checks for reported security vulnerabilities in dependencies

We’d like to better understand the opinions from Rust engineers on a recommended code scanning tool so that one may be added for https://github.com/open-telemetry/oteps/issues/144. 

cc @KKelvinLo @alolita

**Comment by djc** [comment]
I like to use cargo-deny, which will check for vulnerable dependencies but can also help checking for inappropriate licenses and duplicate dependency versions.

**Comment by TommyCpp** [comment]
Should we also consider adding a license check? I ran a quick check with `cargo deny`. The only crate that seems to be a problem is `ring`. It contains a custom LICENSE file. The template in `cargo deny` describes `ring`'s LICENSE as `MIT AND ISC AND OpenSSL`. I suppose this is compatible with our repo's license?
