### ISSUE TITLE
Project LICENSE file is Apache 2.0, but README badge and crates.io shows MIT.

### ISSUE THREAD

**Issue by rthomas** [open-telemetry/opentelemetry-rust#57]
I'm unsure if crates.io thinks this is MIT because previous releases were done under MIT - but the LICENSE file and Github both show this as Apache 2.0.

**Comment by MikeGoldsmith** [comment]
Hi @rthomas - I don't believe pushed another release to crates.io. I suspect that, along with other project metadata, will up date once we have.

**Comment by rthomas** [comment]
Excellent, thanks - I suspected it was tied to the release on crates.io - I just wasn't sure where the badge pulled the details from.

I'll close this, as I think you're right and it'll fix itself up when you push a new release.
