### ISSUE TITLE
Add serialize attributes for SpanData

### ISSUE THREAD

**Issue by jodh-intel** [open-telemetry/opentelemetry-rust#58]
I'd like to be able to serialise and deserialise the public `SpanData` [1]. Since all of its fields are public I *could* do that manually or even use the magic "remote derive" feature of serde [2]. However, from a safety and usability perspective adding the standard `#[derive(Serialize, Deserialize)]` to `SpanData` would allow standard serde semantics.

---

[1] - https://github.com/kata-containers/kata-containers/issues/60
[2] - https://serde.rs/remote-derive.html

**Comment by jodh-intel** [comment]
btw, do you have any thoughts on when you plan to update the crate version (since `SpanData` isn't available in the latest `0.1.5` release on crates.io)?

**Comment by MikeGoldsmith** [comment]
Hi @jodh-intel 

We don't have a set date for our next release to crates.io, though it has been a while and there have been a lot of changes since the last release (including moving github org).

**Comment by jodh-intel** [comment]
Thanks @MikeGoldsmith - I've tried using the latest git repo version but it got messy due to other deps (and their particular versioned deps) so would be great to be able to consume direct from crates.io ideally.

@jtescher - do you think adding these serialisation options is reasonable?

**Comment by jtescher** [comment]
@jodh-intel yeah `SpanData` being serialize/deserialize seems reasonable to me. Want to do the PR? (always good to have more committers 😃)

As far as a release, once the current open PR's land we can likely get a release ready. The current issues around how current span tracking works with futures is the real meat of the outstanding work to be done.

**Comment by jodh-intel** [comment]
Thanks @jtescher - here you go: https://github.com/open-telemetry/opentelemetry-rust/pull/59 :smile:
