### ISSUE TITLE
Rename metrics labels to attributes

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#591]
See the spec change for details https://github.com/open-telemetry/opentelemetry-specification/pull/1775

**Comment by LanceEa** [comment]
@TommyCpp  - I can grab this one, if no one has yet. 

It looks like it will be removed from `opentelemetry-proto` 3 months from July 1st so around September.

https://github.com/open-telemetry/opentelemetry-proto/blob/60fa8754d890b5c55949a8c68dcfd7ab5c2395df/opentelemetry/proto/metrics/v1/metrics.proto#L314

**Comment by TommyCpp** [comment]
Sounds good. I think I did something similar a few months ago. Mostly update the proto-generated files and our transformation between types.
