### ISSUE TITLE
Consider using Options instead of Noop implementations

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-rust#6]
We should probably spike on this in a PR to see the implications on semantics, implementation, etc.

**Comment by jtescher** [comment]
@iredelmeier could you elaborate here a bit? Are you thinking it the SDK would accept and produce options instead of a separate impl?

**Comment by hawkw** [comment]
IMO, I think it's better for noops to be separate types; that way the dispatch is done statically & it's encoded in the type system. `Option` implies a bunch of runtime checks to me?

**Comment by jtescher** [comment]
Closing this for now, we can re-open later if there is interest in examining alternatives.
