### ISSUE TITLE
OpenTelemetry trace error: ConnectError

### ISSUE THREAD

**Issue by dorrabb** [open-telemetry/opentelemetry-rust#617]
Hello,

The use of the OpenTelemetry crate to send logs to datadog produces logs with the following error every now and then:

`OpenTelemetry trace error occurred Other(Custom("failed to export batch Other(reqwest::Error { kind: Request, url: Url { scheme: \"http\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"datadog-agent\")), port: Some(8126), path: \"/v0.5/traces\", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError(\"dns error\", Custom { kind: Other, error: \"failed to lookup address information: Name does not resolve\" })) })"))
` 

Everything else works perfectly - the traces are being recorded and the logs are being sent associated with each trace. Here is how the code is implemented:

```
let tracer = new_pipeline()
    .with_service_name(name)
    .with_version(ApiVersion::Version05)
    .with_agent_endpoint("http://datadog-agent:8126")
    .with_trace_config(
        trace_lib::config()
            .with_sampler(Sampler::AlwaysOn)
            .with_id_generator(IdGenerator::default())
)
    .install_batch(opentelemetry::runtime::Tokio)
    .unwrap();

let opentelemetry = tracing_opentelemetry::layer().with_tracer(tracer);

let _ = tracing_subscriber::registry()
    .with(EnvFilter::from_default_env().add_directive("hyper=error".parse().unwrap_or_default()))
    .with(tracing_subscriber::fmt::Layer::new()
    .json().flatten_event(true).with_writer(std::io::stdout))
    .with(opentelemetry)
    .try_init().map_err(|err|anyhow::anyhow!(err));

let tracer = opentelemetry::global::tracer("tracer");
let span = tracer.span_builder("span")
            .with_attributes(vec![KeyValue::new("foo", "bar")])
            .start(&tracer);
async {
    // do something
}.with_context(Context::current_with_span(span)).await; 
```

Any help would be appreciated a lot. Thanks!

**Comment by TommyCpp** [comment]
Sorry for the late response, I think the error is `failed to lookup address information: Name does not resolve`. I would suggest double-checking the data dog agent to make sure it's accessible from the application. Other than that, the code looks good to me.

**Comment by TommyCpp** [comment]
Looks like there are no further questions here. If there is, please feel free to reopen this issue with questions. Thanks.
