### ISSUE TITLE
AWS Lambda: recommendations?

### ISSUE THREAD

**Issue by davidarmstronglewis** [open-telemetry/opentelemetry-rust#620]
I'm trying to get started with using opentelemetry to instrument some Rust Lambdas I'm running in AWS by pushing traces to DataDog. It looks like the examples are assuming I have an exporter running as a sidecar container reachable on the local network. That doesn't make as much sense in the context of AWS Lambda. Does anyone have any suggestions of where to start or where I can look for guidance?

Thanks all <3

**Comment by TommyCpp** [comment]
The Rust SDKs only require an endpoint that supports the datadog protocol and is accessible from the application to push spans. So you don't necessarily have to run an exporter/agent.

**Comment by davidarmstronglewis** [comment]
Ah, so there's a way to push spans directly to DataDog - cool! I'll close this issue then as it seems this is supported. It probably requires setting an API Key to be provided via a header, if you happen to know where to provide this I'd love to know.

Closing, and thank you.
