### ISSUE TITLE
Cannot use gRPC roots on macOS

### ISSUE THREAD

**Issue by maxcountryman** [open-telemetry/opentelemetry-rust#623]
Hello,

It seems the [`opentelemetry-otlp` example](https://github.com/open-telemetry/opentelemetry-rust/blob/a0899d9ed595343e9d4eb2dbd994235dedb501ed/examples/external-otlp-grpcio-async-std/src/main.rs) involving e.g. Honeycomb aren't working on macOS and result in an error something along the lines of:

```
E0829 15:47:47.733447000 123145469861888 ssl_utils.cc:588]             load_file: {"created":"@1630277267.733416000","description":"Failed to load file","file":"/Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.9.0+1.38.0/grpc/src/core/lib/iomgr/load_file.cc","file_line":72,"filename":"/usr/share/grpc/roots.pem","referenced_errors":[{"created":"@1630277267.733415000","description":"No such file or directory","errno":2,"file":"/Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.9.0+1.38.0/grpc/src/core/lib/iomgr/load_file.cc","file_line":45,"os_error":"No such file or directory","syscall":"fopen"}]}
E0829 15:47:47.733490000 123145469861888 ssl_security_connector.cc:423] Could not get default pem root certs.
E0829 15:47:47.733503000 123145469861888 secure_channel_create.cc:108] Failed to create secure subchannel for secure name 'api.honeycomb.io:443'
E0829 15:47:47.733529000 123145469861888 secure_channel_create.cc:50]  Failed to create channel args during subchannel creation.
E0829 15:47:47.733593000 123145469861888 ssl_security_connector.cc:423] Could not get default pem root certs.
```

Indeed, `/usr/share/grpc/roots.pem` does not exist; gRPC was installed with Homebrew and `roots.pem` can be found at `/usr/local/opt/grpc/share/grpc/roots.pem` instead.

I'm having trouble figuring out how to configure this and at this point I'm unsure if it's possible. (Note that macOS doesn't allow superuser write access to `/usr/share` due to SIP.)

**Comment by TommyCpp** [comment]
👋 Hello, could you try set the `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` env var and see if it can override the path?

**Comment by TommyCpp** [comment]
It seems to work for other users. Will close this for now, feel free to reopen if the problem presists
