### ISSUE TITLE
Example usage of _tracing and _prometheus?

### ISSUE THREAD

**Issue by seanpianka** [open-telemetry/opentelemetry-rust#624]
Hello 👋 An application I'm working on is instrumented with `tracing::instrument`, and now I'm trying to hook in `opentelemetry_tracing` and `opentelemetry_prometheus` to send metrics data regarding all the spans/events of my application to Prometheus (so that they could be visualized in Grafana).

Are there any examples of this integration available in this repo? My search has come up with nothing, and I am finding it difficult to re-use the `PrometheusExporter` with any pipeline/tracer instantiation since `PrometheusExporter` is not a `SpanExporter`. But perhaps I'm missing some fundamental understanding of opentelemetry... thanks!

**Comment by TommyCpp** [comment]
Please correct me if I understand it incorrectly. But Prometheus cannot handle spans data. Prometheus collects `metrics` data while spans belong to `tracing`. 

Grafana used to be a dashboard for metrics data. But I believe they developed a project called `Tempo` to allow Grafana to show spans as well. But you still need to collect metrics and spans somehow. Some tools like `opentelemetry-collector` allow you to push both metrics or tracing data to the same place while other tools like Prometheus or Jaeger may only handle one of them.
