### ISSUE TITLE
Prometheus metrics exporter builder does not allow customizing aggregation selector

### ISSUE THREAD

**Issue by Sushisource** [open-telemetry/opentelemetry-rust#633]
I'd expect a `with_aggregation_selector` method to exist on the `ExporterBuilder`, but it doesn't. Only way to customize is to part of the `try_init` method and use the deprecated `new` constructor on `PrometheusExporter`

Sorry for opening so many issues :smile:  but I figure better to know about them than not. I might be able to find some time to contribute some of these soon.

**Comment by TommyCpp** [comment]
No worries :smile:. Sorry I need to deal with some personal issues so didn't spend much time on the project in the past month. As always, contributions are welcome.

**Comment by Sushisource** [comment]
Looks like this is fixed now. Thanks!
