### ISSUE TITLE
Move website_docs back to website repo? (Decide by Oct 1)

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-rust#636]
As discussed at the [Sept 9 Comms][cm] and [Sept 13 Maintainers][mm] meetings, @open-telemetry/rust-maintainers have a choice to make regarding **how your docs** ([website_docs]) will be incorporated into **[opentelemetry.io]**.

For your **two choices** and other details, see https://github.com/open-telemetry/opentelemetry.io/issues/730. 

The Comms team can help implement either of these choices. We'd appreciate a **response by Oct 1**, after which we'll **assume** that you're ok with option (2) and initiate the **move  of [website_docs] back to [website repo][wr]**.

/cc @austinlparker @open-telemetry/rust-approvers

[website_docs]: https://github.com/open-telemetry/opentelemetry-rust/tree/main/website_docs
[opentelemetry.io]: https://opentelemetry.io/
[cm]: https://docs.google.com/document/d/1wW0jLldwXN8Nptq2xmgETGbGn9eWP8fitvD5njM-xZY/edit#heading=h.brwue8g3voai
[mm]: https://docs.google.com/document/d/14lBtLAdzsV7M8xQNdhTJ0d2PxM1R7FByw-GttKJzVVw/edit#heading=h.vannhusrul2x
[wr]: https://github.com/open-telemetry/opentelemetry.io/

**Comment by TommyCpp** [comment]
I think choice 2(move website_docs backend to website repo) would work for us. Any thoughts? @open-telemetry/rust-approvers

**Comment by jtescher** [comment]
Yep option 2 sounds good to me 👍

**Comment by chalin** [comment]
Ok, moving ahead with option (2), thanks.
