### ISSUE TITLE
Support building an HTTP SpanExporter

### ISSUE THREAD

**Issue by joshtriplett** [open-telemetry/opentelemetry-rust#640]
I'm trying to migrate from opentelemetry-rust 0.14 to 0.16. I'm using OTLP HTTP. In 0.14, I had this:

```rust
        opentelemetry_otlp::TraceExporter::new_http(
            opentelemetry_otlp::ExporterConfig {
                endpoint: "https://api.honeycomb.io/v1/traces".to_string(),
                protocol: opentelemetry_otlp::Protocol::HttpBinary,
                ..Default::default()
            },
            opentelemetry_otlp::HttpConfig {
                headers: Some(headers),
                ..Default::default()
            },
        )
```

But in 0.16, `HttpConfig` doesn't seem to be public anymore, so I can't create one to call `new_http`. I tried creating an `HttpExporterBuilder`, but once I'm done building, I don't see how to get from there to a `SpanExporter`, because `SpanExporterBuilder::build_span_exporter` is private.

What's the supported way to build a `SpanExporter` in 0.16?

Alternatively, a solution to https://github.com/open-telemetry/opentelemetry-rust/issues/540 (providing a function to write a `Vec<SpanData>` into the pipeline's channel) would make this unnecessary; the main reason I need a `SpanExporter` is to build my own pipeline by hand so that I have access to a channel sender to send additional spans.

**Comment by jtescher** [comment]
@TommyCpp seems [`build_span_exporter`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/src/span.rs#L205) should be public?

**Comment by TommyCpp** [comment]
Yes we should make it public
