### ISSUE TITLE
Implement a way to retroactively adjust `SpanContext` trace IDs

### ISSUE THREAD

**Issue by Sushisource** [open-telemetry/opentelemetry-rust#643]
In my project, almost everything that happens follows this pattern:

```rust
#[instrument]
async fn poll() -> Result<PollResult, PollError> {
    // Stuff happens in here, more spans get created, etc
    let res = poll_some_service().await;
    // Res contains information that would let me set the appropriate trace ID. Ideally
    // here I do something like:
    opentelemetry::Context::current_mut().set_trace_id(res.real_trace_id);
    // And now before the span is ended, the appropriate trace ID has been set
    res
}

async fn called_from_another_language(span_context: SpanContext) -> Result<PollResult, PollError> {
    let otel_ctx = opentelemetry::Context::new().with_remote_span_context(span_context);
    poll().with_context(otel_ctx).await
}
```

I need to pass in the span context so the spans created in rust are children of the correct span id. The original trace id is irrelevant, since it gets overwritten later in the calling language too. In the case of Javascript being the calling language, fixing up the original context is easy. I can literally just `span.spanContext().traceId = whateverIWant;`

However, there's no way to do this in Rust. I looked through the code for a bit and it looks like it wouldn't be the simplest thing to fit into the current design, but I imagine this is a reasonably common thing to want to do. It's pretty important to my use case so I could try to contribute if this makes sense.

**Comment by lonewolf3739** [comment]
[SpanContext](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spancontext)'s are immutable by design. 

> The original trace id is irrelevant, since it gets overwritten later in the calling language too

Why is it irrelevant? AFAIK language clients do not allow mutating the span context since that would lead to gaps in distributed tracing.

**Comment by TommyCpp** [comment]
As mentioned above, the spec says `SpanContext` is immutable. To me it looks like you want to delay the trace id assignment until the end of the span. i.e create a span and record but only assign the real trace id when it's ends.

It's an interesting use case which I don't believe it's possible at the moment.

**Comment by lonewolf3739** [comment]
@Sushisource I didn't fully understand what is the real world use case for your requirement, but you may want to look at span links https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#specifying-links

**Comment by jtescher** [comment]
You could also use a [`SpanBuilder`](https://docs.rs/opentelemetry/0.16.0/opentelemetry/trace/struct.SpanBuilder.html) and record your start time / state / trace id information that way, and then call [`Tracer::build`](https://docs.rs/opentelemetry/0.16.0/opentelemetry/trace/trait.Tracer.html#tymethod.build) once a sufficient amount of information is available to start an otel span.

**Comment by Sushisource** [comment]
Ah, I didn't realize the context was supposed to be immutable per the spec. @TommyCpp delaying trace id assignment until the end would work well too.

@lonewolf3739 Admittedly links should be perfectly suitable here, and is probably what I'll do for now. My problem is really a symptom of the fact that Jaeger's UI is terrible at displaying links. There's no way to show all spans which follow from some given span, which is what I care about. Having everything in one trace makes for an easy-to-see experience (plus is conceptually nice in my case).

@jtescher Problem with that is the span should start, and there are events I want to record in the span, all before I learn about the appropriate ID.
