### ISSUE TITLE
external-otlp-tonic-tokio fails under Windows OS

### ISSUE THREAD

**Issue by mikehentges** [open-telemetry/opentelemetry-rust#656]
The example program external-otlp-tonic-tokio fails under Windows OS. Error at console is: `OpenTelemetry trace error occurred. Exporter otlp encountered the following error(s): the grpc server returns error Unknown error` 

I can connect to the collector with a golang example program - so I believe the collector is OK. The rust external HTTP example also works.

I have another application I was trying to debug that runs under MacOS, but fails silently (no error, but traces are not produced) under Windows OS.

rust 1.55

**Comment by cijothomas** [comment]
@mikehentges Do you still need help here ? A few of the examples were refactored/removed. If you are still facing issue, could you helpby sharing a minimal repro?

**Comment by cijothomas** [comment]
Closing old issues without activity.
