### ISSUE TITLE
Jaeger: service.name is not with_service_name

### ISSUE THREAD

**Issue by taqtiqa-mark** [open-telemetry/opentelemetry-rust#657]
Using:

```rust
opentelemetry::sdk::trace::BatchSpanProcessor::builder(
        opentelemetry_jaeger::new_pipeline()
            .with_service_name("mre-jaeger")
            .with_agent_endpoint(addr)
            .with_tags(vec![opentelemetry::KeyValue::new("exporter", "jaeger")])
            .init_async_exporter(opentelemetry::runtime::Tokio).expect("Jaeger Tokio async exporter"),
        opentelemetry::runtime::Tokio,
    )
    .build();
 ```

Jaeger does not show a `service.name` entry:

![image](https://user-images.githubusercontent.com/1468258/138574545-f3a08106-0092-45be-9dc8-f75e22369357.png)

I understand the service name passed in is the service name all spans sit under.
It would be useful to be able to set this value within a span, perhaps to a different value.  However, I haven't been able to find any documentation on how to populate the `service.value` shown above.

**Comment by TommyCpp** [comment]
> > 1. As for the service name, it should generally follows
> > 
> > 
> > * starts with `unknown_service`(the default one)
> 
> [This description](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service) suggests the default should be `unknown_service:` (note the trailing `:`). That immediately raises the question how to set/override the executable name - but that is properly the subject of another issue.

Yes, the spec recommends having a execute name after the trailing `:`. We are figuring out a way to get that info from Rust. 



> > * `OTEL_SERVICE_NAME`
> 
> I did read [this specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md) to mean attention **could** be given to `OTEL_RESOURCE_ATTRIBUTES` for the service name before any code definitions. If that variable is ignored we can just make a comment to that effect in the docs?

Fixed in #662
