### ISSUE TITLE
Example request: setting service name with OTLP exporter

### ISSUE THREAD

**Issue by davechallis** [open-telemetry/opentelemetry-rust#712]
It would be handy if the [basic-otlp example](https://github.com/open-telemetry/opentelemetry-rust/tree/main/examples/basic-otlp) showed how to set the service name for a tracer, since this is a fairly crucial setting when tracing.

The example produces span with `unknown_service`, and I couldn't see an obvious way to set it.

A lot of other examples use the Jaeger exporter, which uses:
```rust
opentelemetry_jaeger::new_pipeline()
        .with_service_name("trace-demo")
```
but I couldn't find any similar function for `OtlpPipeline`.

**Comment by TommyCpp** [comment]
So OTLP doesn't have a service name configuration. Instead, it uses a `service.name` attribute in the resource. See [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/da74730bf835010229a9612c281f052e26553218/specification/resource/semantic_conventions/README.md#service). 

Something like this should help you set the service name
```rust
    opentelemetry_otlp::new_pipeline()
        .tracing()
        .with_exporter(
            opentelemetry_otlp::new_exporter()
                .tonic()
                .with_endpoint("http://localhost:4317"),
        )
        .with_trace_config(
            opentelemetry::sdk::trace::config().with_resource(Resource::new(vec![KeyValue::new(
                opentelemetry_semantic_conventions::resource::SERVICE_NAME,
                "basic-otlp-service",
            )])),
        )
        .install_batch(opentelemetry::runtime::Tokio)
```

Will update the example accordingly
