### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by rex-remind101** [open-telemetry/opentelemetry-rust#715]
dead link in README of https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-datadog#kitchen-sink-full-configuration for [DatadogPipelineBuilder](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-datadog/struct.DatadogPipelineBuilder.html)

**Comment by TommyCpp** [comment]
Good catch. Thanks!
