### ISSUE TITLE
span name requires static string

### ISSUE THREAD

**Issue by rex-remind101** [open-telemetry/opentelemetry-rust#717]
Span name requires static string https://github.com/open-telemetry/opentelemetry-rust/blob/561426e4d5e04fff10f896c681c7501adbe95929/opentelemetry/src/trace/tracer.rs#L259

This prevents the user from providing names for spans dynamically, such as a different span name per request path.

**Comment by TommyCpp** [comment]
Yeah we should change it to `Cow<'static, str>` like other APIs. Thanks for catching it.

**Comment by rex-remind101** [comment]
What might be an expected eta for a new version with this change?

**Comment by djc** [comment]
In the past year, we usually released about every 6 weeks or so, although we had a 6 month gap before 0.17 so things might be slowing down. There is no set release schedule.
