### ISSUE TITLE
Configuration seems to ignore sampler configuration variables

### ISSUE THREAD

**Issue by ctron** [open-telemetry/opentelemetry-rust#730]
To me it looks like the default configuration configured itself from some environment variables, but especially the sampler configuration is ignored:

https://github.com/open-telemetry/opentelemetry-rust/blob/60af6e1eff332b432dfe284abc455834cf3841d8/opentelemetry/src/sdk/trace/config.rs#L97-L103

I would expect the sampler configuration to be apply by default as described here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration

**Comment by TommyCpp** [comment]
Hi sorry for the late response. IIRC this has been implemented yet. https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#environment-variables provides a good list of what's currently available. I will put it on my list
