### ISSUE TITLE
OpenTelemetry-jaeger: thrift agent failed with transport error

### ISSUE THREAD

**Issue by velvia** [open-telemetry/opentelemetry-rust#759]
I'm using 0.16 version
with jaeger from Docker container:
`docker run -d -p6831:6831/udp -p6832:6832/udp -p16686:16686 jaegertracing/all-in-one:latest`

```
OpenTelemetry trace error occurred. Exporter jaeger encountered the following error(s): thrift agent failed with transport error
```

This started happening when I started increasing the number of spans recorded.  It's as though it cannot handle above a certain number of spans or the size.  What can I tune or change to fix this?   Many thanks

**Comment by velvia** [comment]
I seem to only be able to send 4 spans per trace at a time to Jaeger.  This is kind of disappointing....  when I go to 5, then I get the above error and nothing is sent.

**Comment by TommyCpp** [comment]
Could you share your jaeger pipeline setup? One possible reason is the UDP packet is too long. Using [`with_max_packet_size`](https://docs.rs/opentelemetry-jaeger/0.16.0/opentelemetry_jaeger/struct.PipelineBuilder.html#method.with_max_packet_size) to increase the max packet size may medicate the problem.

**Comment by velvia** [comment]
The error does not occur if I use the `install_simple()` tracer.   The original tracer setup which gave this error:

```
            let tracer = opentelemetry_jaeger::new_pipeline()
                .with_service_name("sui")
                .install_batch(opentelemetry::runtime::Tokio)
                .expect("Could not create async Tracer");

            // Create a tracing subscriber with the configured tracer
            let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);
```

**Comment by TommyCpp** [comment]
Looks like the thrift agent throws [Transport Error](https://docs.rs/thrift/latest/thrift/struct.TransportError.html) with an [unknown error](https://docs.rs/thrift/latest/thrift/enum.TransportErrorKind.html). Digging into the code a little bit. The unkown error seems to indicate there is an [io error](https://doc.rust-lang.org/std/io/enum.ErrorKind.html).
```rust
impl From<io::Error> for Error {
    fn from(err: io::Error) -> Self {
        match err.kind() {
            io::ErrorKind::ConnectionReset
            | io::ErrorKind::ConnectionRefused
            | io::ErrorKind::NotConnected => Error::Transport(TransportError {
                kind: TransportErrorKind::NotOpen,
                message: err.to_string(),
            }),
            io::ErrorKind::AlreadyExists => Error::Transport(TransportError {
                kind: TransportErrorKind::AlreadyOpen,
                message: err.to_string(),
            }),
            io::ErrorKind::TimedOut => Error::Transport(TransportError {
                kind: TransportErrorKind::TimedOut,
                message: err.to_string(),
            }),
            io::ErrorKind::UnexpectedEof => Error::Transport(TransportError {
                kind: TransportErrorKind::EndOfFile,
                message: err.to_string(),
            }),
            _ => {
                Error::Transport(TransportError {
                    kind: TransportErrorKind::Unknown,
                    message: err.to_string(), // FIXME: use io error's debug string
                })
            }
        }
    }
}
```

We didn't surface the underlying io error. But given your problem seems to be related to the number of spans. I suspect it's the UDP packet issues where the large size packet is rejected. cc @jtescher any thoughts?

**Comment by jtescher** [comment]
Yeah this is UDP max packet size on your system. You can either reduce the number of spans per batch (simple exporter exports one at a time which is why you don't see this) or set [auto split batch](https://docs.rs/opentelemetry-jaeger/latest/opentelemetry_jaeger/struct.PipelineBuilder.html#method.with_auto_split_batch) to `true`.

**Comment by TommyCpp** [comment]
What I found interesting is thrift has a `SizeLimit` error type whose error message is `Too large a buffer or message size was requested or received`. But it doesn't seem to be used.

**Comment by velvia** [comment]
@jtescher I tried setting auto split batch to true, but it didn't seem to help.  I'll try the max packet size setting or reducing the number of spans per batch.

**Comment by TommyCpp** [comment]
@velvia you may also need to set the `max_packet_size` to be the same as UDP max packet limit of your OS. The default one is 65000 but your OS may have a smaller limit. For example, the macOS seems to have 9216

**Comment by velvia** [comment]
Ok, so it looks like the following fixes the issue for me.

```
     OpenTelemetry_jaeger::new_pipeline()
           .with_max_packet_size(9216) // Default max UDP packet size on OSX
            .with_auto_split_batch(true) // Auto split batches so they fit under packet size
            .install_batch(opentelemetry::runtime::Tokio)
```

Thanks for everyone's help.    I wonder if lowering the default max UDP packet size would help others?  Or documenting the issue?   I read that the max UDP packet size doesn't need to be that big as MTU has limit of 1500 bytes anyways.....

**Comment by TommyCpp** [comment]
The MTU doesn't necessarily limit the UDP packet. See [this SO thread](https://serverfault.com/questions/246508/how-is-the-mtu-is-65535-in-udp-but-ethernet-does-not-allow-frame-size-more-than#:~:text=UDP%20packets%20can%20have%20any,IP%2C%20either%20IPv4%20or%20IPv6). If the UDP packet is more than MTU. It will result in fragmentation, which should be avoided if you are actually communicating with a remote host as if you lost any of the fragment the receiver will throw away the whole packet. But note that jaeger agent are suppose to run along with the application on the same host. So we don't worry that fragment could be lost. 

The problem with auto split and lower packet size is it increases the number of requests needed to export the same batch of spans, which imposes a performance overhead. 

For prod environment, I'd recommend changing the OS configuration to allow larger UDP packets.
