### ISSUE TITLE
rust implementation of opentelemetry collector

### ISSUE THREAD

**Issue by hsuchifeng** [open-telemetry/opentelemetry-rust#764]
Is there any plan for  implement opentelemetry collector using rust considering performance.

**Comment by TommyCpp** [comment]
I think https://www.tremor.rs/ is an interesting read if you are looking for rust based telemetry signal processing system.

**Comment by jtescher** [comment]
Someone could also port https://github.com/open-telemetry/opentelemetry-collector if they are excited to maintain it.

**Comment by NickLarsenNZ** [comment]
I'm interested in this too, but more so I can see how to receive traces (and which existing structs are useful).
