### ISSUE TITLE
Add link to opentelemetry.io under About section

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-rust#766]
Under the **About** section of this repo (which you can access from the main repo page -- click the gear icon next to the About title):

- Under **Website**, replace the `docs.rs` link with https://opentelemetry.io
  > <img width="315" alt="Screen Shot 2022-03-20 at 17 50 44" src="https://user-images.githubusercontent.com/4140793/159187484-b9546f94-96de-4843-afcb-848b01e71d4f.png">

We're looking to do this uniformly for all OTel org repos. 

/cc @caniszczyk @nate-double-u

**Comment by chalin** [comment]
Or, if you prefer, you can link to https://opentelemetry.io/docs/instrumentation/rust/

**Comment by jtescher** [comment]
I'd prefer not to before this project hits 1.0 as it doubles the documentation maintenance effort and the rust community is more accustomed to using docs.rs.

**Comment by chalin** [comment]
Hi @jtescher - I'm not sure that I understand your "double the documentation maintenance effort". The request in this issue is just to change the link to the website in the About section of the repo. It probably makes more sense to link to https://opentelemetry.io/docs/instrumentation/rust/. That page contains a link to the doc.rs resource currently references under the About section.

There is a [docs consolidation effort underway](https://github.com/open-telemetry/opentelemetry.io/issues/833), but haven't reached the point of discussing Rust docs yet. Thanks.

**Comment by austinlparker** [comment]
Yeah, you don't need to move the docs or anything, but it'd be nice if all the repos pointed to the otel site (and then that can reference your rustdoc). Just helps make things feel a bit more aligned across the project.

**Comment by djc** [comment]
We still have the docs badge link at the top of the README, which at least for me is the more common place to look for that link. So I think replacing the link at the top right would probably be fine.

**Comment by TommyCpp** [comment]
I think we can point ppl to docs.rs from https://opentelemetry.io/docs/instrumentation/rust/. Along with the fact that we have docs badge at the top of the README. I think we are can change the link in the **About** section to https://opentelemetry.io/docs/instrumentation/rust/

**Comment by chalin** [comment]
> I think we can point ppl to docs.rs from https://opentelemetry.io/docs/instrumentation/rust/.

That's already the case, FYI.

**Comment by chalin** [comment]
Hi all. Any update on this?

**Comment by TommyCpp** [comment]
> > I think we can point ppl to docs.rs from https://opentelemetry.io/docs/instrumentation/rust/.
> 
> That's already the case, FYI.

I think we should probably list all docs.rs for all crate we have in this repo. I can make the change
