### ISSUE TITLE
Kitchen sink example uses undefined method: TonicExporterBuilder.with_endpoint

### ISSUE THREAD

**Issue by davechallis** [open-telemetry/opentelemetry-rust#767]
The [kitchen sink example](https://github.com/open-telemetry/opentelemetry-rust/blob/11af0ae0c1777aa75bb44d68fde9ccec98a9fcbf/opentelemetry-otlp/src/lib.rs#L108) for _opentelemetry-otlp_, uses a method named `.with_endpoint`:

```rust
    let tracer = opentelemetry_otlp::new_pipeline()
        .tracing()
        .with_exporter(
            opentelemetry_otlp::new_exporter()
            .tonic()
            .with_endpoint("http://localhost:4317")
            .with_timeout(Duration::from_secs(3))
            .with_metadata(map)
         )
```

however, the [TonicExporterBuilder](https://docs.rs/opentelemetry-otlp/latest/opentelemetry_otlp/struct.TonicExporterBuilder.html) has no such method.

I'm guessing that this needs updating to something similar to the example below it that uses an ExportConfig to define the endpoint?

**Comment by TommyCpp** [comment]
It was actually implemented by [`WithExportConfig`](https://docs.rs/opentelemetry-otlp/0.10.0/opentelemetry_otlp/trait.WithExportConfig.html#), which has an [implementor ](https://docs.rs/opentelemetry-otlp/0.10.0/opentelemetry_otlp/trait.WithExportConfig.html#implementors)that implements for `HasExportConfig` type.

**Comment by davechallis** [comment]
Ah, thanks, good to know, I didn't spot that.
