### ISSUE TITLE
Examples of talking to real services with opentelemetry-otlp

### ISSUE THREAD

**Issue by itamarst** [open-telemetry/opentelemetry-rust#771]
Various vendors support OTLP directly on the backend (unless I'm misunderstanding something completely). As such, I assumed I could point `opentelemetry-otlp` directly at these services, without a local collector. Perhaps I'm wrong?

Problem 1: getting it to work was a complete pain. The docs are missing lots of info so I had to cobble it together. Eventually I managed to get something that looked plausible.

Problem 2: I've tried configuring both Honeycomb and Aspecto, and they both fail with mysterious errors from the backends. This may be my fault, or it may be a bug. I have no way of telling.

It would therefore be nice to have completely working (just plug in API token) examples for some of the SaaSes using `opentelemetry-otlp`.

**Comment by itamarst** [comment]
Honeycomb dug into logs; they said the 400 error I was seeing was due to "invalid OTLP endpoint - should you be sending to /v1/traces?"

**Comment by itamarst** [comment]
I managed to get it working by changing `OTEL_EXPORTER_OTLP_ENDPOINT` to `https://api.honeycomb.io:443/v1/traces`. Can't tell if that's problem with this package or bad docs on the Honeycomb side.

**Comment by itamarst** [comment]
Here is how I got Honeycomb working (cleaned up slightly, might not compile without tweaks):

```rust
use tracing::Subscriber;
use tracing_subscriber::Registry;

fn get_tracing_subscriber(
    service_name: String,
    honeycomb_token: String,
    honeycomb_dataset: String,
) -> impl Subscriber + Sync + Send + 'static {
    std::env::set_var("OTEL_SERVICE_NAME", service_name);
    std::env::set_var(
        "OTEL_EXPORTER_OTLP_ENDPOINT",
        "https://api.honeycomb.io/v1/traces",
    );
    let exporter = opentelemetry_otlp::new_exporter()
        .http()
        .with_env()
        .with_headers(
            [
                ("x-honeycomb-team".to_string(), honeycomb_token),
                ("x-honeycomb-dataset".to_string(), honeycomb_dataset),
            ]
            .into(),
        );
    let tracer = opentelemetry_otlp::new_pipeline()
        .tracing()
        .with_exporter(exporter)
        .install_batch(opentelemetry::runtime::Tokio)
        .expect("Failed to create opentelemetry tracer");
    Registry::default().with(telemetry)


```

**Comment by TommyCpp** [comment]
I think we need to specify a path for HTTP. Grpc example to connect to honeycomb can be found at https://github.com/open-telemetry/opentelemetry-rust/tree/main/examples/external-otlp-tonic-tokio. 

I will close this issue for now as the problem has been solved. I am not sure we want to add anther example just for HTTP use case. It seems the OTLP based on Grpc is used more often. Please let me know if you have further questions.

**Comment by cartermp** [comment]
@TommyCpp any thoughts towards appending `/v1/traces` for this case in the SDK side here? As per [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#endpoint-urls-for-otlphttp), with the env var used (`OTEL_EXPORTER_OTLP_ENDPOINT`) the user shouldn't have to specify `/v1/traces` at the end of their URL, unless I'm misinterpreting the spec.

**Comment by TommyCpp** [comment]
I think that is worth exploring. Let me open an issue for it
