### ISSUE TITLE
Cannot create PushController for metrics with an http exporter instead of a grpc one

### ISSUE THREAD

**Issue by bnjjj** [open-telemetry/opentelemetry-rust#772]
With `opentelemtry-oltp` for now we can't create a `PushController` with an http exporter.
Here is the version I have for GRPC:

```rust
let push_ctrl = opentelemetry_otlp::new_pipeline()
                    .metrics(tokio::spawn, delayed_interval)
                    .with_exporter(
                        opentelemetry_otlp::new_exporter()
                            .tonic()
                            .with_export_config(export_config),
                    )
                    .with_aggregator_selector(selectors::simple::Selector::Exact)
                    .build()?;
```

Here is the version I would like for the http but it doesn't work for now. (Mainly because `MetricsExporter::new` takes a `TonicConfig` and then we can't create a `MetricsExporter` with something else than a Grpc mode.

```rust
let push_ctrl = opentelemetry_otlp::new_pipeline()
                    .metrics(tokio::spawn, delayed_interval)
                    .with_exporter(
                        opentelemetry_otlp::new_exporter()
                            .http()
                            .with_export_config(export_config),
                    )
                    .with_aggregator_selector(selectors::simple::Selector::Exact)
                    .build()?;
```

**Comment by TommyCpp** [comment]
Currently, we only have `tonic` based implementation for metrics exporters. `http-proto` support will be added later

**Comment by MatthiasJReisinger** [comment]
Hi, thx for working on this issue! After #1020 has been merged, does this mean that this issue here could be closed? Or are there still things to do in order to achieve full support for HTTP metric export? :)

**Comment by cijothomas** [comment]
> Hi, thx for working on this issue! After #1020 has been merged, does this mean that this issue here could be closed? Or are there still things to do in order to achieve full support for HTTP metric export? :)

I think this can be closed now.
