### ISSUE TITLE
Add signal path automatically for OTLP HTTP exporter

### ISSUE THREAD

**Issue by TommyCpp** [open-telemetry/opentelemetry-rust#773]
As per [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#example-1), OTLP http exporter should be able to automatically add a path based on signal.

**Comment by GaryPWhite** [comment]
i'd be happy to take this one!

**Comment by TommyCpp** [comment]
Thanks for the help! Just assigned it to you
