### ISSUE TITLE
Sampler::Probability will never sample orphaned spans

### ISSUE THREAD

**Issue by natemara** [open-telemetry/opentelemetry-rust#78]
According to the documentation of the `Probability` variant of `opentelemetry::sdk::trace::sampler::Sampler`, 

> Fractions >= 1 will always sample. If the parent span is sampled, then it's child spans will automatically be sampled. 

This implies that a span may be sampled if its parent is not sampled, if a probability condition is met. Here is a link to the referenced documentation in the code:

https://github.com/open-telemetry/opentelemetry-rust/blob/ade9c2c3dba2ba2852a2f89dc973e3e23fc9d97e/src/sdk/trace/sampler.rs#L14-L18

In practice however, using the probability variant of Sampler will not sample any spans. Due to the implementation of `should_sample` which conflicts with the above documentation:

https://github.com/open-telemetry/opentelemetry-rust/blob/ade9c2c3dba2ba2852a2f89dc973e3e23fc9d97e/src/sdk/trace/sampler.rs#L47-L48

The implementation here first checks to see if the parent span was sampled, and only if it was, performs the probability check to see if the current span will be sampled. This does not match with the documentation shown above. If this behavior is intentional, the documentation should call out that the probability will only be tested, and spans will only be sampled if their parent span was sampled. I would expect the implementation to look more like this if the documentation is correct:

```rust
 if  *prob > 0.0 { 
     if *prob > 1.0 || parent_context.map(|ctx| ctx.is_sampled()).unwrap_or(false) || *prob > rand::random() { 
        // Mark span as sampled
```

**Comment by jtescher** [comment]
@natemara hm you are bringing up a good point. Currently [the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/6347a9b44714840ef67f0a477f60896e07362191/specification/sdk-tracing.md#built-in-samplers) states:

* The default behavior should be to trust the parent SampledFlag. However there should be configuration to change this.
* The default behavior is to apply the sampling probability only for Spans that are root spans (no parent) and Spans with remote parent. However there should be configuration to change this to "root spans only", or "all spans".
* Description MUST be ProbabilitySampler{0.000100}.

It seems like the conservative change would be to update the docs in this project and change `.unwrap_or(false)` to `.unwrap_or(true)` which would make the priority be parent, then >0 and <1, then checking against rand.

Alternatively we could add another config option to `Sampler::Probability` that could signal root spans vs all spans and update the implementation to take the extended spec into account.

Are you interested in creating a PR with either of these solutions? happy to help you get started.

**Comment by natemara** [comment]
After I filed this issue initially, I had the thought of changing the `unwrap(false)` to true, but can I ask why you crossed that out?

I also thought of changing it to this:

```rust
                let mut should_get_probability_checked = true;
                if let Some(ctx) = parent_context {
                    if ctx.is_sampled() {
                        return api::SamplingResult {
                            decision: api::SamplingDecision::RecordAndSampled,
                            attributes: Vec::new(),
                        };
                    } else if !ctx.is_remote() {
                        should_get_probability_checked = false;
                    }
                }

                if should_get_probability_checked && *prob > 0.0 {
                    if *prob > 1.0 || *prob > rand::random() {
                        api::SamplingDecision::RecordAndSampled
                    } else {
                        api::SamplingDecision::NotRecord
                    }
                } else {
                    api::SamplingDecision::NotRecord
                }
```

This would ensure that only root and remote spans had the probability applied to them, and all local spans with a parent would inherit their parent's sampling decision. Does that seem reasonable?

**Comment by jtescher** [comment]
I think `...and Spans with remote parent` could be read two ways, meaning that all remote-parent spans are "roots" in a sense so they should have the probability applied, or that they should have probability applied but still respect the non-sampled flag of the parent and not record.

The go impl treats >1.0 as `ALWAYS`:

https://github.com/open-telemetry/opentelemetry-go/blob/638b865c907fc0f5fe8b06fc037bc5467d6343cc/sdk/trace/sampling.go#L85-L87

And then checks parent before sampling (meaning that <0 will not act like `NEVER`):

https://github.com/open-telemetry/opentelemetry-go/blob/638b865c907fc0f5fe8b06fc037bc5467d6343cc/sdk/trace/sampling.go#L65-L73

That seems reasonable to me, they also use the first 8 bytes of the trace id as a source of randomness instead of generating a new number which could be a nice optimization.

**Comment by jtescher** [comment]
@natemara that seem right to you? or do you see other issues?

**Comment by MikeGoldsmith** [comment]
My understanding is a _remote_ parent span created in an up-stream process and is only created when extracting a span context in propagation.
A _non-remote_ parent span is one that is created within the same process.

I also agreed the probability range is 0.0 to 1.0, a probability of 1.0+ is ALWAYS and 0.0 or less is NEVER.
