### ISSUE TITLE
invalid URL generated from the Datadog agent endpoint

### ISSUE THREAD

**Issue by Geal** [open-telemetry/opentelemetry-rust#782]
Context: https://github.com/apollographql/router/issues/851

If the URL passed to [with_agent_endpoint](https://docs.rs/opentelemetry-datadog/latest/opentelemetry_datadog/struct.DatadogPipelineBuilder.html#method.with_agent_endpoint) is of the format `http://localhost:8126/` (with a trailing slash), the exporter will generate an URL of the format `http://datadog.default:8126//v0.5/traces` and fail to send traces there.

The issue is that the endpoint and version path are concatenated instead of appending a proper path to an existing URL: http://datadog.default:8126//v0.5/traces

**Comment by TommyCpp** [comment]
We should probably add some URL parsing instead of just combing raw string. I will push a fix. Thanks for letting us know
