### ISSUE TITLE
Can't fork

### ISSUE THREAD

**Issue by rex-remind101** [open-telemetry/opentelemetry-rust#784]
<img width="793" alt="Screen Shot 2022-04-15 at 1 58 44 PM" src="https://user-images.githubusercontent.com/4573957/163631357-a9c54336-c4cd-4bea-901e-26877c75f064.png">

How do I contribute and open a PR?

**Comment by TommyCpp** [comment]
Looks like you already have a fork https://github.com/rex-remind101/opentelemetry-rust?
