### ISSUE TITLE
Memory Consumption Issue with opentelemetry::KeyValue

### ISSUE THREAD

**Issue by Bhogayata-Keval** [open-telemetry/opentelemetry-rust#793]
I am using this SDK to send my infrastructure metrics to Kafka using OTLP Exporter.
I am sending metrics every 5 seconds (using an infinite loop).
I used valgrind massif and memcheck tools to identify memory leaks in my code.
Turns out that, if I am sending attributes along with my values, then it is consuming a lot of memory.

```
demo_recorder.record(value, &[
    KeyValue::new("key1", "data1"),
    KeyValue::new("key2", "data2"),
    KeyValue::new("key3", "data3"),
    KeyValue::new("key4", "data4"),
]);
```
If I avoid adding these KeyValue (use opentelemetry::KeyValue), then there is a massive change in memory leaks.
Is there a way I can handle this on my side (can I somehow free memory occupied by KeyValue ?)
OR is it an SDK level bug ?

**Comment by TommyCpp** [comment]
Thanks for bringing it up. I am not so sure is it a problem of attributes taking too much memory or is it a memory leak. Could you provide some more details? Do you observe the memory keeps going up even if you stop record metrics?

**Comment by Bhogayata-Keval** [comment]
The memory growth slows down by around 10 times, when I continue recording, and just comment out the attributes !!
Here is a small example, I used for testing.

`mod otelemetry;
use sysinfo::{ProcessExt, System, SystemExt};
use settimeout::set_timeout;
use std::time::Duration;
use opentelemetry::global;

use futures_util::{Stream, StreamExt as _};
use opentelemetry::{
    metrics
};

use opentelemetry_otlp::{ExportConfig, WithExportConfig, Protocol};
use opentelemetry::{sdk::metrics::{selectors, PushController}};

fn delayed_interval(duration: Duration) -> impl Stream<Item = tokio::time::Instant> {
    opentelemetry::util::tokio_interval_stream(duration).skip(1)
}

pub fn init_meter() -> metrics::Result<PushController> {
    let export_config = ExportConfig {
        endpoint: "http://localhost:55680".to_string(),
        protocol: Protocol::Grpc,
        ..ExportConfig::default()
    };
    opentelemetry_otlp::new_pipeline()
        .metrics(tokio::spawn, delayed_interval)
        .with_exporter(
            opentelemetry_otlp::new_exporter()
                .tonic()
                .with_export_config(export_config),
        )
        .with_aggregator_selector(selectors::simple::Selector::Exact)
        .build()
}

#[tokio::main]
async fn main() {

    loop {
        let mut sys = System::new_all();
        sys.refresh_all();

        // Metrics Initialized 
        let _start = init_meter(); 
        let meter = global::meter("demo-watcher");

        // Values recorded
        let cpu_recorder = meter.f64_value_recorder("host.process.cpu.utilization").init();
        let memory_recorder = meter.f64_value_recorder("host.process.memory.utilization").init();

        // Display processes ID, name na disk usage:
        for (_pid, process) in sys.processes() {
            if process.cmd().join(" ") != "" {
                // println!("{:?}\t\t{:?}", process.cmd().join(" "), pid);
                let cpu = (process.cpu_usage()) as f64;
                let memory = (process.memory()*(1000 as u64)) as f64;

                cpu_recorder.record(cpu, &[
                    /* KeyValue::new("command", process.cmd().join(" ")),
                    KeyValue::new("pid", pid.to_string()),
                    KeyValue::new("pid", pid.to_string()),
                    KeyValue::new("node_identifier", sys.host_name().unwrap()), */
                ]);
                memory_recorder.record(memory, &[]);
            }
        }
        set_timeout(Duration::from_secs(5)).await;
    }
}
`

We can just uncomment the attributes passed - and can easily observe the memory growth.

**Comment by Bhogayata-Keval** [comment]
I also tested this with UpDownCounter, same result  (faster memory consumption with attributes, slower memory consumption without attributes)

Therefore, I doubt the issue is with the core : direct_record method in SyncInstrument
https://github.com/open-telemetry/opentelemetry-rust/blob/dacd75af209550283d98be9f6f93e91588493032/opentelemetry-api/src/metrics/sync_instrument.rs

Trying to contribute on this issue as well

**Comment by Bhogayata-Keval** [comment]
Valgrind memcheck also suggest the same trace of memory usage :

`91.90% (617,214B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->43.97% (295,280B) 0x10ECCFB: alloc::alloc::alloc (alloc.rs:87)
| ->43.97% (295,280B) 0x10ECE96: alloc::alloc::Global::alloc_impl (alloc.rs:169)
|   ->43.97% (295,280B) 0x10ECFB9: <alloc::alloc::Global as core::alloc::Allocator>::allocate (alloc.rs:229)
|     ->33.45% (224,624B) 0x10998F9: alloc::boxed::Box<T,A>::try_new_uninit_in (boxed.rs:461)
|     | ->33.45% (224,624B) 0x1099833: alloc::boxed::Box<T,A>::new_uninit_in (boxed.rs:425)
|     |   ->33.45% (224,624B) 0x10996F6: alloc::boxed::Box<T>::new_uninit (boxed.rs:221)
|     |     ->33.45% (224,624B) 0x10727E3: alloc::collections::btree::node::LeafNode<K,V>::new (node.rs:83)
|     |       ->33.45% (224,624B) 0x1072919: alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Owned,K,V,alloc::collections::btree::node::marker::Leaf
>::new_leaf (node.rs:217)
|     |         ->33.45% (224,624B) 0x1074D39: alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Owned,K,V,alloc::collections::btree::node::marker::Le
afOrInternal>::new (node.rs:559)
|     |           ->33.21% (223,008B) 0x10947EE: alloc::collections::btree::map::BTreeMap<K,V>::bulk_build_from_sorted_iter (map.rs:1315)
|     |           | ->33.21% (223,008B) 0x1095552: <alloc::collections::btree::map::BTreeMap<K,V> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter (map.rs:1952)
|     |           |   ->33.21% (223,008B) 0x1080CCA: core::iter::traits::iterator::Iterator::collect (iterator.rs:1778)
|     |           |     ->33.21% (223,008B) 0x10CA35E: opentelemetry::attributes::AttributeSet::from_attributes (mod.rs:21)
|     |           |       ->33.21% (223,008B) 0x10C595B: opentelemetry::sdk::metrics::SyncInstrument::acquire_handle (mod.rs:335)
|     |           |         ->33.21% (223,008B) 0x10C5E6B: <opentelemetry::sdk::metrics::SyncInstrument as opentelemetry::metrics::sdk_api::SyncInstrumentCore>::record_one (mod.rs:36
9)
|     |           |           ->33.21% (223,008B) 0x4618D0: opentelemetry::metrics::sync_instrument::SyncInstrument<T>::direct_record (sync_instrument.rs:66)
|     |           |             ->33.21% (223,008B) 0x2EEABB: opentelemetry::metrics::value_recorder::ValueRecorder<T>::record (value_recorder.rs:25)
|     |           |               ->33.21% (223,008B) 0x313FEA: pod_list::hosts::Base::stats (mod.rs:99)`

**Comment by Bhogayata-Keval** [comment]
`91.90% (617,214B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->43.97% (295,280B) 0x10ECCFB: alloc::alloc::alloc (alloc.rs:87)
| ->43.97% (295,280B) 0x10ECE96: alloc::alloc::Global::alloc_impl (alloc.rs:169)
|   ->43.97% (295,280B) 0x10ECFB9: <alloc::alloc::Global as core::alloc::Allocator>::allocate (alloc.rs:229)
|     ->33.45% (224,624B) 0x10998F9: alloc::boxed::Box<T,A>::try_new_uninit_in (boxed.rs:461)
|     | ->33.45% (224,624B) 0x1099833: alloc::boxed::Box<T,A>::new_uninit_in (boxed.rs:425)
|     |   ->33.45% (224,624B) 0x10996F6: alloc::boxed::Box<T>::new_uninit (boxed.rs:221)
|     |     ->33.45% (224,624B) 0x10727E3: alloc::collections::btree::node::LeafNode<K,V>::new (node.rs:83)
|     |       ->33.45% (224,624B) 0x1072919: alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Owned,K,V,alloc::collections::btree::node::marker::Leaf
>::new_leaf (node.rs:217)
|     |         ->33.45% (224,624B) 0x1074D39: alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Owned,K,V,alloc::collections::btree::node::marker::Le
afOrInternal>::new (node.rs:559)
|     |           ->33.21% (223,008B) 0x10947EE: alloc::collections::btree::map::BTreeMap<K,V>::bulk_build_from_sorted_iter (map.rs:1315)
|     |           | ->33.21% (223,008B) 0x1095552: <alloc::collections::btree::map::BTreeMap<K,V> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter (map.rs:1952)
|     |           |   ->33.21% (223,008B) 0x1080CCA: core::iter::traits::iterator::Iterator::collect (iterator.rs:1778)
|     |           |     ->33.21% (223,008B) 0x10CA35E: opentelemetry::attributes::AttributeSet::from_attributes (mod.rs:21)
|     |           |       ->33.21% (223,008B) 0x10C595B: opentelemetry::sdk::metrics::SyncInstrument::acquire_handle (mod.rs:335)
|     |           |         ->33.21% (223,008B) 0x10C5E6B: <opentelemetry::sdk::metrics::SyncInstrument as opentelemetry::metrics::sdk_api::SyncInstrumentCore>::record_one (mod.rs:36
9)
|     |           |           ->33.21% (223,008B) 0x4618D0: opentelemetry::metrics::sync_instrument::SyncInstrument<T>::direct_record (sync_instrument.rs:66)
|     |           |             ->33.21% (223,008B) 0x2EEABB: opentelemetry::metrics::value_recorder::ValueRecorder<T>::record (value_recorder.rs:25)
|     |           |               ->33.21% (223,008B) 0x313FEA: pod_list::hosts::Base::stats (mod.rs:99)`

**Comment by bhogayatakb** [comment]
Valgrind memcheck tool is also showing the same memory consumption trace !
[screenshot](https://drive.google.com/file/d/1gem4wHO_FGU7G77MoBKuumqXTVblhBFc/view?usp=sharing)

**Comment by Bhogayata-Keval** [comment]
Valgrind memcheck tool is also showing the same memory consumption trace !
[screenshot](https://drive.google.com/file/d/1gem4wHO_FGU7G77MoBKuumqXTVblhBFc/view?usp=sharing)

**Comment by TommyCpp** [comment]
I think the issue is concluded as the Stateful collection requires more memory to calculate the aggregation. Please feel free to reopen this if further investigation is needed
