### ISSUE TITLE
Allow `opentelemetry-jaeger` to export span data in jaegers json format

### ISSUE THREAD

**Issue by weiznich** [open-telemetry/opentelemetry-rust#804]
This is more a feature request than a bug report.

I'm looking for a possibility to export open telemetry compatible span data without setting up whole collector stack as that requires network access and/or additional software. That might not be able in some environments due to external restrictions. Nevertheless it would sometimes be really helpful to receive tracing data from those environments to debug potential issues. 

Jaeger allows to import trace data as json file, so one idea to implement this would be to just have an exporter that write trace data in a compatible json format to some files. Although it seems like the jaeger json format is mostly designed to be used as way to export and later import data from jaeger itself it seems like a good solution for the problem outlined above. See https://github.com/jaegertracing/jaeger-ui/issues/381 for more details about the format.

I've already written a compatible exporter for our project and can verify that it works as expected. I've opening this mostly to checkout if there is any interest in having such functionality as part of the `opentelemetry-jaeger` crate. If there is any interest in this I likely can provide a PR if someone provides some pointers about where to put stuff and how to integrate the exporter into the existing `opentelemetry-jaeger` code base.

**Comment by TommyCpp** [comment]
Thanks for the contribution! I think it's nice to have more custom exporters. I think it may be best to put it in `opentelemetry-contrib` crate as the jaeger JSON format is not a standard exporter mentioned in spec and we already have a lot of different exporters in the jaeger crate.

In `opentelemetry-contrib` we have `trace` mod, which only has a `propagator` mod inside, I think we can create a new mod called `exporter` and put the json format exporter in it.

Let me know your thoughts.

**Comment by weiznich** [comment]
That sounds fine for me. I will try to open a PR next week.

**Comment by weiznich** [comment]
Fixed by #814
