### ISSUE TITLE
Support a rust service in the community demo app

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-rust#805]
The OTel community is working on a shared demo application that represents all supported languages. We need to replace an existing service in the donated Google microservices demo with a Rust example.

Reference issue: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/35

**Comment by TommyCpp** [comment]
Close with https://github.com/open-telemetry/opentelemetry-demo-webstore/pull/179
