### ISSUE TITLE
Proposal: Alter RNG for TraceId and SpanId

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-rust#808]
![image](https://user-images.githubusercontent.com/643846/172310090-ecd0f3c8-e2fd-4397-a1ee-57f516337f2e.png)
Base on doing some cursory benchmarking I was seeing that in `main` roughtly 28% of the time spent on `Span::start()` is 20% in trace_id generation and 8% in span_id generation, 

I originally dug into this because of #800 out of interest in how much time sampling versus non sampling took.

I can run some additional benchmarks to ensure consistency. However, I am currently thinking something like https://crates.io/crates/oorandom would be a faster default. It's `#[no_std]` and also `#[forbid(unsafe_code)]` 
Finally it's a [PCG](https://www.pcg-random.org/) so statistically it should be ok.

**Comment by djc** [comment]
Different RNG does not necessarily require a different crate -- the rand crate comes with several types of RNG. The first question is if we need a cryptographically secure RNG for this, which we do seem to be using here. If we think we don't need a secure RNG, we could try the `SmallRng`, as explained in https://docs.rs/rand/latest/rand/rngs/index.html#our-generators.

**Comment by hdost** [comment]
> Different RNG does not necessarily require a different crate -- the rand crate comes with several types of RNG. The first question is if we need a cryptographically secure RNG for this, which we do seem to be using here. If we think we don't need a secure RNG, we could try the `SmallRng`, as explained in https://docs.rs/rand/latest/rand/rngs/index.html#our-generators.

Agreed as first change SmallRng might be alright. I'll do some initial testing.

**Comment by hdost** [comment]
From my initial benchmarks looks like minor but not insignificant improvement. ~9% improvement ran a few times to attempt normalizing it.

**Comment by shaun-cox** [comment]
@hdost, curious if you're still planning to move forward with this change?

**Comment by hdost** [comment]
Yes I can rebase put out a patch.

**Comment by hdost** [comment]
Finally got back to this, and when running the stress test for the SmallRng we're seeing about a 6% improvement at the best, to negligible at worst.
