### ISSUE TITLE
Support exporting to collector using grpc in opentelemetry-jaeger

### ISSUE THREAD

**Issue by TommyCpp** [open-telemetry/opentelemetry-rust#813]
Out of all [available formats](https://www.jaegertracing.io/docs/1./apis/#protobuf-via-grpc-stable) in Jaeger the _protobuf over grpc_ support is missing. 

This format is generally used by agents to send spans to collectors and should probably be avoided in SDK. However, some SDK like java supports it so it maybe makes sense for us to support it too.

We may also support `OTEL_EXPORTER_JAEGER_PROTOCOL` env var if we added grpc support

**Comment by cijothomas** [comment]
Closing this issue as this is irrelevant due to opentelemetry-jaeger exporter being [deprecated](https://github.com/open-telemetry/opentelemetry-rust/issues/995#issuecomment-1744112355).
