### ISSUE TITLE
Add support for instrumentation scope attributes

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-rust#815]
See the spec change for details https://github.com/open-telemetry/opentelemetry-specification/pull/2579

**Comment by wperron** [comment]
Wouldn't mind taking a shot at this, is there an SDK that already implements this? Just took a quick look at the Go one and it doesn't look like it's been implemented there.

**Comment by lzchen** [comment]
Related: https://github.com/open-telemetry/opentelemetry-rust/issues/883
