### ISSUE TITLE
Release new opentelemetry-datadog version

### ISSUE THREAD

**Issue by alexpusch** [open-telemetry/opentelemetry-rust#817]
Current opentelemetry-datadog crate is 0.5.0 which was released 5 months ago - https://crates.io/crates/opentelemetry-datadog
Lately some interesting features were added to this crate, that we'll be happy to use. Can you release an official release of this crate?

**Comment by djc** [comment]
I think we'll release another release with everything packaged up together, see #779.

**Comment by lroux-at-jellysmack** [comment]
This issue can be closed as `opentelemetry-datadog` v0.6 has been released. (cf. https://crates.io/crates/opentelemetry-datadog/versions)
