### ISSUE TITLE
WithContext is not exposed through exports

### ISSUE THREAD

**Issue by exFalso** [open-telemetry/opentelemetry-rust#823]
Hi, I'm trying to use `WithContext` and I need to specify its type in a trait implementation. This is in a tonic GRPC service with a streaming API, where I need to specify the stream's type with an associated type.
However, I cannot find any way to actually import `WithContext`, I can only construct instances of with with the `with_context()` functions. Is this intended?

**Comment by mkatychev** [comment]
This would also help in isntrumenting by attaching a span and context:

```rust
pub trait InstrumentWithContext: Instrument {
    fn instrument_cx(self, span: Span) -> Instrumented<WithContext<Self>>;
}
```
