### ISSUE TITLE
SpanExporter::ForceFlush

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-rust#836]
As mentioned in https://github.com/open-telemetry/opentelemetry-specification/pull/2654
there are three required methods for SpanExporter. 
Thus seems like a blocker for 1.0 on Tracing

**Comment by ymtdzzz** [comment]
Hi, I'm new to this project, but I'd like to start  contribution from smaller part.
Is it okay to just add `ForceFlush` method (and default implementation) to the trait?

**Comment by hdost** [comment]
@ymtdzzz  go for it

**Comment by hdost** [comment]
I feel like we should re-open or create other tickets such that at least the specifies exporters implement it.
