### ISSUE TITLE
More information in OpenTelemetry export errors

### ISSUE THREAD

**Issue by skairunner** [open-telemetry/opentelemetry-rust#837]
We are currently using open telemetry with the OTLP exporter. We get these sort of errors while batch-exporting: 

```
OpenTelemetry trace error occurred. Exporter otlp encountered the following error(s): the grpc server returns error (Some resource has been exhausted): , detailed error message: grpc: received message larger than max (9074759 vs. 4194304)

```

Clearly we are sending too large spans. However, it's not easy to track down where the problematic spans are. It would be good if the error message included some information that could help diagnose the issues.

Logging all the span names is probably not a good idea, since there could be a lot of them. Some kind of sampling might help. Alternatively, for this specific error the approximate byte size of the spans could be tallied and logged if they are a significant fraction of the payload. This might be getting into too-specific solutions.

**Comment by lzchen** [comment]
@TommyCpp 
Is the tags for this supposed to be under `metrics`?

**Comment by TommyCpp** [comment]
Good catch! Fixed the label

**Comment by Ezward** [comment]
I am getting the same error in one project.  It seems the traces are blocking and eventually timeout and produce this error.  Is there some setting to control how often batches are flushed?

**Comment by matthiasg** [comment]
Just experience that same issue. It is not even clear from the log message whether this happens due to batching or individual tracing statements.

At minimum improved logging here would help

**Comment by cijothomas** [comment]
There have been many improvements to internal logging in the past few releases. If there is anything else missing, we can add them to improve troubleshooting experience.

Closing this, as there is nothing specific to act on. Happy to receive more feedback on improving internal logging.
