### ISSUE TITLE
[Rust] Add Project Status table for each Signal in README top section

### ISSUE THREAD

**Issue by trivikr** [open-telemetry/opentelemetry-rust#838]
**Is your feature request related to a problem? Please describe.**

The Project Status of Traces/Metrics/Logs Signals in OpenTelemetry is difficult to find in OpenTelemetry for Rust.

**Describe the solution you'd like**
Add Project Status Table at the top of README, similar to how it's done in other implementations:

- .NET https://github.com/open-telemetry/opentelemetry-dotnet
- Go https://github.com/open-telemetry/opentelemetry-go
- CPP https://github.com/open-telemetry/opentelemetry-cpp

The Status Table would list Signal and the current status

```
| Signal  | Status                            | Project                           |
| ------- | --------------------------------- | --------------------------------- |
| Traces  | Experimental/Alpha/Beta/RC/Stable | [version](link-to-github-project) |
| Metrics | Experimental/Alpha/Beta/RC/Stable | [version](link-to-github-project) |
| Logs    | Experimental/Alpha/Beta/RC/Stable | [version](link-to-github-project) |
```

**Describe alternatives you've considered**
Going through repo contents to find the status of each Signal.

**Additional context**
Summary table for OpenTelemetry Status https://github.com/open-telemetry/opentelemetry.io/issues/1548

**Comment by trivikr** [comment]
On a quick look at version numbers and GitHub projects, this is what I think the table is:

| Signal  | Status       | Project |
| ------- | ------------ | ------- |
| Traces  | Experimental | N/A     |
| Metrics | Experimental | N/A     |
| Logs    | Experimental | N/A     |

If it's incorrect, please provide the correct table in this GitHub issue, so that it can be updated on README.

**Comment by trivikr** [comment]
The consensus is being achieved towards treating website as authoritative, and provide a link to website instead. 

https://github.com/open-telemetry/opentelemetry-java/pull/4612#issuecomment-1185118267

We'll request the status page to link to language instrumentation links instead of GitHub READMEs in https://github.com/open-telemetry/opentelemetry.io/issues/1548

**Comment by TommyCpp** [comment]
> The consensus is being achieved towards treating website as authoritative, and provide a link to website instead.

Emm I feel like we already have that in `About` section, which actually is easier to find 

If we do need to add one to README we can probably update the `Website` link in README to point to rust instrument?
