### ISSUE TITLE
Proposal: Implementation of CollectorHttpClient with pure hyper

### ISSUE THREAD

**Issue by tomkarw** [open-telemetry/opentelemetry-rust#843]
I recently tried to remove `reqwest` as a dependency from a project (using the lower-level `hyper::Client` which was already required instead). After doing so, I noticed that `reqwest` is still included in the dependency tree due to its use in `opentelemetry-http` and `opentelemetry-jaeger`. Using `reqwest` (which relies on `hyper` either way) seems a suitable choice for application code, but `hyper` itself might mean fewer dependencies for a project like mine.

Would you be interested if I implemented `CollectorHttpClient` variant that relied only on `hyper` as an alternative? If yes, I'd try to code it straight away.

**Comment by tomkarw** [comment]
Hey @TommyCpp, is that a green light?

**Comment by TommyCpp** [comment]
Yeah, I think that's reasonable as long as we can put it behind a feature like other clients.

**Comment by tomkarw** [comment]
Hey @TommyCpp, I think I have an MVP :arrow_up:.

I'd like to do three more things:
* add `hyper_rustls_collector_client` the same way, there is a `reqwest_rustls_collector_client`
* add `hyper` option to the rest of the SDKs: `opentelemetry-{datadog,dynatrace,otlp,zipkin}`
* refactor this [#[cfg(feature = "...")] mess](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-jaeger/src/exporter/config/collector/http_client.rs#L1-L31) to something like [this](https://github.com/tomkarw/opentelemetry-rust/blob/tomkarw/feat-implementation-of-collector-http-client-with-pure-hyper/opentelemetry-jaeger/src/exporter/config/collector/http_client.rs#L150-L151). Basically move the `use ...` to the match arm scope that is already behind feature flag.

Let me know which of these you'd like to see (or should we stick to only current changes and create new PR for the rest), and I'll continue the work.

**Comment by TommyCpp** [comment]
Thanks for working on it. I think it's reasonable to start with adding a hyper based client with rusttls support and refatoring #[cfg(feature)]. 

As for the adding `hyper` option to other exporters. I think it's a good idea but one caveat is that we haven't finished refactoring the overlapping features(means if you enable two http client features one of them will override the other) in those creates so it may be tricky
