### ISSUE TITLE
Upgrade dashmap

### ISSUE THREAD

**Issue by lorensr** [open-telemetry/opentelemetry-rust#846]
Currently this depends on dashmap `^4.0.1`, which has this security advisory: https://rustsec.org/advisories/RUSTSEC-2022-0002.html

It's fixed in `>=5.1.0`

**Comment by TommyCpp** [comment]
I believe we have fixed it in https://github.com/open-telemetry/opentelemetry-rust/pull/818. Once the new version is released it should be fixed. Meanwhile, maybe we can try to backport this to 0.17? cc @jtescher

**Comment by jtescher** [comment]
@TommyCpp sure, happy to do a patch release there if you want to set it up

**Comment by jtescher** [comment]
Resolved in https://github.com/open-telemetry/opentelemetry-rust/pull/818
