### ISSUE TITLE
Publish crate for `opentelemetry-proto`

### ISSUE THREAD

**Issue by spencergilbert** [open-telemetry/opentelemetry-rust#860]
Hey,

I was wondering if it was possible to get a crate published for the `opentelemetry-proto`. We ([Vector](https://vector.dev)) are starting to add support for OpenTelemetry - both receiving and sending and realized we were just re-implementing the code from that crate.

**Comment by jtescher** [comment]
Absolutely, just resolving the last blocking issues and then we'll publish this crate in #779

**Comment by spencergilbert** [comment]
Awesome! I'll keep an eye on that and update our usage once that lands, looking forward to working together in the future 😄

**Comment by jtescher** [comment]
Currently just https://github.com/open-telemetry/opentelemetry-rust/pull/839

**Comment by jtescher** [comment]
Released https://crates.io/crates/opentelemetry-proto
