### ISSUE TITLE
Exporters should not be sent "is_sampled=false" spans

### ISSUE THREAD

**Issue by fasterthanlime** [open-telemetry/opentelemetry-rust#870]
I have a custom `ShouldSample` implemetation. I ran into https://github.com/open-telemetry/opentelemetry-rust/issues/800 and am glad to see https://github.com/open-telemetry/opentelemetry-rust/pull/839 is almost there.

But there's a remaining problem afaict. As per the [opentelemetry spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampling):

> `Sampled` flag in `TraceFlags` on `SpanContext`. This flag is propagated via the `SpanContext` to child Spans. For more details see the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#sampled-flag). This flag indicates that the `Span` has been `sampled` and will be exported.
>
> **[Span Exporters](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#span-exporter) MUST receive those spans which have `Sampled` flag set to true and they SHOULD NOT receive the ones that do not.**

The problem is that, in the `opentelemetry` crate, span exporters are simply span processors. `Span::ensure_ended_and_exported` sends export data to all processors unconditionally:

https://github.com/open-telemetry/opentelemetry-rust/blob/043e4b7523f66e79338ada84e7ab2da53251d448/opentelemetry-sdk/src/trace/span.rs#L186-L208

(..unless the span was already exported, or the provider was shut down). It doesn't check for `self.span_context().is_sampled()`, and can't tell the difference between exporters and other span processors anyway.

Here's what happens whe installing a simple exporter:

https://github.com/open-telemetry/opentelemetry-rust/blob/c92a1ad5af6a3c4098ecfc1e54134c17f3a1e708/opentelemetry-sdk/src/trace/provider.rs#L154-L160

The `SimpleSpanProcessor` unconditionally sends to its internal channel:

https://github.com/open-telemetry/opentelemetry-rust/blob/c92a1ad5af6a3c4098ecfc1e54134c17f3a1e708/opentelemetry-sdk/src/trace/span_processor.rs#L143-L147

Which unconditionally calls `exporter.export`:

https://github.com/open-telemetry/opentelemetry-rust/blob/c92a1ad5af6a3c4098ecfc1e54134c17f3a1e708/opentelemetry-sdk/src/trace/span_processor.rs#L116-L118

So, this seems like another departure from the spec (which was very surprising to me).

---

A bad fix for this is to teach both the "simple" and "batched" exporters to ignore spans where `is_sampled=false`. This is bad for a bunch of reasons:

  * Other exporter crates implement their own processors, which might not know they have to filter
  * It's really not the responsibility of exporters to do filtering
  * `build_export_data` is not free, calling it for a non-sampled span is wasteful

Another fix is to not send the span to _any_ processor if it's not sampled - ie, to return early from `ensure_ended_and_exported` if `is_sampled=false`. This also seems bad because what if there's processors that _aren't_ exporters?

Again, the spec says:

  * span processors must receive spans with `is_recording=true`, regardless of `is_sampled`
  * span exporters must only receive spans with `is_recording=true && is_sampled=true`

It seems like the actual fix is to either:

  * keep separate lists for "processors" and "exporters"
  * add an "fn is_exporter(&self) -> bool" method to `SpanProcessor` - this seems expensive for no good reason

Either way this seems like a breaking change.

**Comment by TommyCpp** [comment]
Yeah, I think this is a regression that happened when we switch to async exporters. Good catch! 
I am not sure why 
> in the opentelemetry crate, span exporters are simply span processors.

in `opentelemetry` crate, [`SpanExrpoter`](https://docs.rs/opentelemetry/0.17.0/opentelemetry/sdk/export/trace/trait.SpanExporter.html#) is the span exporters. The internal queue inside the span processors are to batch the spans 

So I think we can simply check the spans before it sends to the internal queues in span processors.

**Comment by fasterthanlime** [comment]
> in `opentelemetry` crate, [`SpanExporter`](https://docs.rs/opentelemetry/0.17.0/opentelemetry/sdk/export/trace/trait.SpanExporter.html#) is the span exporters.

That's a trait, though. Third-party exporters like https://github.com/ramosbugs/opentelemetry-honeycomb-rs implement both `SpanExporter` and `SpanProcessor` on their own types, and would require a separate fix if that's how you want to approach it.

Also, simply filtering in the two built-in `{Simple,Batch}SpanProcessor` types would still create "exported span data" for every span, even if it's not sampled, so it's not my preferred solution (but I'll take any improvements in correctness I can get!)

**Comment by TommyCpp** [comment]
> That's a trait, though. 

Yeah the idea is people can bring their own exporter and those exporter will be able to work with BatchSpanProcessor or SimpleSpanProcessor in SDK.

> Third-party exporters like https://github.com/ramosbugs/opentelemetry-honeycomb-rs implement both SpanExporter and SpanProcessor on their own types

Haven't look into that repo much but I think the reason they build their own Processor is to have [a custom function](https://sourcegraph.com/github.com/ramosbugs/opentelemetry-honeycomb-rs@main/-/blob/src/lib.rs?L303&utm_source=chrome-extension&utm_campaign=hover#tab=def) before span starts.

> Also, simply filtering in the two built-in `{Simple,Batch}SpanProcessor` types would still create "exported span data" for every span, even if it's not sampled, so it's not my preferred solution

In the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#recording-sampled-reaction-table), if a span is `recording` but not `sampled` then the `SpanProcessor` should receive them but it shouldn't pass it down to the SpanExporter

If a span is not `recording` then we will drop it in `Tracers`.

I think that why this bug stays undetected even if we export it to the backend most of them just gonna drop the span without a sample flag

**Comment by jtescher** [comment]
Yeah looks like this was a regression at some point. Thanks for the detailed report @fasterthanlime!

**Comment by jtescher** [comment]
> A bad fix for this is to teach both the "simple" and "batched" exporters to ignore spans where is_sampled=false. This is bad for a bunch of reasons:
>
>    * Other exporter crates implement their own processors, which might not know they have to filter
>    * It's really not the responsibility of exporters to do filtering
 >   * build_export_data is not free, calling it for a non-sampled span is wasteful

I think this actually is the commonly accepted solution (see the [go impl](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/simple_span_processor.go#L57), [java impl](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java#L76-L78), etc), so that's the patch I submitted in  #871 to get this working properly again.

**Comment by jtescher** [comment]
Happy to keep investigating less footguy-y solutions as well, but would be good to get this fixed for the upcoming 0.18.x release so at least the sdk provided processors have the correct behavior.
