### ISSUE TITLE
Datadog exporter doesn't send resources from `trace::Config`

### ISSUE THREAD

**Issue by bnjjj** [open-telemetry/opentelemetry-rust#876]
In `DatadogExporter` resources (https://docs.rs/opentelemetry/latest/opentelemetry/sdk/trace/struct.Config.html#structfield.resource) are not sent to datadog. Only span attributes are sent to Datadog.

**Comment by lroux-at-jellysmack** [comment]
Hello @bnjjj, I also noticed that as I tried to tag a service-wide `version` for deployment tracking of my application.
Do you think the way to do it would be to also encode [`trace::Config::resource`](https://docs.rs/opentelemetry/latest/opentelemetry/sdk/trace/struct.Config.html#structfield.resource) in [there](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-datadog/src/exporter/model/v05.rs#L160) as span attributes ?

**Comment by bnjjj** [comment]
@lroux-at-jellysmack I think so :)

**Comment by abernix** [comment]
Now waiting on https://github.com/open-telemetry/opentelemetry-rust/pull/965!
