### ISSUE TITLE
Integrate `TextMapPropagator` with Tower

### ISSUE THREAD

**Issue by dbofmmbt** [open-telemetry/opentelemetry-rust#878]
Hello, I wanted to use OpenTelemetry with `axum` and it seems necessary to add some glue code between `opentelemetry` and `tower` to propagate the W3C Trace Context from a request. I hoped this implementation could be done here, behind a feature flag.

Others felt the need before, e.g. https://github.com/tower-rs/tower-http/issues/238.

I think to support tower would be a great addition, since it allows easy integration with all the clients and servers which implement `tower` traits.

**Comment by TommyCpp** [comment]
For your use case have you checked out https://github.com/davidB/axum-tracing-opentelemetry? It does seem to cover a lot on integration between opentelemetry and `axum`

**Comment by dbofmmbt** [comment]
@TommyCpp thank you for the suggestion. It indeed seems to be fit for my use case. As I was looking for something related to `tower` instead of `axum`, I didn't find it before.

I was looking for a clean integration with `tower` and `http`, but I realized after some research that there's some information specified by `otel` that is only available after the routing. So, being specific to axum allows to populate the span attributes with a few more fields.

Feel free to close this issue if you want to :smile:

**Comment by TommyCpp** [comment]
We can probably build an integration between `tower` and `opentelemetry` and put it in `contrib` creates under a feature flag. But it probably not gonna be our priority for a while.

I will close this for now.  But if there is enough interest in it we can definitely explore it. If other ppl think this integration will be helpful feel free to reopen the issue
