### ISSUE TITLE
OTLP exporters should emit standard user agent string

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-rust#889]
As per the following change in the specification (1.14 releasing Oct 4):

> OpenTelemetry protocol exporters SHOULD emit a User-Agent header to at a minimum identify the exporter, the language of its implementation, and the version of the exporter. For example, the Python OTLP exporter version 1.2.3 would report the following:
> ```OTel OTLP Exporter Python/1.2.3```

See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#user-agent

**Comment by GaryPWhite** [comment]
I'm here and happy to help!

**Comment by TommyCpp** [comment]
> I'm here and happy to help!

Thanks for the help! assigned it to you
