### ISSUE TITLE
`ObserverResult` deprecated?

### ISSUE THREAD

**Issue by jpmcb** [open-telemetry/opentelemetry-rust#900]
In `v0.16` of opentelemetry, we were using the `ObserverResult` but upon attempting to upgrade to `v0.18`, we have this breaking change I don't see documented in the changelog:

```
error[E0432]: unresolved import `opentelemetry::metrics::ObserverResult`
 --> controller/src/metrics.rs:2:22
  |
2 |     metrics::{Meter, ObserverResult},
  |                      ^^^^^^^^^^^^^^ no `ObserverResult` in `metrics`
```

I do see the `ObserverResult` has moved under the `sdk::metrics::sdk_api` module:

https://github.com/open-telemetry/opentelemetry-rust/blob/f20c9b40547ee20b6ec99414bb21abdd3a54d99b/opentelemetry-sdk/src/metrics/sdk_api/async_instrument.rs#L51-L57

but that doesn't seem to be exported in the mod:

```
error[E0432]: unresolved import `opentelemetry::sdk::metrics::sdk_api::ObserverResult`
 --> controller/src/metrics.rs:1:37
  |
1 | use opentelemetry::{metrics::Meter, sdk::metrics::sdk_api::ObserverResult, Key};
  |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ObserverResult` in `metrics::sdk_api`
```

In v0.16, it was exported in the `opentelemetry` metrics module:
https://github.com/open-telemetry/opentelemetry-rust/blob/4a649eafeaf5cd2efe18168458e85675325888cd/opentelemetry/src/metrics/mod.rs#L24

---

Was this intended to be removed from the public API? Or is there a different expectation with some of these APIs?

**Comment by TommyCpp** [comment]
Hi yes the `ObserverResult` is deprecated in favor of `Observable<Instrument>`s like `ObservableCounter`.

In v0.16, `ObserverResult` is used as the parameter of callbacks. 
```rust
 let one_metric_callback =
        |res: ObserverResult<f64>| res.observe(1.0, COMMON_ATTRIBUTES.as_ref());
```

In v0.18, in order to register a callback to be called during data collection. You can use [`register_callback`](https://docs.rs/opentelemetry/latest/opentelemetry/metrics/struct.Meter.html#method.register_callback) function in `Meter`s and pass the `Observable<Instrument>`s.
```rust
    let observable_counter = meter
        .u64_observable_counter("ex.com.one")
        .with_description("An observable counter set to 1.0")
        .init();

let _ = meter.register_callback(move |cx| {
            observable_counter.observe(cx, 1, &[]);
            observable_gauge.observe(cx, 2.0, &[]);
        });
```

**Comment by rfishrock** [comment]
> Hi yes the `ObserverResult` is deprecated in favor of `Observable<Instrument>`s like `ObservableCounter`.
> 
> In v0.16, `ObserverResult` is used as the parameter of callbacks.
> 
> ```rust
>  let one_metric_callback =
>         |res: ObserverResult<f64>| res.observe(1.0, COMMON_ATTRIBUTES.as_ref());
> ```
> 
> In v0.18, in order to register a callback to be called during data collection. You can use [`register_callback`](https://docs.rs/opentelemetry/latest/opentelemetry/metrics/struct.Meter.html#method.register_callback) function in `Meter`s and pass the `Observable<Instrument>`s.
> 
> ```rust
>     let observable_counter = meter
>         .u64_observable_counter("ex.com.one")
>         .with_description("An observable counter set to 1.0")
>         .init();
> 
> let _ = meter.register_callback(move |cx| {
>             observable_counter.observe(cx, 1, &[]);
>             observable_gauge.observe(cx, 2.0, &[]);
>         });
> ```

Heyhey, when [register_callback](https://docs.rs/opentelemetry/latest/opentelemetry/metrics/struct.Meter.html#method.register_callback) will occur the metricsError? Shall i unwrap it?

**Comment by TommyCpp** [comment]
> > Hi yes the `ObserverResult` is deprecated in favor of `Observable<Instrument>`s like `ObservableCounter`.
> > In v0.16, `ObserverResult` is used as the parameter of callbacks.
> > ```rust
> >  let one_metric_callback =
> >         |res: ObserverResult<f64>| res.observe(1.0, COMMON_ATTRIBUTES.as_ref());
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In v0.18, in order to register a callback to be called during data collection. You can use [`register_callback`](https://docs.rs/opentelemetry/latest/opentelemetry/metrics/struct.Meter.html#method.register_callback) function in `Meter`s and pass the `Observable<Instrument>`s.
> > ```rust
> >     let observable_counter = meter
> >         .u64_observable_counter("ex.com.one")
> >         .with_description("An observable counter set to 1.0")
> >         .init();
> > 
> > let _ = meter.register_callback(move |cx| {
> >             observable_counter.observe(cx, 1, &[]);
> >             observable_gauge.observe(cx, 2.0, &[]);
> >         });
> > ```
> 
> Heyhey, when [register_callback](https://docs.rs/opentelemetry/latest/opentelemetry/metrics/struct.Meter.html#method.register_callback) will occur the metricsError? Shall i unwrap it?

Generally it should only happens when the internal lock has been poisoned. If you are registering when the application starts the general guideline would be fail fast and unwrap

**Comment by jpmcb** [comment]
Thanks much for the support here - using the `register_callback` works 👍🏼
