### ISSUE TITLE
`opentelemetry-aws` version 0.6 not published on crates.io

### ISSUE THREAD

**Issue by Tuetuopay** [open-telemetry/opentelemetry-rust#902]
Hi!

I'm in the process of updating my opentelemetry stack to the latest 0.18 but I'm stuck because the updated `opentelemetry-aws` for 0.18 has not been published on crates.io. It still has the 0.5 version that targets opentelemetry 0.17.

Can you publish this crate please? Thanks!

**Comment by jtescher** [comment]
@Tuetuopay good catch, looks like that failed to upload last time. Fixed https://crates.io/crates/opentelemetry-aws/0.6.0
