### ISSUE TITLE
OTEL_EXPORTER_OTLP_ENDPOINT_DEFAULT is incorrect

### ISSUE THREAD

**Issue by BrynCooke** [open-telemetry/opentelemetry-rust#908]
According to the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md) the otlp exporter default endpoint should not use https by default.
In addition, depending on the protocol, the port number changes.

Currently the default is set to https, but this only reveals itself to be an issue when tonic `tls-roots` is enabled.
https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/src/exporter/mod.rs#L21

**Comment by TommyCpp** [comment]
close with #912. Thanks again!
