### ISSUE TITLE
span ownership with async functions

### ISSUE THREAD

**Issue by ty-elastic** [open-telemetry/opentelemetry-rust#920]
Hi, if I create a span in a function bar() and pass to another with
```
let r = foo(itemct)
  .with_context(Context::current_with_span(span))
  .await {...};
```
then ownership of the span is transferred to foo() and I can no longer add attributes in bar() after foo() completes.

Is it workable to instead save the context w/ span in bar(), pass a clone of the context to foo(), and then further manipulate the span (from the saved context) in bar after foo() completes, like this:
```
let cx = Context::current_with_span(span);
let r = foo(itemct)
  .with_context(cx.clone())
  .await {...};
cx.span().set_attribute(...);
```
?

thx!

**Comment by jtescher** [comment]
> Is it workable to instead save the context w/ span in bar(), pass a clone of the context to foo(), and then further manipulate the span (from the saved context) in bar after foo() completes, like this:
> 
> ```
> let cx = Context::current_with_span(span);
> let r = foo(itemct)
>   .with_context(cx.clone())
>   .await {...};
> cx.span().set_attribute(...);
> ```

Yes that works.
