### ISSUE TITLE
can not create rust docs for opentelemetry-proto in stable release channel.

### ISSUE THREAD

**Issue by bdalton** [open-telemetry/opentelemetry-rust#924]
I am unable to run `cargo doc` for my project which includes `opentelemetry-proto` as a transitive dependency because of an unstable feature on the first line of `src/lib.rs`. 

```rust
#![cfg_attr(doc, feature(doc_auto_cfg)]
```

The error message is: 
    error[E0554]: `#![feature]` may not be used on the stable release channel

I verified with a minimal application which includes nothing but this dependency.

**Comment by TommyCpp** [comment]
That is a conditional complication that should only work if you specify `docsrs` feature. Is that the case here?

**Comment by TommyCpp** [comment]
Will close this for now. Feel free to reopen it if it's still an issue without `docsrs` feature

**Comment by flokli** [comment]
I'm also seeing this, and I don't see a `docsrs` feature, neither in `opentelemetry`, nor in `opentelemetry-otlp`:

```
❯ cargo add opentelemetry --features rt-tokio
    Updating crates.io index
      Adding opentelemetry v0.18.0 to optional dependencies.
             Features:
             + rt-tokio
             + trace
             - metrics
             - rt-async-std
             - rt-tokio-current-thread
             - testing
```

```
    Updating crates.io index
      Adding opentelemetry-otlp v0.11.0 to optional dependencies.
             Features:
             + grpc-tonic
             + http
             + prost
             + tokio
             + tonic
             + trace
             - grpc-sys
             - grpcio
             - http-proto
             - integration-testing
             - metrics
             - openssl
             - openssl-vendored
             - opentelemetry-http
             - protobuf
             - reqwest
             - reqwest-blocking-client
             - reqwest-client
             - reqwest-rustls
             - serde
             - serialize
             - surf
             - surf-client
             - tls
             - tls-roots
```

**Comment by flokli** [comment]
Ah, this is not a feature, but a cfg flag for rustdoc.

I was able to work this around by bumping `opentelemetry-otlp` from 0.11.0 to 0.12.0 (released 17 hours ago), and then bumping `opentelemetry` itself from 0.18.0 to 0.19.0, and now indeed `cargo doc` works without any unstable stuff.
