### ISSUE TITLE
mark_span_as_active moves span, cannot add attributes later

### ISSUE THREAD

**Issue by wcarmon** [open-telemetry/opentelemetry-rust#925]
# Issue
- `mark_span_as_active` prevents span usage later in the method

# Example
```rust
    let mut span = global::tracer("").start("do_something");
    let _guard = mark_span_as_active(span); // moves here
   
    // ... some error happens 
    span.record_error(&err); // compiler fails here
```

# related
- https://docs.rs/opentelemetry/latest/opentelemetry/trace/fn.mark_span_as_active.html

**Comment by TommyCpp** [comment]
`mark_span_as_active` will make the span active within the current context(until the returned `_guard` is dropped). But you can use [`get_active_span`](https://docs.rs/opentelemetry/latest/opentelemetry/trace/fn.get_active_span.html) method to access the span that is currently active within the context
