### ISSUE TITLE
Prometheus Exporter: Counters should have _total suffix

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-rust#926]
From the [OTel prometheus spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#sums):

> Monotonic Sum metric points MUST have _total added as a suffix to the metric name.

The [current implementation](https://github.com/open-telemetry/opentelemetry-rust/blob/3820284d5a686604fd7b50530b6625865e5c4a74/opentelemetry-prometheus/src/lib.rs#L317) doesn't add a suffix to prometheus counter metrics.

**Comment by TommyCpp** [comment]
close with #952
