### ISSUE TITLE
Prometheus exporter: Use OTel Resource for target_info

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-rust#929]
From the [OTel prometheus spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#resource-attributes-1), resource attributes should be used to make a `target_info` metric:

> In SDK Prometheus (pull) exporters, resource attributes SHOULD be converted to a single [target_info metric](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#supporting-target-metadata-in-both-push-based-and-pull-based-systems); otherwise, they MUST be dropped, and MUST NOT be attached as labels to other metric families. The target_info metric MUST be an info-typed metric whose labels MUST include the resource attributes, and MUST NOT include any other labels. There MUST be at most one target_info metric exposed on an SDK Prometheus endpoint.

The [current implementation](https://github.com/open-telemetry/opentelemetry-rust/blob/3820284d5a686604fd7b50530b6625865e5c4a74/opentelemetry-prometheus/src/lib.rs#L394) adds resource attributes to all metrics on the endpoint.  The [OpenMetrics spec](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#supporting-target-metadata-in-both-push-based-and-pull-based-systems) says we can't do that: 

> Exposers MUST NOT add target metadata labels to all Metrics from an exposition, unless explicitly configured for a specific ingestor.

**Comment by jtescher** [comment]
Resolved in #1000
