### ISSUE TITLE
OTLP Metrics Exporter causes dropped spans and logs when created before `tracing` global dispatcher initialization

### ISSUE THREAD

**Issue by neoeinstein** [open-telemetry/opentelemetry-rust#932]
Issue reported here: tokio-rs/tracing#2411

Cross-reported here for anyone who might have been trying to add the OTLP Metrics exporter layer into a registry. The exporter needs to be initialized prior to the `BasicController` being registered as a `MetricsLayer` in the `tracing_subscriber` registry. Once created, a `tower::Buffer` layer in the Tonic gRPC stack results results in a poll on `tracing::Span::current()` this pull is highly likely to happen before the registry setup is complete, resulting in the thread-local tracing dispatchers becoming poisoned.

This may be fixed over on the `tracing` side, but I figured I'd raise the issue here in case there was something that could be done on this side too, such as having a call that would enable the periodic scrape and export after the `Registry` had been properly set as the global dispatcher. Otherwise, it will be a signpost to anyone as confused as I was that spans were not properly associating and log messages appeared to be dropped into a black hole.

**Comment by cijothomas** [comment]
Closing as the linked issue is resolved in the tracing repo.!
