### ISSUE TITLE
Would it be possible to publish a new release?

### ISSUE THREAD

**Issue by vlad-ivanov-name** [open-telemetry/opentelemetry-rust#934]
The latest release does not include fix for https://github.com/open-telemetry/opentelemetry-rust/issues/873

This means that all projects depending on [opentelemetry-otlp](https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-otlp) need to have `protoc` at build time. It's a big and heavy dependency and some projects would prefer to avoid it, even at build time.

Would it be possible to publish e.g. 0.18.1 release?

**Comment by TommyCpp** [comment]
I will prepare a release by end of month

**Comment by bearcage** [comment]
Every now and again I bump into #873 on various projects and add some flavor of `brew install protoc` to the relevant machines -- it'd be great to not need that!

Is there anything you'd like help with to cut a new release? I could lend a hand here instead of patching protoc installers in, next time it comes up.

**Comment by TommyCpp** [comment]
Hi @bearcage Sorry for the delay. I think we the only blocking PR is https://github.com/open-telemetry/opentelemetry-rust/pull/969. I have the patch for MSRV once it merged I will clean up and add any missing changlog

**Comment by bearcage** [comment]
Oh, awesome — no need to apologize, you're the one doing the maintenance work! Thanks for coming back to this, it'll be nice to have one less dependency to carry around.

**Comment by kenkoooo** [comment]
Hi! Thank you for working on it so hard! Is there anything I can help with to publish a new release?

**Comment by TommyCpp** [comment]
close with #965
