### ISSUE TITLE
suggestion: use env!("CARGO_BIN_NAME") instead of "unknown_service" as default service name

### ISSUE THREAD

**Issue by lovasoa** [open-telemetry/opentelemetry-rust#942]
Currently, when there is no service name defined, this library annotates everything with `service_name="unknown_service"`, which is not very useful. It could simply not include service_name, or even better, use the value of `CARGO_BIN_NAME` (defined at runtime) to extract a meaningful name.

**Comment by jtescher** [comment]
This value and behavior is defined in the spec in https://github.com/open-telemetry/opentelemetry-specification/blob/b00980832b4b823155001df56dbf9203d4e53f98/semantic_conventions/resource/service.yaml#L14-L17

But as the bin name is likely what the user would want here I think that using it as a fallback would likely be the less surprising choice, so I'm for this option if someone wants to submit a PR.

**Comment by hdost** [comment]
Seems like it should be behind a feature flag perhaps? as it's not per spec.

**Comment by djc** [comment]
If it goes behind a feature flag I think it should be opt-out, not opt-in. For Rust the spec behavior doesn't make as much sense since the binary name will generally be a good default for the service name (unlike for code that is executed using an interpreter, as the spec implies).

**Comment by TommyCpp** [comment]
I feel like the feature flag may be too heavy for this. Maybe sufficient to have a configure function that allows users to provide a default service name and we can default to use cargo bin name.

**Comment by hdost** [comment]
So precedent (high to low):
- Builder option
- Environment Var
- Build Variable

**Comment by danielschaffel** [comment]
I have been working on this issue and would love to be assigned it. 

However I don't understand where this `Builder` option belongs. Should it be added to the [`EnvResourceDetector`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/resource/env.rs#L20)?
