### ISSUE TITLE
It should be possible to create Metrics exporters without mutating the global meter provider

### ISSUE THREAD

**Issue by BrynCooke** [open-telemetry/opentelemetry-rust#947]
Currently all metrics exporters call ` global::set_meter_provider` on init.

The spec states that it should be possible to configure multiple exporters
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricexporter

But having all meter providers mutate global state make this difficult to achieve.

**Comment by TommyCpp** [comment]
Yeah we can add addtional methods to build exporters on pipelines. I will open a PR for it

**Comment by jtescher** [comment]
Resolved in #1156
