### ISSUE TITLE
Support callback unregistration

### ISSUE THREAD

**Issue by TommyCpp** [open-telemetry/opentelemetry-rust#958]
The spec requires API to support unregister the callback registered outside instrument initialization. See [here](https://github.com/open-telemetry/opentelemetry-specification/blob/b00980832b4b823155001df56dbf9203d4e53f98/specification/metrics/api.md#asynchronous-gauge-operations)

> For callback functions registered after an asynchronous instrument is created, the API is required to support a mechanism for unregistration. For example, the object returned from register_callback can support an unregister() method directly.

**Comment by lzchen** [comment]
@TommyCpp 
Is there anything that needs to be [discussed](https://github.com/open-telemetry/opentelemetry-rust/issues/955#issuecomment-1407318302) before this can be implemented?

**Comment by TommyCpp** [comment]
I think it's already implemented in the new metrics implementation?

**Comment by lzchen** [comment]
This issue can probably be resolved then right? @jtescher

**Comment by jtescher** [comment]
Resolved in #1156
