### ISSUE TITLE
In-Memory Metrics Exporter

### ISSUE THREAD

**Issue by Sushisource** [open-telemetry/opentelemetry-rust#961]
Hey all,

Didn't see an open issue for this so I figured I'd add one. It would be great to have an in-memory exporter per the spec [here](https://opentelemetry.io/docs/reference/specification/metrics/sdk_exporters/in-memory/) to make testing metric reporting a bit easier.

I might be able to make a contribution if this is an area where one would be welcome.

Thanks!

**Comment by TommyCpp** [comment]
> I might be able to make a contribution if this is an area where one would be welcome

Contributions are always welcome 🙌 . Feel free to let me know if you run into any problems. We probably want to think about what data structure should the exporter store the metrics in(probably gonna be a some kind of map but need to decide key and values).
