### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by wcarmon** [open-telemetry/opentelemetry-rust#966]
Lines 185 and 187 of this file seem conflicting:

- https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-jaeger/src/lib.rs#L185
- https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-jaeger/src/lib.rs#L187

**Comment by djc** [comment]
That's indeed pretty strange. Want to submit a PR?
