### ISSUE TITLE
Slack vs Gitter?

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#978]
All the other SIGs in OpenTelemetry has moved from Gitter to use the CNCF Slack : https://github.com/open-telemetry/community#special-interest-groups

Any objection if OTel-Rust is also moved to slack? 
If no objection, I can create the slack channel (if not existing), and update the repo (this repo, community repo) to point to the new place.

**Comment by reyang** [comment]
There seems to be one already, maybe the doc is outdated https://app.slack.com/client/T08PSQ7BQ/C03GDP0H023/thread/C02KF2PPUV9-1677693866.155779.

**Comment by hdost** [comment]
As I understand it the maintainers for the rust sig prefer gitter as [it's more open](https://cloud-native.slack.com/archives/C03GDP0H023/p1674677013566679), since anyone who already has a github account already has access. 
I personally don't have a stake, but playing Devil's Advocate. Just because Slack is popular in the US doesn't mean it's universal or that it has to be the only way. This comes from somebody who spends every working day in Slack.

**Comment by reyang** [comment]
> As I understand it the maintainers for the rust sig prefer gitter as [it's more open](https://cloud-native.slack.com/archives/C03GDP0H023/p1674677013566679), since anyone who already has a github account already has access. I personally don't have a stake, but playing Devil's Advocate. Just because Slack is popular in the US doesn't mean it's universal or that it has to be the only way. This comes from somebody who spends every working day in Slack.

I guess this is more a decision from CNCF and OpenTelemetry? https://github.com/open-telemetry/community/blob/19b7054626d5b2b19632bc02e37d10ae7392ed4c/README.md#discussions

**Comment by hdost** [comment]
> > As I understand it the maintainers for the rust sig prefer gitter as [it's more open](https://cloud-native.slack.com/archives/C03GDP0H023/p1674677013566679), since anyone who already has a github account already has access. I personally don't have a stake, but playing Devil's Advocate. Just because Slack is popular in the US doesn't mean it's universal or that it has to be the only way. This comes from somebody who spends every working day in Slack.
> 
> 
> 
> I guess this is more a decision from CNCF and OpenTelemetry? https://github.com/open-telemetry/community/blob/19b7054626d5b2b19632bc02e37d10ae7392ed4c/README.md#discussions

I don't know if seeing if there is considered a decision. There was also on the website, I mentioned that the tracing in the Rust implementation was considered stable, which was not true, and I corrected it.  Potentially what needs to be fixed is the documentation page pointing to the Gitter, not Slack. For all, we know, the person that put together the page saw that there was a channel #otel-rust and put it in the page.

As an addendum to my previous comment about openness gitter is a front over Matrix which means it's possible for a wider swath of people to connect similar to IRC.

**Comment by hdost** [comment]
Ultimately @open-telemetry/rust-maintainers will need to respond on this. From an organizational perspective of CNCF I understand the want for uniformity, but I honestly find it ironic that an open source project strictly uses a non-open source product for its primary method of communication (he knowingly says, typing into github.com owned by Microsoft).

**Comment by djc** [comment]
I dislike Slack a little bit more than Gitter/Matrix, but I probably won't spend much time in this chat anyway so not sure my vote is very important.

**Comment by TommyCpp** [comment]
I have been monitoring the Slack channel in case someone asks a question there. I personally perfer the Slack but also understand the concern of it's not been open source. I guess one option is to use Slack as primary way of communication and redirect any major issues to Github and discuss as discussion so everyone can chaim in.

**Comment by cijothomas** [comment]
The openness of Gitter was already taken into consideration, when OTel org (I think spec sig moved first) decided to move to slack in early 2021. At this stage, I think this group should align with the rest of the ecosystem, given every other SIGs have switched to Slack 2 years ago and they are operating smoothly.

From what I see in this discussions, nobody has strong opposition to move to Slack.
I'll send a PR to replace Gitter links with slack. The slack channel description already has link to the Gitter channel incase someone want to refer to old conversations.

*If anyone strongly opposes this, please block the PR.*

**Comment by hdost** [comment]
> The openness of Gitter was already taken into consideration, when OTel org (I think spec sig moved first) decided to move to Slack in early 2021. At this stage, I think this group should align with the rest of the ecosystem, given every other SIGs have switched to Slack 2 years ago and they are operating smoothly.

In principle I don't think switching will change much. Other than people will stop asking why we're not using Slack. There's simultaneously no need to kill the Gitter since others have mentioned they prefer it. I wouldn't personally block making the official as Slack. If it brings more contributions great.
