### ISSUE TITLE
Bump otel-proto

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-rust#989]
opentelemetry-proto points to 0.14.0
Bump to https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.19.0

**Comment by hdost** [comment]
@open-telemetry/rust-maintainers  I think we should consider removing the generation from the standard tests. Or at least ignoring them normally. We could have them run on a scheduled basis instead.

**Comment by djc** [comment]
If you're going to update the proto definitions I think it makes sense to update the generated code in the same PR -- or am I missing something here? An issue might be that we don't version the `Cargo.lock` file, which means that updates to the code generation dependencies can make CI fail. IMO it might be reasonable to start versioning `Cargo.lock` instead.

**Comment by hdost** [comment]
> IMO it might be reasonable to start versioning `Cargo.lock` instead.

There's no side effects for the crates published, right? If so I wouldn't be opposed.
