### ISSUE TITLE
[security] cargo audit for remove_dir_all < 0.8.0

### ISSUE THREAD

**Issue by Oliboy50** [open-telemetry/opentelemetry-rust#993]
## What?

Running `cargo audit` (i.e. with the `cargo-audit` binary installed) from a project which depends on `opentelemetry-otlp 0.11.0` results in an error:

```shell
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Crate:     remove_dir_all
Version:   0.5.3
Title:     Race Condition Enabling Link Following and Time-of-check Time-of-use (TOCTOU)
Date:      2023-02-24
ID:        RUSTSEC-2023-0018
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0018
Solution:  Upgrade to >=0.8.0
Dependency tree:
remove_dir_all 0.5.3
└── tempfile 3.3.0
    └── prost-build 0.11.5
        └── tonic-build 0.8.4
            └── opentelemetry-proto 0.1.0
                └── opentelemetry-otlp 0.11.0
                    └── my-project x.y.z
```

## How?

I think that releasing a new version of opentelemetry-otlp and/or opentelemetry-proto with the current state of the main branch should fix this issue, because it seems to have been fixed [in this commit](https://github.com/open-telemetry/opentelemetry-rust/commit/d571b24ad1f3a63db6d9e5cae5ce2c2b57223edd#diff-03e3c7c6b25caacfc9a7687009852b1d98272cf63ad65f3dcecd005aabaae617R59) which moved `tonic-build` dependency from `build-dependencies` to `dev-dependencies` and therefore should not impact userland projects anymore

**Comment by TommyCpp** [comment]
> I think that releasing a new version of opentelemetry-otlp and/or opentelemetry-proto with the current state of the main branch should fix this issue

With  0.19 release it should be solved.
