### ISSUE TITLE
Compiling opentelemetry-otlp with tonic without protoc installed

### ISSUE THREAD

**Issue by oddgrd** [open-telemetry/opentelemetry-rust#999]
Hey! I am not sure if this is the right place for questions like this, but I didn't find another issue like this, and I can't access the slack (I think 😅). Please let me know if there is a better place for questions and I'll ask there instead.

So my question is: is there any way around needing to install protoc to compile a crate that depends on `opentelemetry-otlp` with grpc-tonic? I tried using the grpcio exporter instead, which works, but it added a ton of time to compilations. I also depend on tonic in one of my own crates, but I was able to used a vendored protoc for that: https://crates.io/crates/protoc-bin-vendored. 

If anyone knows a way to do this, or can direct me to some resources on how to achieve this, I would appreciate it very much. Thanks! 🙏

**Comment by djc** [comment]
I think we did that in #881, maybe have a look at current main to see if it works better for you? We hope to get a release out soonish (see #965).

**Comment by oddgrd** [comment]
Oh, I can't believe I missed that :facepalm: Thank you very much, that should solve my problem!
